   

namespace InvAcc.Forms
{
partial class FrmPointsCalc
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
    
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(InvAcc.Forms.FrmPointsCalc));
            groupPanel1 = new DevComponents.DotNetBar.Controls.GroupPanel();
            txtTotalPoint = new DevComponents.Editors.DoubleInput();
            button_UpdatePoint = new DevComponents.DotNetBar.ButtonX();
            label4 = new System.Windows.Forms.Label();
            button_SrchItemGroup = new DevComponents.DotNetBar.ButtonX();
            txtClassName = new System.Windows.Forms.TextBox();
            txtClassNo = new System.Windows.Forms.TextBox();
            label3 = new System.Windows.Forms.Label();
            label2 = new System.Windows.Forms.Label();
            txtTotalPurchaes = new DevComponents.Editors.DoubleInput();
            Label1 = new System.Windows.Forms.Label();
            groupPanel4 = new DevComponents.DotNetBar.Controls.GroupPanel();
            labelCurr = new System.Windows.Forms.Label();
            txtPointOfRyal = new DevComponents.Editors.DoubleInput();
            label12 = new System.Windows.Forms.Label();
            ButExit = new DevComponents.DotNetBar.ButtonX();
            ButOk = new DevComponents.DotNetBar.ButtonX();
            groupPanel5 = new DevComponents.DotNetBar.Controls.GroupPanel();
            txtItem4E = new System.Windows.Forms.TextBox();
            txtItem3E = new System.Windows.Forms.TextBox();
            txtItem2E = new System.Windows.Forms.TextBox();
            txtItem1E = new System.Windows.Forms.TextBox();
            textBox1 = new System.Windows.Forms.TextBox();
            textBox6 = new System.Windows.Forms.TextBox();
            textBox7 = new System.Windows.Forms.TextBox();
            textBox8 = new System.Windows.Forms.TextBox();
            integerInput5 = new DevComponents.Editors.IntegerInput();
            integerInput6 = new DevComponents.Editors.IntegerInput();
            integerInput7 = new DevComponents.Editors.IntegerInput();
            integerInput8 = new DevComponents.Editors.IntegerInput();
            textBox5 = new System.Windows.Forms.TextBox();
            textBox4 = new System.Windows.Forms.TextBox();
            textBox3 = new System.Windows.Forms.TextBox();
            textBox2 = new System.Windows.Forms.TextBox();
            txtItem4 = new System.Windows.Forms.TextBox();
            integerInput4 = new DevComponents.Editors.IntegerInput();
            txtItem3 = new System.Windows.Forms.TextBox();
            integerInput3 = new DevComponents.Editors.IntegerInput();
            txtItem2 = new System.Windows.Forms.TextBox();
            integerInput2 = new DevComponents.Editors.IntegerInput();
            txtItem1 = new System.Windows.Forms.TextBox();
            integerInput1 = new DevComponents.Editors.IntegerInput();
            groupPanel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)txtTotalPoint).BeginInit();
            ((System.ComponentModel.ISupportInitialize)txtTotalPurchaes).BeginInit();
            groupPanel4.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)txtPointOfRyal).BeginInit();
            groupPanel5.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)integerInput5).BeginInit();
            ((System.ComponentModel.ISupportInitialize)integerInput6).BeginInit();
            ((System.ComponentModel.ISupportInitialize)integerInput7).BeginInit();
            ((System.ComponentModel.ISupportInitialize)integerInput8).BeginInit();
            ((System.ComponentModel.ISupportInitialize)integerInput4).BeginInit();
            ((System.ComponentModel.ISupportInitialize)integerInput3).BeginInit();
            ((System.ComponentModel.ISupportInitialize)integerInput2).BeginInit();
            ((System.ComponentModel.ISupportInitialize)integerInput1).BeginInit();
            SuspendLayout();
            groupPanel1.AccessibleDescription = null;
            groupPanel1.AccessibleName = null;
            resources.ApplyResources(groupPanel1, "groupPanel1");
            groupPanel1.CanvasColor = System.Drawing.SystemColors.Control;
            groupPanel1.ColorSchemeStyle = DevComponents.DotNetBar.eDotNetBarStyle.StyleManagerControlled;
            groupPanel1.Controls.Add(txtTotalPoint);
            groupPanel1.Controls.Add(button_UpdatePoint);
            groupPanel1.Controls.Add(label4);
            groupPanel1.Controls.Add(button_SrchItemGroup);
            groupPanel1.Controls.Add(txtClassName);
            groupPanel1.Controls.Add(txtClassNo);
            groupPanel1.Controls.Add(label3);
            groupPanel1.Controls.Add(label2);
            groupPanel1.Controls.Add(txtTotalPurchaes);
            groupPanel1.Controls.Add(Label1);
            groupPanel1.Name = "groupPanel1";
            groupPanel1.Style.BackColor2SchemePart = DevComponents.DotNetBar.eColorSchemePart.PanelBackground2;
            groupPanel1.Style.BackColorGradientAngle = 90;
            groupPanel1.Style.BackColorSchemePart = DevComponents.DotNetBar.eColorSchemePart.PanelBackground;
            groupPanel1.Style.BorderBottom = DevComponents.DotNetBar.eStyleBorderType.Solid;
            groupPanel1.Style.BorderBottomWidth = 1;
            groupPanel1.Style.BorderColorSchemePart = DevComponents.DotNetBar.eColorSchemePart.PanelBorder;
            groupPanel1.Style.BorderLeft = DevComponents.DotNetBar.eStyleBorderType.Solid;
            groupPanel1.Style.BorderLeftWidth = 1;
            groupPanel1.Style.BorderRight = DevComponents.DotNetBar.eStyleBorderType.Solid;
            groupPanel1.Style.BorderRightWidth = 1;
            groupPanel1.Style.BorderTop = DevComponents.DotNetBar.eStyleBorderType.Solid;
            groupPanel1.Style.BorderTopWidth = 1;
            groupPanel1.Style.CornerDiameter = 4;
            groupPanel1.Style.CornerType = DevComponents.DotNetBar.eCornerType.Rounded;
            groupPanel1.Style.TextAlignment = DevComponents.DotNetBar.eStyleTextAlignment.Center;
            groupPanel1.Style.TextColorSchemePart = DevComponents.DotNetBar.eColorSchemePart.PanelText;
            groupPanel1.Style.TextLineAlignment = DevComponents.DotNetBar.eStyleTextAlignment.Near;
            groupPanel1.StyleMouseDown.CornerType = DevComponents.DotNetBar.eCornerType.Square;
            groupPanel1.StyleMouseOver.CornerType = DevComponents.DotNetBar.eCornerType.Square;
            groupPanel1.TitleImagePosition = DevComponents.DotNetBar.eTitleImagePosition.Center;
            txtTotalPoint.AccessibleDescription = null;
            txtTotalPoint.AccessibleName = null;
            txtTotalPoint.AllowEmptyState = false;
            resources.ApplyResources(txtTotalPoint, "txtTotalPoint");
            txtTotalPoint.BackgroundImage = null;
            txtTotalPoint.BackgroundStyle.BackColor = System.Drawing.Color.FromArgb(255, 255, 0);
            txtTotalPoint.BackgroundStyle.Class = "DateTimeInputBackground";
            txtTotalPoint.BackgroundStyle.CornerType = DevComponents.DotNetBar.eCornerType.Square;
            txtTotalPoint.ButtonCalculator.DisplayPosition = (int)resources.GetObject("txtTotalPoint.ButtonCalculator.DisplayPosition");
            txtTotalPoint.ButtonCalculator.Image = null;
            txtTotalPoint.ButtonCalculator.Text = resources.GetString("txtTotalPoint.ButtonCalculator.Text");
            txtTotalPoint.ButtonClear.DisplayPosition = (int)resources.GetObject("txtTotalPoint.ButtonClear.DisplayPosition");
            txtTotalPoint.ButtonClear.Image = null;
            txtTotalPoint.ButtonClear.Text = resources.GetString("txtTotalPoint.ButtonClear.Text");
            txtTotalPoint.ButtonCustom.DisplayPosition = (int)resources.GetObject("txtTotalPoint.ButtonCustom.DisplayPosition");
            txtTotalPoint.ButtonCustom.Image = null;
            txtTotalPoint.ButtonCustom.Text = resources.GetString("txtTotalPoint.ButtonCustom.Text");
            txtTotalPoint.ButtonCustom2.DisplayPosition = (int)resources.GetObject("txtTotalPoint.ButtonCustom2.DisplayPosition");
            txtTotalPoint.ButtonCustom2.Image = null;
            txtTotalPoint.ButtonCustom2.Text = resources.GetString("txtTotalPoint.ButtonCustom2.Text");
            txtTotalPoint.ButtonDropDown.DisplayPosition = (int)resources.GetObject("txtTotalPoint.ButtonDropDown.DisplayPosition");
            txtTotalPoint.ButtonDropDown.Image = null;
            txtTotalPoint.ButtonDropDown.Text = resources.GetString("txtTotalPoint.ButtonDropDown.Text");
            txtTotalPoint.ButtonFreeText.DisplayPosition = (int)resources.GetObject("txtTotalPoint.ButtonFreeText.DisplayPosition");
            txtTotalPoint.ButtonFreeText.Image = null;
            txtTotalPoint.ButtonFreeText.Shortcut = DevComponents.DotNetBar.eShortcut.F2;
            txtTotalPoint.ButtonFreeText.Text = resources.GetString("txtTotalPoint.ButtonFreeText.Text");
            txtTotalPoint.CommandParameter = null;
            txtTotalPoint.DisplayFormat = "0.00";
            txtTotalPoint.Increment = 0.0;
            txtTotalPoint.InputHorizontalAlignment = DevComponents.Editors.eHorizontalAlignment.Center;
            txtTotalPoint.MinValue = 0.0;
            txtTotalPoint.Name = "txtTotalPoint";
            txtTotalPoint.ShowUpDown = true;
            button_UpdatePoint.AccessibleDescription = null;
            button_UpdatePoint.AccessibleName = null;
            button_UpdatePoint.AccessibleRole = System.Windows.Forms.AccessibleRole.PushButton;
            resources.ApplyResources(button_UpdatePoint, "button_UpdatePoint");
            button_UpdatePoint.BackgroundImage = null;
            button_UpdatePoint.ColorTable = DevComponents.DotNetBar.eButtonColor.Office2007WithBackground;
            button_UpdatePoint.CommandParameter = null;
            button_UpdatePoint.Name = "button_UpdatePoint";
            button_UpdatePoint.Style = DevComponents.DotNetBar.eDotNetBarStyle.StyleManagerControlled;
            button_UpdatePoint.Symbol = "\uf021";
            button_UpdatePoint.SymbolSize = 16f;
            button_UpdatePoint.TextColor = System.Drawing.Color.Black;
            button_UpdatePoint.Click += new System.EventHandler(button_UpdatePoint_Click);
            label4.AccessibleDescription = null;
            label4.AccessibleName = null;
            resources.ApplyResources(label4, "label4");
            label4.BackColor = System.Drawing.Color.Transparent;
            label4.Name = "label4";
            button_SrchItemGroup.AccessibleDescription = null;
            button_SrchItemGroup.AccessibleName = null;
            button_SrchItemGroup.AccessibleRole = System.Windows.Forms.AccessibleRole.PushButton;
            resources.ApplyResources(button_SrchItemGroup, "button_SrchItemGroup");
            button_SrchItemGroup.BackgroundImage = null;
            button_SrchItemGroup.ColorTable = DevComponents.DotNetBar.eButtonColor.OrangeWithBackground;
            button_SrchItemGroup.CommandParameter = null;
            button_SrchItemGroup.Font = null;
            button_SrchItemGroup.Name = "button_SrchItemGroup";
            button_SrchItemGroup.Style = DevComponents.DotNetBar.eDotNetBarStyle.StyleManagerControlled;
            button_SrchItemGroup.Symbol = "\uf002";
            button_SrchItemGroup.SymbolSize = 12f;
            button_SrchItemGroup.TextColor = System.Drawing.Color.SteelBlue;
            button_SrchItemGroup.Click += new System.EventHandler(button_SrchItemGroup_Click);
            txtClassName.AccessibleDescription = null;
            txtClassName.AccessibleName = null;
            resources.ApplyResources(txtClassName, "txtClassName");
            txtClassName.BackColor = System.Drawing.Color.DarkSeaGreen;
            txtClassName.BackgroundImage = null;
            txtClassName.Font = null;
            txtClassName.ForeColor = System.Drawing.Color.White;
            txtClassName.Name = "txtClassName";
            txtClassName.ReadOnly = true;
            txtClassNo.AccessibleDescription = null;
            txtClassNo.AccessibleName = null;
            resources.ApplyResources(txtClassNo, "txtClassNo");
            txtClassNo.BackColor = System.Drawing.Color.White;
            txtClassNo.BackgroundImage = null;
            txtClassNo.Font = null;
            txtClassNo.Name = "txtClassNo";
            txtClassNo.ReadOnly = true;
            txtClassNo.Tag = " T_CATEGORY.CAT_ID ";
            label3.AccessibleDescription = null;
            label3.AccessibleName = null;
            resources.ApplyResources(label3, "label3");
            label3.BackColor = System.Drawing.Color.Transparent;
            label3.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            label3.Name = "label3";
            label2.AccessibleDescription = null;
            label2.AccessibleName = null;
            resources.ApplyResources(label2, "label2");
            label2.BackColor = System.Drawing.Color.Transparent;
            label2.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            label2.Name = "label2";
            txtTotalPurchaes.AccessibleDescription = null;
            txtTotalPurchaes.AccessibleName = null;
            txtTotalPurchaes.AllowEmptyState = false;
            resources.ApplyResources(txtTotalPurchaes, "txtTotalPurchaes");
            txtTotalPurchaes.BackgroundImage = null;
            txtTotalPurchaes.BackgroundStyle.BackColor = System.Drawing.Color.FromArgb(255, 255, 255);
            txtTotalPurchaes.BackgroundStyle.Class = "DateTimeInputBackground";
            txtTotalPurchaes.BackgroundStyle.CornerType = DevComponents.DotNetBar.eCornerType.Square;
            txtTotalPurchaes.ButtonCalculator.DisplayPosition = (int)resources.GetObject("txtTotalPurchaes.ButtonCalculator.DisplayPosition");
            txtTotalPurchaes.ButtonCalculator.Image = null;
            txtTotalPurchaes.ButtonCalculator.Text = resources.GetString("txtTotalPurchaes.ButtonCalculator.Text");
            txtTotalPurchaes.ButtonClear.DisplayPosition = (int)resources.GetObject("txtTotalPurchaes.ButtonClear.DisplayPosition");
            txtTotalPurchaes.ButtonClear.Image = null;
            txtTotalPurchaes.ButtonClear.Text = resources.GetString("txtTotalPurchaes.ButtonClear.Text");
            txtTotalPurchaes.ButtonCustom.DisplayPosition = (int)resources.GetObject("txtTotalPurchaes.ButtonCustom.DisplayPosition");
            txtTotalPurchaes.ButtonCustom.Image = null;
            txtTotalPurchaes.ButtonCustom.Text = resources.GetString("txtTotalPurchaes.ButtonCustom.Text");
            txtTotalPurchaes.ButtonCustom2.DisplayPosition = (int)resources.GetObject("txtTotalPurchaes.ButtonCustom2.DisplayPosition");
            txtTotalPurchaes.ButtonCustom2.Image = null;
            txtTotalPurchaes.ButtonCustom2.Text = resources.GetString("txtTotalPurchaes.ButtonCustom2.Text");
            txtTotalPurchaes.ButtonDropDown.DisplayPosition = (int)resources.GetObject("txtTotalPurchaes.ButtonDropDown.DisplayPosition");
            txtTotalPurchaes.ButtonDropDown.Image = null;
            txtTotalPurchaes.ButtonDropDown.Text = resources.GetString("txtTotalPurchaes.ButtonDropDown.Text");
            txtTotalPurchaes.ButtonFreeText.DisplayPosition = (int)resources.GetObject("txtTotalPurchaes.ButtonFreeText.DisplayPosition");
            txtTotalPurchaes.ButtonFreeText.Image = null;
            txtTotalPurchaes.ButtonFreeText.Shortcut = DevComponents.DotNetBar.eShortcut.F2;
            txtTotalPurchaes.ButtonFreeText.Text = resources.GetString("txtTotalPurchaes.ButtonFreeText.Text");
            txtTotalPurchaes.CommandParameter = null;
            txtTotalPurchaes.DisplayFormat = "0.00";
            txtTotalPurchaes.Increment = 0.0;
            txtTotalPurchaes.InputHorizontalAlignment = DevComponents.Editors.eHorizontalAlignment.Center;
            txtTotalPurchaes.MinValue = 0.0;
            txtTotalPurchaes.Name = "txtTotalPurchaes";
            Label1.AccessibleDescription = null;
            Label1.AccessibleName = null;
            resources.ApplyResources(Label1, "Label1");
            Label1.BackColor = System.Drawing.Color.Transparent;
            Label1.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            Label1.Name = "Label1";
            groupPanel4.AccessibleDescription = null;
            groupPanel4.AccessibleName = null;
            resources.ApplyResources(groupPanel4, "groupPanel4");
            groupPanel4.CanvasColor = System.Drawing.SystemColors.Control;
            groupPanel4.ColorSchemeStyle = DevComponents.DotNetBar.eDotNetBarStyle.StyleManagerControlled;
            groupPanel4.Controls.Add(labelCurr);
            groupPanel4.Controls.Add(txtPointOfRyal);
            groupPanel4.Controls.Add(label12);
            groupPanel4.Name = "groupPanel4";
            groupPanel4.Style.BackColor2SchemePart = DevComponents.DotNetBar.eColorSchemePart.PanelBackground2;
            groupPanel4.Style.BackColorGradientAngle = 90;
            groupPanel4.Style.BackColorSchemePart = DevComponents.DotNetBar.eColorSchemePart.PanelBackground;
            groupPanel4.Style.BorderBottom = DevComponents.DotNetBar.eStyleBorderType.Solid;
            groupPanel4.Style.BorderBottomWidth = 1;
            groupPanel4.Style.BorderColorSchemePart = DevComponents.DotNetBar.eColorSchemePart.PanelBorder;
            groupPanel4.Style.BorderLeft = DevComponents.DotNetBar.eStyleBorderType.Solid;
            groupPanel4.Style.BorderLeftWidth = 1;
            groupPanel4.Style.BorderRight = DevComponents.DotNetBar.eStyleBorderType.Solid;
            groupPanel4.Style.BorderRightWidth = 1;
            groupPanel4.Style.BorderTop = DevComponents.DotNetBar.eStyleBorderType.Solid;
            groupPanel4.Style.BorderTopWidth = 1;
            groupPanel4.Style.CornerDiameter = 4;
            groupPanel4.Style.CornerType = DevComponents.DotNetBar.eCornerType.Rounded;
            groupPanel4.Style.TextAlignment = DevComponents.DotNetBar.eStyleTextAlignment.Center;
            groupPanel4.Style.TextColorSchemePart = DevComponents.DotNetBar.eColorSchemePart.PanelText;
            groupPanel4.Style.TextLineAlignment = DevComponents.DotNetBar.eStyleTextAlignment.Near;
            groupPanel4.StyleMouseDown.CornerType = DevComponents.DotNetBar.eCornerType.Square;
            groupPanel4.StyleMouseOver.CornerType = DevComponents.DotNetBar.eCornerType.Square;
            groupPanel4.TitleImagePosition = DevComponents.DotNetBar.eTitleImagePosition.Center;
            labelCurr.AccessibleDescription = null;
            labelCurr.AccessibleName = null;
            resources.ApplyResources(labelCurr, "labelCurr");
            labelCurr.BackColor = System.Drawing.Color.Transparent;
            labelCurr.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            labelCurr.ForeColor = System.Drawing.SystemColors.HotTrack;
            labelCurr.Name = "labelCurr";
            txtPointOfRyal.AccessibleDescription = null;
            txtPointOfRyal.AccessibleName = null;
            txtPointOfRyal.AllowEmptyState = false;
            resources.ApplyResources(txtPointOfRyal, "txtPointOfRyal");
            txtPointOfRyal.BackgroundImage = null;
            txtPointOfRyal.BackgroundStyle.BackColor = System.Drawing.Color.FromArgb(255, 130, 132);
            txtPointOfRyal.BackgroundStyle.Class = "DateTimeInputBackground";
            txtPointOfRyal.BackgroundStyle.CornerType = DevComponents.DotNetBar.eCornerType.Square;
            txtPointOfRyal.ButtonCalculator.DisplayPosition = (int)resources.GetObject("txtPointOfRyal.ButtonCalculator.DisplayPosition");
            txtPointOfRyal.ButtonCalculator.Image = null;
            txtPointOfRyal.ButtonCalculator.Text = resources.GetString("txtPointOfRyal.ButtonCalculator.Text");
            txtPointOfRyal.ButtonClear.DisplayPosition = (int)resources.GetObject("txtPointOfRyal.ButtonClear.DisplayPosition");
            txtPointOfRyal.ButtonClear.Image = null;
            txtPointOfRyal.ButtonClear.Text = resources.GetString("txtPointOfRyal.ButtonClear.Text");
            txtPointOfRyal.ButtonCustom.DisplayPosition = (int)resources.GetObject("txtPointOfRyal.ButtonCustom.DisplayPosition");
            txtPointOfRyal.ButtonCustom.Image = null;
            txtPointOfRyal.ButtonCustom.Text = resources.GetString("txtPointOfRyal.ButtonCustom.Text");
            txtPointOfRyal.ButtonCustom2.DisplayPosition = (int)resources.GetObject("txtPointOfRyal.ButtonCustom2.DisplayPosition");
            txtPointOfRyal.ButtonCustom2.Image = null;
            txtPointOfRyal.ButtonCustom2.Text = resources.GetString("txtPointOfRyal.ButtonCustom2.Text");
            txtPointOfRyal.ButtonDropDown.DisplayPosition = (int)resources.GetObject("txtPointOfRyal.ButtonDropDown.DisplayPosition");
            txtPointOfRyal.ButtonDropDown.Image = null;
            txtPointOfRyal.ButtonDropDown.Text = resources.GetString("txtPointOfRyal.ButtonDropDown.Text");
            txtPointOfRyal.ButtonFreeText.DisplayPosition = (int)resources.GetObject("txtPointOfRyal.ButtonFreeText.DisplayPosition");
            txtPointOfRyal.ButtonFreeText.Image = null;
            txtPointOfRyal.ButtonFreeText.Shortcut = DevComponents.DotNetBar.eShortcut.F2;
            txtPointOfRyal.ButtonFreeText.Text = resources.GetString("txtPointOfRyal.ButtonFreeText.Text");
            txtPointOfRyal.CommandParameter = null;
            txtPointOfRyal.DisplayFormat = "0.00";
            txtPointOfRyal.Increment = 0.0;
            txtPointOfRyal.InputHorizontalAlignment = DevComponents.Editors.eHorizontalAlignment.Center;
            txtPointOfRyal.MinValue = 0.0;
            txtPointOfRyal.Name = "txtPointOfRyal";
            txtPointOfRyal.Value = 0.01;
            label12.AccessibleDescription = null;
            label12.AccessibleName = null;
            resources.ApplyResources(label12, "label12");
            label12.BackColor = System.Drawing.Color.Transparent;
            label12.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            label12.ForeColor = System.Drawing.SystemColors.HotTrack;
            label12.Name = "label12";
            ButExit.AccessibleDescription = null;
            ButExit.AccessibleName = null;
            ButExit.AccessibleRole = System.Windows.Forms.AccessibleRole.PushButton;
            resources.ApplyResources(ButExit, "ButExit");
            ButExit.BackgroundImage = null;
            ButExit.Checked = true;
            ButExit.ColorTable = DevComponents.DotNetBar.eButtonColor.OrangeWithBackground;
            ButExit.CommandParameter = null;
            ButExit.Name = "ButExit";
            ButExit.Style = DevComponents.DotNetBar.eDotNetBarStyle.StyleManagerControlled;
            ButExit.Symbol = "\uf011";
            ButExit.SymbolSize = 16f;
            ButExit.TextColor = System.Drawing.Color.Black;
            ButExit.Click += new System.EventHandler(ButExit_Click);
            ButOk.AccessibleDescription = null;
            ButOk.AccessibleName = null;
            ButOk.AccessibleRole = System.Windows.Forms.AccessibleRole.PushButton;
            resources.ApplyResources(ButOk, "ButOk");
            ButOk.BackgroundImage = null;
            ButOk.ColorTable = DevComponents.DotNetBar.eButtonColor.BlueOrb;
            ButOk.CommandParameter = null;
            ButOk.Name = "ButOk";
            ButOk.Style = DevComponents.DotNetBar.eDotNetBarStyle.StyleManagerControlled;
            ButOk.Symbol = "\uf00c";
            ButOk.SymbolSize = 16f;
            ButOk.TextColor = System.Drawing.Color.White;
            ButOk.Click += new System.EventHandler(ButOk_Click);
            groupPanel5.AccessibleDescription = null;
            groupPanel5.AccessibleName = null;
            resources.ApplyResources(groupPanel5, "groupPanel5");
            groupPanel5.CanvasColor = System.Drawing.SystemColors.Control;
            groupPanel5.ColorSchemeStyle = DevComponents.DotNetBar.eDotNetBarStyle.Office2007;
            groupPanel5.ColorTable = DevComponents.DotNetBar.Controls.ePanelColorTable.Green;
            groupPanel5.Controls.Add(txtItem4E);
            groupPanel5.Controls.Add(txtItem3E);
            groupPanel5.Controls.Add(txtItem2E);
            groupPanel5.Controls.Add(txtItem1E);
            groupPanel5.Controls.Add(textBox1);
            groupPanel5.Controls.Add(textBox6);
            groupPanel5.Controls.Add(textBox7);
            groupPanel5.Controls.Add(textBox8);
            groupPanel5.Controls.Add(integerInput5);
            groupPanel5.Controls.Add(integerInput6);
            groupPanel5.Controls.Add(integerInput7);
            groupPanel5.Controls.Add(integerInput8);
            groupPanel5.Controls.Add(textBox5);
            groupPanel5.Controls.Add(textBox4);
            groupPanel5.Controls.Add(textBox3);
            groupPanel5.Controls.Add(textBox2);
            groupPanel5.Controls.Add(txtItem4);
            groupPanel5.Controls.Add(integerInput4);
            groupPanel5.Controls.Add(txtItem3);
            groupPanel5.Controls.Add(integerInput3);
            groupPanel5.Controls.Add(txtItem2);
            groupPanel5.Controls.Add(integerInput2);
            groupPanel5.Controls.Add(txtItem1);
            groupPanel5.Controls.Add(integerInput1);
            groupPanel5.Name = "groupPanel5";
            groupPanel5.Style.BackColor = System.Drawing.Color.FromArgb(195, 217, 185);
            groupPanel5.Style.BackColor2 = System.Drawing.Color.FromArgb(156, 191, 139);
            groupPanel5.Style.BackColorGradientAngle = 90;
            groupPanel5.Style.BorderBottom = DevComponents.DotNetBar.eStyleBorderType.Solid;
            groupPanel5.Style.BorderBottomWidth = 1;
            groupPanel5.Style.BorderColor = System.Drawing.Color.FromArgb(114, 164, 90);
            groupPanel5.Style.BorderLeft = DevComponents.DotNetBar.eStyleBorderType.Solid;
            groupPanel5.Style.BorderLeftWidth = 1;
            groupPanel5.Style.BorderRight = DevComponents.DotNetBar.eStyleBorderType.Solid;
            groupPanel5.Style.BorderRightWidth = 1;
            groupPanel5.Style.BorderTop = DevComponents.DotNetBar.eStyleBorderType.Solid;
            groupPanel5.Style.BorderTopWidth = 1;
            groupPanel5.Style.CornerDiameter = 4;
            groupPanel5.Style.CornerType = DevComponents.DotNetBar.eCornerType.Rounded;
            groupPanel5.Style.TextAlignment = DevComponents.DotNetBar.eStyleTextAlignment.Center;
            groupPanel5.Style.TextColor = System.Drawing.Color.FromArgb(60, 74, 31);
            groupPanel5.Style.TextLineAlignment = DevComponents.DotNetBar.eStyleTextAlignment.Near;
            groupPanel5.StyleMouseDown.CornerType = DevComponents.DotNetBar.eCornerType.Square;
            groupPanel5.StyleMouseOver.CornerType = DevComponents.DotNetBar.eCornerType.Square;
            groupPanel5.TitleImagePosition = DevComponents.DotNetBar.eTitleImagePosition.Center;
            txtItem4E.AccessibleDescription = null;
            txtItem4E.AccessibleName = null;
            resources.ApplyResources(txtItem4E, "txtItem4E");
            txtItem4E.BackgroundImage = null;
            txtItem4E.ForeColor = System.Drawing.Color.DodgerBlue;
            txtItem4E.Name = "txtItem4E";
            txtItem3E.AccessibleDescription = null;
            txtItem3E.AccessibleName = null;
            resources.ApplyResources(txtItem3E, "txtItem3E");
            txtItem3E.BackgroundImage = null;
            txtItem3E.ForeColor = System.Drawing.Color.DodgerBlue;
            txtItem3E.Name = "txtItem3E";
            txtItem2E.AccessibleDescription = null;
            txtItem2E.AccessibleName = null;
            resources.ApplyResources(txtItem2E, "txtItem2E");
            txtItem2E.BackgroundImage = null;
            txtItem2E.ForeColor = System.Drawing.Color.DodgerBlue;
            txtItem2E.Name = "txtItem2E";
            txtItem2E.Click += new System.EventHandler(txtItem2E_Click);
            txtItem1E.AccessibleDescription = null;
            txtItem1E.AccessibleName = null;
            resources.ApplyResources(txtItem1E, "txtItem1E");
            txtItem1E.BackgroundImage = null;
            txtItem1E.ForeColor = System.Drawing.Color.DodgerBlue;
            txtItem1E.Name = "txtItem1E";
            txtItem1E.Click += new System.EventHandler(txtItem1E_Click);
            textBox1.AccessibleDescription = null;
            textBox1.AccessibleName = null;
            resources.ApplyResources(textBox1, "textBox1");
            textBox1.BackgroundImage = null;
            textBox1.ForeColor = System.Drawing.Color.SlateGray;
            textBox1.Name = "textBox1";
            textBox6.AccessibleDescription = null;
            textBox6.AccessibleName = null;
            resources.ApplyResources(textBox6, "textBox6");
            textBox6.BackgroundImage = null;
            textBox6.ForeColor = System.Drawing.Color.SlateGray;
            textBox6.Name = "textBox6";
            textBox7.AccessibleDescription = null;
            textBox7.AccessibleName = null;
            resources.ApplyResources(textBox7, "textBox7");
            textBox7.BackgroundImage = null;
            textBox7.ForeColor = System.Drawing.Color.SlateGray;
            textBox7.Name = "textBox7";
            textBox8.AccessibleDescription = null;
            textBox8.AccessibleName = null;
            resources.ApplyResources(textBox8, "textBox8");
            textBox8.BackgroundImage = null;
            textBox8.ForeColor = System.Drawing.Color.SlateGray;
            textBox8.Name = "textBox8";
            integerInput5.AccessibleDescription = null;
            integerInput5.AccessibleName = null;
            integerInput5.AllowEmptyState = false;
            resources.ApplyResources(integerInput5, "integerInput5");
            integerInput5.BackgroundImage = null;
            integerInput5.BackgroundStyle.BackColor = System.Drawing.Color.FromArgb(255, 255, 255);
            integerInput5.BackgroundStyle.Class = "DateTimeInputBackground";
            integerInput5.BackgroundStyle.CornerType = DevComponents.DotNetBar.eCornerType.Square;
            integerInput5.ButtonCalculator.DisplayPosition = (int)resources.GetObject("integerInput5.ButtonCalculator.DisplayPosition");
            integerInput5.ButtonCalculator.Image = null;
            integerInput5.ButtonCalculator.Text = resources.GetString("integerInput5.ButtonCalculator.Text");
            integerInput5.ButtonClear.DisplayPosition = (int)resources.GetObject("integerInput5.ButtonClear.DisplayPosition");
            integerInput5.ButtonClear.Image = null;
            integerInput5.ButtonClear.Text = resources.GetString("integerInput5.ButtonClear.Text");
            integerInput5.ButtonCustom.DisplayPosition = (int)resources.GetObject("integerInput5.ButtonCustom.DisplayPosition");
            integerInput5.ButtonCustom.Image = null;
            integerInput5.ButtonCustom.Text = resources.GetString("integerInput5.ButtonCustom.Text");
            integerInput5.ButtonCustom2.DisplayPosition = (int)resources.GetObject("integerInput5.ButtonCustom2.DisplayPosition");
            integerInput5.ButtonCustom2.Image = null;
            integerInput5.ButtonCustom2.Text = resources.GetString("integerInput5.ButtonCustom2.Text");
            integerInput5.ButtonDropDown.DisplayPosition = (int)resources.GetObject("integerInput5.ButtonDropDown.DisplayPosition");
            integerInput5.ButtonDropDown.Image = null;
            integerInput5.ButtonDropDown.Text = resources.GetString("integerInput5.ButtonDropDown.Text");
            integerInput5.ButtonFreeText.DisplayPosition = (int)resources.GetObject("integerInput5.ButtonFreeText.DisplayPosition");
            integerInput5.ButtonFreeText.Image = null;
            integerInput5.ButtonFreeText.Shortcut = DevComponents.DotNetBar.eShortcut.F2;
            integerInput5.ButtonFreeText.Text = resources.GetString("integerInput5.ButtonFreeText.Text");
            integerInput5.CommandParameter = null;
            integerInput5.DisplayFormat = "0";
            integerInput5.InputHorizontalAlignment = DevComponents.Editors.eHorizontalAlignment.Center;
            integerInput5.IsInputReadOnly = true;
            integerInput5.MinValue = 0;
            integerInput5.Name = "integerInput5";
            integerInput5.Value = 4;
            integerInput6.AccessibleDescription = null;
            integerInput6.AccessibleName = null;
            integerInput6.AllowEmptyState = false;
            resources.ApplyResources(integerInput6, "integerInput6");
            integerInput6.BackgroundImage = null;
            integerInput6.BackgroundStyle.BackColor = System.Drawing.Color.FromArgb(255, 255, 255);
            integerInput6.BackgroundStyle.Class = "DateTimeInputBackground";
            integerInput6.BackgroundStyle.CornerType = DevComponents.DotNetBar.eCornerType.Square;
            integerInput6.ButtonCalculator.DisplayPosition = (int)resources.GetObject("integerInput6.ButtonCalculator.DisplayPosition");
            integerInput6.ButtonCalculator.Image = null;
            integerInput6.ButtonCalculator.Text = resources.GetString("integerInput6.ButtonCalculator.Text");
            integerInput6.ButtonClear.DisplayPosition = (int)resources.GetObject("integerInput6.ButtonClear.DisplayPosition");
            integerInput6.ButtonClear.Image = null;
            integerInput6.ButtonClear.Text = resources.GetString("integerInput6.ButtonClear.Text");
            integerInput6.ButtonCustom.DisplayPosition = (int)resources.GetObject("integerInput6.ButtonCustom.DisplayPosition");
            integerInput6.ButtonCustom.Image = null;
            integerInput6.ButtonCustom.Text = resources.GetString("integerInput6.ButtonCustom.Text");
            integerInput6.ButtonCustom2.DisplayPosition = (int)resources.GetObject("integerInput6.ButtonCustom2.DisplayPosition");
            integerInput6.ButtonCustom2.Image = null;
            integerInput6.ButtonCustom2.Text = resources.GetString("integerInput6.ButtonCustom2.Text");
            integerInput6.ButtonDropDown.DisplayPosition = (int)resources.GetObject("integerInput6.ButtonDropDown.DisplayPosition");
            integerInput6.ButtonDropDown.Image = null;
            integerInput6.ButtonDropDown.Text = resources.GetString("integerInput6.ButtonDropDown.Text");
            integerInput6.ButtonFreeText.DisplayPosition = (int)resources.GetObject("integerInput6.ButtonFreeText.DisplayPosition");
            integerInput6.ButtonFreeText.Image = null;
            integerInput6.ButtonFreeText.Shortcut = DevComponents.DotNetBar.eShortcut.F2;
            integerInput6.ButtonFreeText.Text = resources.GetString("integerInput6.ButtonFreeText.Text");
            integerInput6.CommandParameter = null;
            integerInput6.DisplayFormat = "0";
            integerInput6.InputHorizontalAlignment = DevComponents.Editors.eHorizontalAlignment.Center;
            integerInput6.IsInputReadOnly = true;
            integerInput6.MinValue = 0;
            integerInput6.Name = "integerInput6";
            integerInput6.Value = 3;
            integerInput7.AccessibleDescription = null;
            integerInput7.AccessibleName = null;
            integerInput7.AllowEmptyState = false;
            resources.ApplyResources(integerInput7, "integerInput7");
            integerInput7.BackgroundImage = null;
            integerInput7.BackgroundStyle.BackColor = System.Drawing.Color.FromArgb(255, 255, 255);
            integerInput7.BackgroundStyle.Class = "DateTimeInputBackground";
            integerInput7.BackgroundStyle.CornerType = DevComponents.DotNetBar.eCornerType.Square;
            integerInput7.ButtonCalculator.DisplayPosition = (int)resources.GetObject("integerInput7.ButtonCalculator.DisplayPosition");
            integerInput7.ButtonCalculator.Image = null;
            integerInput7.ButtonCalculator.Text = resources.GetString("integerInput7.ButtonCalculator.Text");
            integerInput7.ButtonClear.DisplayPosition = (int)resources.GetObject("integerInput7.ButtonClear.DisplayPosition");
            integerInput7.ButtonClear.Image = null;
            integerInput7.ButtonClear.Text = resources.GetString("integerInput7.ButtonClear.Text");
            integerInput7.ButtonCustom.DisplayPosition = (int)resources.GetObject("integerInput7.ButtonCustom.DisplayPosition");
            integerInput7.ButtonCustom.Image = null;
            integerInput7.ButtonCustom.Text = resources.GetString("integerInput7.ButtonCustom.Text");
            integerInput7.ButtonCustom2.DisplayPosition = (int)resources.GetObject("integerInput7.ButtonCustom2.DisplayPosition");
            integerInput7.ButtonCustom2.Image = null;
            integerInput7.ButtonCustom2.Text = resources.GetString("integerInput7.ButtonCustom2.Text");
            integerInput7.ButtonDropDown.DisplayPosition = (int)resources.GetObject("integerInput7.ButtonDropDown.DisplayPosition");
            integerInput7.ButtonDropDown.Image = null;
            integerInput7.ButtonDropDown.Text = resources.GetString("integerInput7.ButtonDropDown.Text");
            integerInput7.ButtonFreeText.DisplayPosition = (int)resources.GetObject("integerInput7.ButtonFreeText.DisplayPosition");
            integerInput7.ButtonFreeText.Image = null;
            integerInput7.ButtonFreeText.Shortcut = DevComponents.DotNetBar.eShortcut.F2;
            integerInput7.ButtonFreeText.Text = resources.GetString("integerInput7.ButtonFreeText.Text");
            integerInput7.CommandParameter = null;
            integerInput7.DisplayFormat = "0";
            integerInput7.InputHorizontalAlignment = DevComponents.Editors.eHorizontalAlignment.Center;
            integerInput7.IsInputReadOnly = true;
            integerInput7.MinValue = 0;
            integerInput7.Name = "integerInput7";
            integerInput7.Value = 2;
            integerInput8.AccessibleDescription = null;
            integerInput8.AccessibleName = null;
            integerInput8.AllowEmptyState = false;
            resources.ApplyResources(integerInput8, "integerInput8");
            integerInput8.BackgroundImage = null;
            integerInput8.BackgroundStyle.BackColor = System.Drawing.Color.FromArgb(255, 255, 255);
            integerInput8.BackgroundStyle.Class = "DateTimeInputBackground";
            integerInput8.BackgroundStyle.CornerType = DevComponents.DotNetBar.eCornerType.Square;
            integerInput8.ButtonCalculator.DisplayPosition = (int)resources.GetObject("integerInput8.ButtonCalculator.DisplayPosition");
            integerInput8.ButtonCalculator.Image = null;
            integerInput8.ButtonCalculator.Text = resources.GetString("integerInput8.ButtonCalculator.Text");
            integerInput8.ButtonClear.DisplayPosition = (int)resources.GetObject("integerInput8.ButtonClear.DisplayPosition");
            integerInput8.ButtonClear.Image = null;
            integerInput8.ButtonClear.Text = resources.GetString("integerInput8.ButtonClear.Text");
            integerInput8.ButtonCustom.DisplayPosition = (int)resources.GetObject("integerInput8.ButtonCustom.DisplayPosition");
            integerInput8.ButtonCustom.Image = null;
            integerInput8.ButtonCustom.Text = resources.GetString("integerInput8.ButtonCustom.Text");
            integerInput8.ButtonCustom2.DisplayPosition = (int)resources.GetObject("integerInput8.ButtonCustom2.DisplayPosition");
            integerInput8.ButtonCustom2.Image = null;
            integerInput8.ButtonCustom2.Text = resources.GetString("integerInput8.ButtonCustom2.Text");
            integerInput8.ButtonDropDown.DisplayPosition = (int)resources.GetObject("integerInput8.ButtonDropDown.DisplayPosition");
            integerInput8.ButtonDropDown.Image = null;
            integerInput8.ButtonDropDown.Text = resources.GetString("integerInput8.ButtonDropDown.Text");
            integerInput8.ButtonFreeText.DisplayPosition = (int)resources.GetObject("integerInput8.ButtonFreeText.DisplayPosition");
            integerInput8.ButtonFreeText.Image = null;
            integerInput8.ButtonFreeText.Shortcut = DevComponents.DotNetBar.eShortcut.F2;
            integerInput8.ButtonFreeText.Text = resources.GetString("integerInput8.ButtonFreeText.Text");
            integerInput8.CommandParameter = null;
            integerInput8.DisplayFormat = "0";
            integerInput8.InputHorizontalAlignment = DevComponents.Editors.eHorizontalAlignment.Center;
            integerInput8.IsInputReadOnly = true;
            integerInput8.MinValue = 0;
            integerInput8.Name = "integerInput8";
            integerInput8.Value = 1;
            textBox5.AccessibleDescription = null;
            textBox5.AccessibleName = null;
            resources.ApplyResources(textBox5, "textBox5");
            textBox5.BackgroundImage = null;
            textBox5.ForeColor = System.Drawing.Color.SlateGray;
            textBox5.Name = "textBox5";
            textBox4.AccessibleDescription = null;
            textBox4.AccessibleName = null;
            resources.ApplyResources(textBox4, "textBox4");
            textBox4.BackgroundImage = null;
            textBox4.ForeColor = System.Drawing.Color.SlateGray;
            textBox4.Name = "textBox4";
            textBox3.AccessibleDescription = null;
            textBox3.AccessibleName = null;
            resources.ApplyResources(textBox3, "textBox3");
            textBox3.BackgroundImage = null;
            textBox3.ForeColor = System.Drawing.Color.SlateGray;
            textBox3.Name = "textBox3";
            textBox2.AccessibleDescription = null;
            textBox2.AccessibleName = null;
            resources.ApplyResources(textBox2, "textBox2");
            textBox2.BackgroundImage = null;
            textBox2.ForeColor = System.Drawing.Color.SlateGray;
            textBox2.Name = "textBox2";
            txtItem4.AccessibleDescription = null;
            txtItem4.AccessibleName = null;
            resources.ApplyResources(txtItem4, "txtItem4");
            txtItem4.BackgroundImage = null;
            txtItem4.ForeColor = System.Drawing.Color.DodgerBlue;
            txtItem4.Name = "txtItem4";
            integerInput4.AccessibleDescription = null;
            integerInput4.AccessibleName = null;
            integerInput4.AllowEmptyState = false;
            resources.ApplyResources(integerInput4, "integerInput4");
            integerInput4.BackgroundImage = null;
            integerInput4.BackgroundStyle.BackColor = System.Drawing.Color.FromArgb(255, 255, 255);
            integerInput4.BackgroundStyle.Class = "DateTimeInputBackground";
            integerInput4.BackgroundStyle.CornerType = DevComponents.DotNetBar.eCornerType.Square;
            integerInput4.ButtonCalculator.DisplayPosition = (int)resources.GetObject("integerInput4.ButtonCalculator.DisplayPosition");
            integerInput4.ButtonCalculator.Image = null;
            integerInput4.ButtonCalculator.Text = resources.GetString("integerInput4.ButtonCalculator.Text");
            integerInput4.ButtonClear.DisplayPosition = (int)resources.GetObject("integerInput4.ButtonClear.DisplayPosition");
            integerInput4.ButtonClear.Image = null;
            integerInput4.ButtonClear.Text = resources.GetString("integerInput4.ButtonClear.Text");
            integerInput4.ButtonCustom.DisplayPosition = (int)resources.GetObject("integerInput4.ButtonCustom.DisplayPosition");
            integerInput4.ButtonCustom.Image = null;
            integerInput4.ButtonCustom.Text = resources.GetString("integerInput4.ButtonCustom.Text");
            integerInput4.ButtonCustom2.DisplayPosition = (int)resources.GetObject("integerInput4.ButtonCustom2.DisplayPosition");
            integerInput4.ButtonCustom2.Image = null;
            integerInput4.ButtonCustom2.Text = resources.GetString("integerInput4.ButtonCustom2.Text");
            integerInput4.ButtonDropDown.DisplayPosition = (int)resources.GetObject("integerInput4.ButtonDropDown.DisplayPosition");
            integerInput4.ButtonDropDown.Image = null;
            integerInput4.ButtonDropDown.Text = resources.GetString("integerInput4.ButtonDropDown.Text");
            integerInput4.ButtonFreeText.DisplayPosition = (int)resources.GetObject("integerInput4.ButtonFreeText.DisplayPosition");
            integerInput4.ButtonFreeText.Image = null;
            integerInput4.ButtonFreeText.Shortcut = DevComponents.DotNetBar.eShortcut.F2;
            integerInput4.ButtonFreeText.Text = resources.GetString("integerInput4.ButtonFreeText.Text");
            integerInput4.CommandParameter = null;
            integerInput4.DisplayFormat = "0";
            integerInput4.InputHorizontalAlignment = DevComponents.Editors.eHorizontalAlignment.Center;
            integerInput4.IsInputReadOnly = true;
            integerInput4.MinValue = 0;
            integerInput4.Name = "integerInput4";
            integerInput4.Value = 4;
            txtItem3.AccessibleDescription = null;
            txtItem3.AccessibleName = null;
            resources.ApplyResources(txtItem3, "txtItem3");
            txtItem3.BackgroundImage = null;
            txtItem3.ForeColor = System.Drawing.Color.DodgerBlue;
            txtItem3.Name = "txtItem3";
            integerInput3.AccessibleDescription = null;
            integerInput3.AccessibleName = null;
            integerInput3.AllowEmptyState = false;
            resources.ApplyResources(integerInput3, "integerInput3");
            integerInput3.BackgroundImage = null;
            integerInput3.BackgroundStyle.BackColor = System.Drawing.Color.FromArgb(255, 255, 255);
            integerInput3.BackgroundStyle.Class = "DateTimeInputBackground";
            integerInput3.BackgroundStyle.CornerType = DevComponents.DotNetBar.eCornerType.Square;
            integerInput3.ButtonCalculator.DisplayPosition = (int)resources.GetObject("integerInput3.ButtonCalculator.DisplayPosition");
            integerInput3.ButtonCalculator.Image = null;
            integerInput3.ButtonCalculator.Text = resources.GetString("integerInput3.ButtonCalculator.Text");
            integerInput3.ButtonClear.DisplayPosition = (int)resources.GetObject("integerInput3.ButtonClear.DisplayPosition");
            integerInput3.ButtonClear.Image = null;
            integerInput3.ButtonClear.Text = resources.GetString("integerInput3.ButtonClear.Text");
            integerInput3.ButtonCustom.DisplayPosition = (int)resources.GetObject("integerInput3.ButtonCustom.DisplayPosition");
            integerInput3.ButtonCustom.Image = null;
            integerInput3.ButtonCustom.Text = resources.GetString("integerInput3.ButtonCustom.Text");
            integerInput3.ButtonCustom2.DisplayPosition = (int)resources.GetObject("integerInput3.ButtonCustom2.DisplayPosition");
            integerInput3.ButtonCustom2.Image = null;
            integerInput3.ButtonCustom2.Text = resources.GetString("integerInput3.ButtonCustom2.Text");
            integerInput3.ButtonDropDown.DisplayPosition = (int)resources.GetObject("integerInput3.ButtonDropDown.DisplayPosition");
            integerInput3.ButtonDropDown.Image = null;
            integerInput3.ButtonDropDown.Text = resources.GetString("integerInput3.ButtonDropDown.Text");
            integerInput3.ButtonFreeText.DisplayPosition = (int)resources.GetObject("integerInput3.ButtonFreeText.DisplayPosition");
            integerInput3.ButtonFreeText.Image = null;
            integerInput3.ButtonFreeText.Shortcut = DevComponents.DotNetBar.eShortcut.F2;
            integerInput3.ButtonFreeText.Text = resources.GetString("integerInput3.ButtonFreeText.Text");
            integerInput3.CommandParameter = null;
            integerInput3.DisplayFormat = "0";
            integerInput3.InputHorizontalAlignment = DevComponents.Editors.eHorizontalAlignment.Center;
            integerInput3.IsInputReadOnly = true;
            integerInput3.MinValue = 0;
            integerInput3.Name = "integerInput3";
            integerInput3.Value = 3;
            txtItem2.AccessibleDescription = null;
            txtItem2.AccessibleName = null;
            resources.ApplyResources(txtItem2, "txtItem2");
            txtItem2.BackgroundImage = null;
            txtItem2.ForeColor = System.Drawing.Color.DodgerBlue;
            txtItem2.Name = "txtItem2";
            txtItem2.Click += new System.EventHandler(txtItem2_Click);
            integerInput2.AccessibleDescription = null;
            integerInput2.AccessibleName = null;
            integerInput2.AllowEmptyState = false;
            resources.ApplyResources(integerInput2, "integerInput2");
            integerInput2.BackgroundImage = null;
            integerInput2.BackgroundStyle.BackColor = System.Drawing.Color.FromArgb(255, 255, 255);
            integerInput2.BackgroundStyle.Class = "DateTimeInputBackground";
            integerInput2.BackgroundStyle.CornerType = DevComponents.DotNetBar.eCornerType.Square;
            integerInput2.ButtonCalculator.DisplayPosition = (int)resources.GetObject("integerInput2.ButtonCalculator.DisplayPosition");
            integerInput2.ButtonCalculator.Image = null;
            integerInput2.ButtonCalculator.Text = resources.GetString("integerInput2.ButtonCalculator.Text");
            integerInput2.ButtonClear.DisplayPosition = (int)resources.GetObject("integerInput2.ButtonClear.DisplayPosition");
            integerInput2.ButtonClear.Image = null;
            integerInput2.ButtonClear.Text = resources.GetString("integerInput2.ButtonClear.Text");
            integerInput2.ButtonCustom.DisplayPosition = (int)resources.GetObject("integerInput2.ButtonCustom.DisplayPosition");
            integerInput2.ButtonCustom.Image = null;
            integerInput2.ButtonCustom.Text = resources.GetString("integerInput2.ButtonCustom.Text");
            integerInput2.ButtonCustom2.DisplayPosition = (int)resources.GetObject("integerInput2.ButtonCustom2.DisplayPosition");
            integerInput2.ButtonCustom2.Image = null;
            integerInput2.ButtonCustom2.Text = resources.GetString("integerInput2.ButtonCustom2.Text");
            integerInput2.ButtonDropDown.DisplayPosition = (int)resources.GetObject("integerInput2.ButtonDropDown.DisplayPosition");
            integerInput2.ButtonDropDown.Image = null;
            integerInput2.ButtonDropDown.Text = resources.GetString("integerInput2.ButtonDropDown.Text");
            integerInput2.ButtonFreeText.DisplayPosition = (int)resources.GetObject("integerInput2.ButtonFreeText.DisplayPosition");
            integerInput2.ButtonFreeText.Image = null;
            integerInput2.ButtonFreeText.Shortcut = DevComponents.DotNetBar.eShortcut.F2;
            integerInput2.ButtonFreeText.Text = resources.GetString("integerInput2.ButtonFreeText.Text");
            integerInput2.CommandParameter = null;
            integerInput2.DisplayFormat = "0";
            integerInput2.InputHorizontalAlignment = DevComponents.Editors.eHorizontalAlignment.Center;
            integerInput2.IsInputReadOnly = true;
            integerInput2.MinValue = 0;
            integerInput2.Name = "integerInput2";
            integerInput2.Value = 2;
            txtItem1.AccessibleDescription = null;
            txtItem1.AccessibleName = null;
            resources.ApplyResources(txtItem1, "txtItem1");
            txtItem1.BackgroundImage = null;
            txtItem1.ForeColor = System.Drawing.Color.DodgerBlue;
            txtItem1.Name = "txtItem1";
            txtItem1.Click += new System.EventHandler(txtItem1_Click);
            integerInput1.AccessibleDescription = null;
            integerInput1.AccessibleName = null;
            integerInput1.AllowEmptyState = false;
            resources.ApplyResources(integerInput1, "integerInput1");
            integerInput1.BackgroundImage = null;
            integerInput1.BackgroundStyle.BackColor = System.Drawing.Color.FromArgb(255, 255, 255);
            integerInput1.BackgroundStyle.Class = "DateTimeInputBackground";
            integerInput1.BackgroundStyle.CornerType = DevComponents.DotNetBar.eCornerType.Square;
            integerInput1.ButtonCalculator.DisplayPosition = (int)resources.GetObject("integerInput1.ButtonCalculator.DisplayPosition");
            integerInput1.ButtonCalculator.Image = null;
            integerInput1.ButtonCalculator.Text = resources.GetString("integerInput1.ButtonCalculator.Text");
            integerInput1.ButtonClear.DisplayPosition = (int)resources.GetObject("integerInput1.ButtonClear.DisplayPosition");
            integerInput1.ButtonClear.Image = null;
            integerInput1.ButtonClear.Text = resources.GetString("integerInput1.ButtonClear.Text");
            integerInput1.ButtonCustom.DisplayPosition = (int)resources.GetObject("integerInput1.ButtonCustom.DisplayPosition");
            integerInput1.ButtonCustom.Image = null;
            integerInput1.ButtonCustom.Text = resources.GetString("integerInput1.ButtonCustom.Text");
            integerInput1.ButtonCustom2.DisplayPosition = (int)resources.GetObject("integerInput1.ButtonCustom2.DisplayPosition");
            integerInput1.ButtonCustom2.Image = null;
            integerInput1.ButtonCustom2.Text = resources.GetString("integerInput1.ButtonCustom2.Text");
            integerInput1.ButtonDropDown.DisplayPosition = (int)resources.GetObject("integerInput1.ButtonDropDown.DisplayPosition");
            integerInput1.ButtonDropDown.Image = null;
            integerInput1.ButtonDropDown.Text = resources.GetString("integerInput1.ButtonDropDown.Text");
            integerInput1.ButtonFreeText.DisplayPosition = (int)resources.GetObject("integerInput1.ButtonFreeText.DisplayPosition");
            integerInput1.ButtonFreeText.Image = null;
            integerInput1.ButtonFreeText.Shortcut = DevComponents.DotNetBar.eShortcut.F2;
            integerInput1.ButtonFreeText.Text = resources.GetString("integerInput1.ButtonFreeText.Text");
            integerInput1.CommandParameter = null;
            integerInput1.DisplayFormat = "0";
            integerInput1.InputHorizontalAlignment = DevComponents.Editors.eHorizontalAlignment.Center;
            integerInput1.IsInputReadOnly = true;
            integerInput1.MinValue = 0;
            integerInput1.Name = "integerInput1";
            integerInput1.Value = 1;
            base.AccessibleDescription = null;
            base.AccessibleName = null;
            resources.ApplyResources(this, "$this");
            base.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            BackColor = System.Drawing.SystemColors.GradientInactiveCaption;
            BackgroundImage = null;
            base.Controls.Add(groupPanel5);
            base.Controls.Add(ButExit);
            base.Controls.Add(ButOk);
            base.Controls.Add(groupPanel4);
            base.Controls.Add(groupPanel1);
            Font = null;
            base.FormBorderStyle = System.Windows.Forms.FormBorderStyle.Fixed3D;
            base.KeyPreview = true;
            base.MaximizeBox = false;
            base.Name = "FrmPointsCalc";
            base.Load += new System.EventHandler(FrmPointsCalc_Load);
            base.KeyPress += new System.Windows.Forms.KeyPressEventHandler(Frm_KeyPress);
            base.KeyDown += new System.Windows.Forms.KeyEventHandler(Frm_KeyDown);
            groupPanel1.ResumeLayout(false);
            groupPanel1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)txtTotalPoint).EndInit();
            ((System.ComponentModel.ISupportInitialize)txtTotalPurchaes).EndInit();
            groupPanel4.ResumeLayout(false);
            groupPanel4.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)txtPointOfRyal).EndInit();
            groupPanel5.ResumeLayout(false);
            groupPanel5.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)integerInput5).EndInit();
            ((System.ComponentModel.ISupportInitialize)integerInput6).EndInit();
            ((System.ComponentModel.ISupportInitialize)integerInput7).EndInit();
            ((System.ComponentModel.ISupportInitialize)integerInput8).EndInit();
            ((System.ComponentModel.ISupportInitialize)integerInput4).EndInit();
            ((System.ComponentModel.ISupportInitialize)integerInput3).EndInit();
            ((System.ComponentModel.ISupportInitialize)integerInput2).EndInit();
            ((System.ComponentModel.ISupportInitialize)integerInput1).EndInit();
            ResumeLayout(false);
        }//###########&&&&&&&&&&

}
}
