#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace InvAcc.Stock_Data
{
    using System.Data.Linq;
    using System.Data.Linq.Mapping;
    using System.Data;
    using System.Collections.Generic;
    using System.Reflection;
    using System.Linq;
    using System.Linq.Expressions;
    using System.ComponentModel;
    using System;


    [global::System.Data.Linq.Mapping.DatabaseAttribute(Name = "DBPROSOFT_default")]
    public class Rate_DataDataContext : DataContext
    {
        private static MappingSource mappingSource = (MappingSource)new AttributeMappingSource();
        public Rate_DataDataContext()
          : base(InvAcc.Properties.Settings.Default.DBPROSOFT_defaultConnectionString, Rate_DataDataContext.mappingSource)
        {
        }
        public Rate_DataDataContext(string connection)
          : base(connection, Rate_DataDataContext.mappingSource)
        {
        }
        public Rate_DataDataContext(IDbConnection connection)
          : base(connection, Rate_DataDataContext.mappingSource)
        {
        }
        public Rate_DataDataContext(string connection, MappingSource mappingSource)
          : base(connection, mappingSource)
        {
        }
        public Rate_DataDataContext(IDbConnection connection, MappingSource mappingSource)
          : base(connection, mappingSource)
        {
        }
        public Table<T_Branch> T_Branches => this.GetTable<T_Branch>();
        public Table<T_User> T_Users => this.GetTable<T_User>();
        public T_Branch RateBranch(string no)
        {
            T_Branch tBranch = new T_Branch();
            IOrderedQueryable<T_Branch> source = this.T_Branches.Where<T_Branch>((Expression<Func<T_Branch, bool>>)(er => er.Branch_no == no)).OrderBy<T_Branch, string>((Expression<Func<T_Branch, string>>)(er => er.Branch_no));
            if (source.Count<T_Branch>() > 0)
                tBranch = source.First<T_Branch>();
            return tBranch;
        }
        public T_Branch RateBranchID(int no)
        {
            T_Branch tBranch = new T_Branch();
            IOrderedQueryable<T_Branch> source = this.T_Branches.Where<T_Branch>((Expression<Func<T_Branch, bool>>)(er => er.Branch_ID == no)).OrderBy<T_Branch, string>((Expression<Func<T_Branch, string>>)(er => er.Branch_no));
            if (source.Count<T_Branch>() > 0)
                tBranch = source.First<T_Branch>();
            return tBranch;
        }
        public IQueryable<T_Branch> FillBranch_2(string key)
        {
            if (key == "")
                return (IQueryable<T_Branch>)this.T_Branches.OrderBy<T_Branch, int>((Expression<Func<T_Branch, int>>)(br => br.Branch_ID));
            return (IQueryable<T_Branch>)this.T_Branches.Where<T_Branch>((Expression<Func<T_Branch, bool>>)(br => br.Branch_no.ToString().StartsWith(key) || br.Branch_Name.Contains(key) || br.Branch_NameE.Contains(key) || br.Branch_phone.ToString().StartsWith(key) || br.Branch_fax.StartsWith(key) || br.dfNo.StartsWith(key) || br.crNo.StartsWith(key) || br.BldNo.StartsWith(key))).OrderBy<T_Branch, string>((Expression<Func<T_Branch, string>>)(br => br.Branch_no));
        }
        public int MaxBranchNo
        {
            get
            {
                int num = 1;
                try
                {
                    num = this.T_Branches.Max<T_Branch, int>((Expression<Func<T_Branch, int>>)(lgl => Convert.ToInt32(lgl.Branch_no))) + 1;
                }
                catch
                {
                }
                return num;
            }
        }
        public T_User SelectBrnchNoByReturnNo(string ReturnNo)
        {
            T_User tUser = new T_User();
            IQueryable<T_User> source = this.T_Users.Where<T_User>((Expression<Func<T_User, bool>>)(br => br.Brn == ReturnNo));
            return source.Count<T_User>() <= 0 ? (T_User)null : source.First<T_User>();
        }
        public T_User RateUsr(string no)
        {
            T_User tUser = new T_User();
            IOrderedQueryable<T_User> source = this.T_Users.Where<T_User>((Expression<Func<T_User, bool>>)(er => er.UsrNo == no)).OrderBy<T_User, string>((Expression<Func<T_User, string>>)(er => er.UsrNo));
            if (source.Count<T_User>() > 0)
                tUser = source.First<T_User>();
            return tUser;
        }
        public T_User Get_PermissionID(int no)
        {
            T_User tUser = new T_User();
            IOrderedQueryable<T_User> source = this.T_Users.Where<T_User>((Expression<Func<T_User, bool>>)(er => er.Usr_ID == no)).OrderBy<T_User, string>((Expression<Func<T_User, string>>)(er => er.UsrNo));
            if (source.Count<T_User>() > 0)
                tUser = source.First<T_User>();
            return tUser;
        }
        public T_User StockUser(string no)
        {
            T_User tUser = new T_User();
            IQueryable<T_User> source = this.T_Users.Where<T_User>((Expression<Func<T_User, bool>>)(br => br.UsrNo == no));
            return source.Count<T_User>() <= 0 ? (T_User)null : source.First<T_User>();
        }
        public int MaxUsrNo
        {
            get
            {
                int num = 1;
                try
                {
                    num = this.T_Users.Max<T_User, int>((Expression<Func<T_User, int>>)(lgl => Convert.ToInt32(lgl.UsrNo))) + 1;
                }
                catch
                {
                }
                return num;
            }
        }
        public IQueryable<T_User> FillUsr_2(string key)
        {
            if (key == "")
                return (IQueryable<T_User>)this.T_Users.Where<T_User>((Expression<Func<T_User, bool>>)(br => br.Usr_ID != 1 || br.UsrNo != "1")).OrderBy<T_User, string>((Expression<Func<T_User, string>>)(br => br.UsrNo));
            return (IQueryable<T_User>)this.T_Users.Where<T_User>((Expression<Func<T_User, bool>>)(br => br.UsrNo.ToString().StartsWith(key) || br.UsrNamA.Contains(key) || br.UsrNamE.Contains(key))).OrderBy<T_User, string>((Expression<Func<T_User, string>>)(br => br.UsrNo));
        }
    }
    [global::System.Data.Linq.Mapping.TableAttribute(Name = "dbo.T_Branch")]
    public partial class T_Branch : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);

        private int _Branch_ID;

        private string _Branch_no;

        private string _Branch_Name;

        private string _Branch_NameE;

        private string _Branch_address;

        private string _Branch_city;

        private string _Branch_phone;

        private string _Branch_fax;

        private string _Branch_mem;

        private System.Nullable<int> _REP_FLG;

        private string _StartEg;

        private string _EndEg;

        private string _crNo;

        private string _crIssu;

        private string _crExp;

        private string _BldNo;

        private string _BldIssu;

        private string _BldExp;

        private string _dfNo;

        private string _dfIssu;

        private string _dfExp;

        private EntitySet<T_User> _T_Users;

        #region Extensibility Method Definitions
        partial void OnLoaded();
        partial void OnValidate(System.Data.Linq.ChangeAction action);
        partial void OnCreated();
        partial void OnBranch_IDChanging(int value);
        partial void OnBranch_IDChanged();
        partial void OnBranch_noChanging(string value);
        partial void OnBranch_noChanged();
        partial void OnBranch_NameChanging(string value);
        partial void OnBranch_NameChanged();
        partial void OnBranch_NameEChanging(string value);
        partial void OnBranch_NameEChanged();
        partial void OnBranch_addressChanging(string value);
        partial void OnBranch_addressChanged();
        partial void OnBranch_cityChanging(string value);
        partial void OnBranch_cityChanged();
        partial void OnBranch_phoneChanging(string value);
        partial void OnBranch_phoneChanged();
        partial void OnBranch_faxChanging(string value);
        partial void OnBranch_faxChanged();
        partial void OnBranch_memChanging(string value);
        partial void OnBranch_memChanged();
        partial void OnREP_FLGChanging(System.Nullable<int> value);
        partial void OnREP_FLGChanged();
        partial void OnStartEgChanging(string value);
        partial void OnStartEgChanged();
        partial void OnEndEgChanging(string value);
        partial void OnEndEgChanged();
        partial void OncrNoChanging(string value);
        partial void OncrNoChanged();
        partial void OncrIssuChanging(string value);
        partial void OncrIssuChanged();
        partial void OncrExpChanging(string value);
        partial void OncrExpChanged();
        partial void OnBldNoChanging(string value);
        partial void OnBldNoChanged();
        partial void OnBldIssuChanging(string value);
        partial void OnBldIssuChanged();
        partial void OnBldExpChanging(string value);
        partial void OnBldExpChanged();
        partial void OndfNoChanging(string value);
        partial void OndfNoChanged();
        partial void OndfIssuChanging(string value);
        partial void OndfIssuChanged();
        partial void OndfExpChanging(string value);
        partial void OndfExpChanged();
        #endregion

        public T_Branch()
        {
            this._T_Users = new EntitySet<T_User>(new Action<T_User>(this.attach_T_Users), new Action<T_User>(this.detach_T_Users));
            OnCreated();
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Branch_ID", AutoSync = AutoSync.Always, DbType = "Int NOT NULL IDENTITY", IsDbGenerated = true)]
        public int Branch_ID
        {
            get
            {
                return this._Branch_ID;
            }
            set
            {
                if ((this._Branch_ID != value))
                {
                    this.OnBranch_IDChanging(value);
                    this.SendPropertyChanging();
                    this._Branch_ID = value;
                    this.SendPropertyChanged("Branch_ID");
                    this.OnBranch_IDChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Branch_no", DbType = "VarChar(50) NOT NULL", CanBeNull = false, IsPrimaryKey = true)]
        public string Branch_no
        {
            get
            {
                return this._Branch_no;
            }
            set
            {
                if ((this._Branch_no != value))
                {
                    this.OnBranch_noChanging(value);
                    this.SendPropertyChanging();
                    this._Branch_no = value;
                    this.SendPropertyChanged("Branch_no");
                    this.OnBranch_noChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Branch_Name", DbType = "VarChar(50)")]
        public string Branch_Name
        {
            get
            {
                return this._Branch_Name;
            }
            set
            {
                if ((this._Branch_Name != value))
                {
                    this.OnBranch_NameChanging(value);
                    this.SendPropertyChanging();
                    this._Branch_Name = value;
                    this.SendPropertyChanged("Branch_Name");
                    this.OnBranch_NameChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Branch_NameE", DbType = "VarChar(50)")]
        public string Branch_NameE
        {
            get
            {
                return this._Branch_NameE;
            }
            set
            {
                if ((this._Branch_NameE != value))
                {
                    this.OnBranch_NameEChanging(value);
                    this.SendPropertyChanging();
                    this._Branch_NameE = value;
                    this.SendPropertyChanged("Branch_NameE");
                    this.OnBranch_NameEChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Branch_address", DbType = "VarChar(50)")]
        public string Branch_address
        {
            get
            {
                return this._Branch_address;
            }
            set
            {
                if ((this._Branch_address != value))
                {
                    this.OnBranch_addressChanging(value);
                    this.SendPropertyChanging();
                    this._Branch_address = value;
                    this.SendPropertyChanged("Branch_address");
                    this.OnBranch_addressChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Branch_city", DbType = "VarChar(50)")]
        public string Branch_city
        {
            get
            {
                return this._Branch_city;
            }
            set
            {
                if ((this._Branch_city != value))
                {
                    this.OnBranch_cityChanging(value);
                    this.SendPropertyChanging();
                    this._Branch_city = value;
                    this.SendPropertyChanged("Branch_city");
                    this.OnBranch_cityChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Branch_phone", DbType = "VarChar(50)")]
        public string Branch_phone
        {
            get
            {
                return this._Branch_phone;
            }
            set
            {
                if ((this._Branch_phone != value))
                {
                    this.OnBranch_phoneChanging(value);
                    this.SendPropertyChanging();
                    this._Branch_phone = value;
                    this.SendPropertyChanged("Branch_phone");
                    this.OnBranch_phoneChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Branch_fax", DbType = "VarChar(50)")]
        public string Branch_fax
        {
            get
            {
                return this._Branch_fax;
            }
            set
            {
                if ((this._Branch_fax != value))
                {
                    this.OnBranch_faxChanging(value);
                    this.SendPropertyChanging();
                    this._Branch_fax = value;
                    this.SendPropertyChanged("Branch_fax");
                    this.OnBranch_faxChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Branch_mem", DbType = "VarChar(MAX)")]
        public string Branch_mem
        {
            get
            {
                return this._Branch_mem;
            }
            set
            {
                if ((this._Branch_mem != value))
                {
                    this.OnBranch_memChanging(value);
                    this.SendPropertyChanging();
                    this._Branch_mem = value;
                    this.SendPropertyChanged("Branch_mem");
                    this.OnBranch_memChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_REP_FLG", DbType = "Int")]
        public System.Nullable<int> REP_FLG
        {
            get
            {
                return this._REP_FLG;
            }
            set
            {
                if ((this._REP_FLG != value))
                {
                    this.OnREP_FLGChanging(value);
                    this.SendPropertyChanging();
                    this._REP_FLG = value;
                    this.SendPropertyChanged("REP_FLG");
                    this.OnREP_FLGChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_StartEg", DbType = "VarChar(30)")]
        public string StartEg
        {
            get
            {
                return this._StartEg;
            }
            set
            {
                if ((this._StartEg != value))
                {
                    this.OnStartEgChanging(value);
                    this.SendPropertyChanging();
                    this._StartEg = value;
                    this.SendPropertyChanged("StartEg");
                    this.OnStartEgChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_EndEg", DbType = "VarChar(30)")]
        public string EndEg
        {
            get
            {
                return this._EndEg;
            }
            set
            {
                if ((this._EndEg != value))
                {
                    this.OnEndEgChanging(value);
                    this.SendPropertyChanging();
                    this._EndEg = value;
                    this.SendPropertyChanged("EndEg");
                    this.OnEndEgChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_crNo", DbType = "VarChar(50)")]
        public string crNo
        {
            get
            {
                return this._crNo;
            }
            set
            {
                if ((this._crNo != value))
                {
                    this.OncrNoChanging(value);
                    this.SendPropertyChanging();
                    this._crNo = value;
                    this.SendPropertyChanged("crNo");
                    this.OncrNoChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_crIssu", DbType = "VarChar(50)")]
        public string crIssu
        {
            get
            {
                return this._crIssu;
            }
            set
            {
                if ((this._crIssu != value))
                {
                    this.OncrIssuChanging(value);
                    this.SendPropertyChanging();
                    this._crIssu = value;
                    this.SendPropertyChanged("crIssu");
                    this.OncrIssuChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_crExp", DbType = "VarChar(50)")]
        public string crExp
        {
            get
            {
                return this._crExp;
            }
            set
            {
                if ((this._crExp != value))
                {
                    this.OncrExpChanging(value);
                    this.SendPropertyChanging();
                    this._crExp = value;
                    this.SendPropertyChanged("crExp");
                    this.OncrExpChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_BldNo", DbType = "VarChar(50)")]
        public string BldNo
        {
            get
            {
                return this._BldNo;
            }
            set
            {
                if ((this._BldNo != value))
                {
                    this.OnBldNoChanging(value);
                    this.SendPropertyChanging();
                    this._BldNo = value;
                    this.SendPropertyChanged("BldNo");
                    this.OnBldNoChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_BldIssu", DbType = "VarChar(50)")]
        public string BldIssu
        {
            get
            {
                return this._BldIssu;
            }
            set
            {
                if ((this._BldIssu != value))
                {
                    this.OnBldIssuChanging(value);
                    this.SendPropertyChanging();
                    this._BldIssu = value;
                    this.SendPropertyChanged("BldIssu");
                    this.OnBldIssuChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_BldExp", DbType = "VarChar(50)")]
        public string BldExp
        {
            get
            {
                return this._BldExp;
            }
            set
            {
                if ((this._BldExp != value))
                {
                    this.OnBldExpChanging(value);
                    this.SendPropertyChanging();
                    this._BldExp = value;
                    this.SendPropertyChanged("BldExp");
                    this.OnBldExpChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_dfNo", DbType = "VarChar(50)")]
        public string dfNo
        {
            get
            {
                return this._dfNo;
            }
            set
            {
                if ((this._dfNo != value))
                {
                    this.OndfNoChanging(value);
                    this.SendPropertyChanging();
                    this._dfNo = value;
                    this.SendPropertyChanged("dfNo");
                    this.OndfNoChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_dfIssu", DbType = "VarChar(10)")]
        public string dfIssu
        {
            get
            {
                return this._dfIssu;
            }
            set
            {
                if ((this._dfIssu != value))
                {
                    this.OndfIssuChanging(value);
                    this.SendPropertyChanging();
                    this._dfIssu = value;
                    this.SendPropertyChanged("dfIssu");
                    this.OndfIssuChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_dfExp", DbType = "VarChar(10)")]
        public string dfExp
        {
            get
            {
                return this._dfExp;
            }
            set
            {
                if ((this._dfExp != value))
                {
                    this.OndfExpChanging(value);
                    this.SendPropertyChanging();
                    this._dfExp = value;
                    this.SendPropertyChanged("dfExp");
                    this.OndfExpChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.AssociationAttribute(Name = "T_Branch_T_User", Storage = "_T_Users", ThisKey = "Branch_no", OtherKey = "Brn")]
        public EntitySet<T_User> T_Users
        {
            get
            {
                return this._T_Users;
            }
            set
            {
                this._T_Users.Assign(value);
            }
        }

        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            if ((this.PropertyChanging != null))
            {
                this.PropertyChanging(this, emptyChangingEventArgs);
            }
        }

        protected virtual void SendPropertyChanged(String propertyName)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }

        private void attach_T_Users(T_User entity)
        {
            this.SendPropertyChanging();
            entity.T_Branch = this;
        }

        private void detach_T_Users(T_User entity)
        {
            this.SendPropertyChanging();
            entity.T_Branch = null;
        }
    }

    [global::System.Data.Linq.Mapping.TableAttribute(Name = "dbo.T_Users")]
    public partial class T_User : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);

        private int _Usr_ID;

        private string _UsrNo;

        private string _UsrNamA;

        private string _UsrNamE;

        private string _Pass;

        private string _Brn;

        private System.Nullable<int> _Sts;

        private System.Nullable<int> _Typ;

        private System.Nullable<int> _ProLng;

        private string _FilStr;

        private string _InvStr;

        private string _SndStr;

        private string _StkRep;

        private string _AccRep;

        private string _SetStr;

        private string _EditCost;

        private string _PassQty;

        private string _RepInv1;

        private string _RepInv2;

        private string _RepInv3;

        private string _RepInv4;

        private string _RepInv5;

        private string _RepInv6;

        private string _RepAcc1;

        private string _RepAcc2;

        private string _RepAcc3;

        private string _RepAcc4;

        private string _RepAcc5;

        private string _RepAcc6;

        private string _Emp_FilStr;

        private string _Emp_MovStr;

        private string _Emp_SalStr;

        private string _Emp_RepStr;

        private string _Emp_GenStr;

        private System.Nullable<int> _CreateGaid;

        private System.Nullable<int> _UserPointTyp;

        private string _CashAccNo_D;

        private string _CashAccNo_C;

        private string _NetworkAccNo_D;

        private string _NetworkAccNo_C;

        private string _CreaditAccNo_D;

        private string _CreaditAccNo_C;

        private System.Nullable<double> _Comm_Inv;

        private System.Nullable<double> _Comm_Gaid;

        private string _CashAccNo_D_R;

        private string _CashAccNo_C_R;

        private string _NetworkAccNo_D_R;

        private string _NetworkAccNo_C_R;

        private string _CreaditAccNo_D_R;

        private string _CreaditAccNo_C_R;

        private string _PeaperTyp;

        private string _StorePrmission;

        private System.Nullable<int> _DefStores;

        private string _StopBanner;

        private System.Data.Linq.Binary _UsrImg;

        private System.Nullable<double> _MaxDiscountSals;

        private System.Nullable<double> _MaxDiscountPurchaes;

        private string _vColumnStr1;

        private string _vColumnStr2;

        private string _vColumnStr3;

        private string _vColumnStr4;

        private System.Nullable<double> _vColumnNum1;

        private System.Nullable<int> _vColumnNum2;

        private string _Eqar_FilStr;

        private string _Eqar_TenantStr;

        private string _Eqar_RepStr;

        private string _Eqar_GenStr;

        private EntityRef<T_Branch> _T_Branch;

        #region Extensibility Method Definitions
        partial void OnLoaded();
        partial void OnValidate(System.Data.Linq.ChangeAction action);
        partial void OnCreated();
        partial void OnUsr_IDChanging(int value);
        partial void OnUsr_IDChanged();
        partial void OnUsrNoChanging(string value);
        partial void OnUsrNoChanged();
        partial void OnUsrNamAChanging(string value);
        partial void OnUsrNamAChanged();
        partial void OnUsrNamEChanging(string value);
        partial void OnUsrNamEChanged();
        partial void OnPassChanging(string value);
        partial void OnPassChanged();
        partial void OnBrnChanging(string value);
        partial void OnBrnChanged();
        partial void OnStsChanging(System.Nullable<int> value);
        partial void OnStsChanged();
        partial void OnTypChanging(System.Nullable<int> value);
        partial void OnTypChanged();
        partial void OnProLngChanging(System.Nullable<int> value);
        partial void OnProLngChanged();
        partial void OnFilStrChanging(string value);
        partial void OnFilStrChanged();
        partial void OnInvStrChanging(string value);
        partial void OnInvStrChanged();
        partial void OnSndStrChanging(string value);
        partial void OnSndStrChanged();
        partial void OnStkRepChanging(string value);
        partial void OnStkRepChanged();
        partial void OnAccRepChanging(string value);
        partial void OnAccRepChanged();
        partial void OnSetStrChanging(string value);
        partial void OnSetStrChanged();
        partial void OnEditCostChanging(string value);
        partial void OnEditCostChanged();
        partial void OnPassQtyChanging(string value);
        partial void OnPassQtyChanged();
        partial void OnRepInv1Changing(string value);
        partial void OnRepInv1Changed();
        partial void OnRepInv2Changing(string value);
        partial void OnRepInv2Changed();
        partial void OnRepInv3Changing(string value);
        partial void OnRepInv3Changed();
        partial void OnRepInv4Changing(string value);
        partial void OnRepInv4Changed();
        partial void OnRepInv5Changing(string value);
        partial void OnRepInv5Changed();
        partial void OnRepInv6Changing(string value);
        partial void OnRepInv6Changed();
        partial void OnRepAcc1Changing(string value);
        partial void OnRepAcc1Changed();
        partial void OnRepAcc2Changing(string value);
        partial void OnRepAcc2Changed();
        partial void OnRepAcc3Changing(string value);
        partial void OnRepAcc3Changed();
        partial void OnRepAcc4Changing(string value);
        partial void OnRepAcc4Changed();
        partial void OnRepAcc5Changing(string value);
        partial void OnRepAcc5Changed();
        partial void OnRepAcc6Changing(string value);
        partial void OnRepAcc6Changed();
        partial void OnEmp_FilStrChanging(string value);
        partial void OnEmp_FilStrChanged();
        partial void OnEmp_MovStrChanging(string value);
        partial void OnEmp_MovStrChanged();
        partial void OnEmp_SalStrChanging(string value);
        partial void OnEmp_SalStrChanged();
        partial void OnEmp_RepStrChanging(string value);
        partial void OnEmp_RepStrChanged();
        partial void OnEmp_GenStrChanging(string value);
        partial void OnEmp_GenStrChanged();
        partial void OnCreateGaidChanging(System.Nullable<int> value);
        partial void OnCreateGaidChanged();
        partial void OnUserPointTypChanging(System.Nullable<int> value);
        partial void OnUserPointTypChanged();
        partial void OnCashAccNo_DChanging(string value);
        partial void OnCashAccNo_DChanged();
        partial void OnCashAccNo_CChanging(string value);
        partial void OnCashAccNo_CChanged();
        partial void OnNetworkAccNo_DChanging(string value);
        partial void OnNetworkAccNo_DChanged();
        partial void OnNetworkAccNo_CChanging(string value);
        partial void OnNetworkAccNo_CChanged();
        partial void OnCreaditAccNo_DChanging(string value);
        partial void OnCreaditAccNo_DChanged();
        partial void OnCreaditAccNo_CChanging(string value);
        partial void OnCreaditAccNo_CChanged();
        partial void OnComm_InvChanging(System.Nullable<double> value);
        partial void OnComm_InvChanged();
        partial void OnComm_GaidChanging(System.Nullable<double> value);
        partial void OnComm_GaidChanged();
        partial void OnCashAccNo_D_RChanging(string value);
        partial void OnCashAccNo_D_RChanged();
        partial void OnCashAccNo_C_RChanging(string value);
        partial void OnCashAccNo_C_RChanged();
        partial void OnNetworkAccNo_D_RChanging(string value);
        partial void OnNetworkAccNo_D_RChanged();
        partial void OnNetworkAccNo_C_RChanging(string value);
        partial void OnNetworkAccNo_C_RChanged();
        partial void OnCreaditAccNo_D_RChanging(string value);
        partial void OnCreaditAccNo_D_RChanged();
        partial void OnCreaditAccNo_C_RChanging(string value);
        partial void OnCreaditAccNo_C_RChanged();
        partial void OnPeaperTypChanging(string value);
        partial void OnPeaperTypChanged();
        partial void OnStorePrmissionChanging(string value);
        partial void OnStorePrmissionChanged();
        partial void OnDefStoresChanging(System.Nullable<int> value);
        partial void OnDefStoresChanged();
        partial void OnStopBannerChanging(string value);
        partial void OnStopBannerChanged();
        partial void OnUsrImgChanging(System.Data.Linq.Binary value);
        partial void OnUsrImgChanged();
        partial void OnMaxDiscountSalsChanging(System.Nullable<double> value);
        partial void OnMaxDiscountSalsChanged();
        partial void OnMaxDiscountPurchaesChanging(System.Nullable<double> value);
        partial void OnMaxDiscountPurchaesChanged();
        partial void OnvColumnStr1Changing(string value);
        partial void OnvColumnStr1Changed();
        partial void OnvColumnStr2Changing(string value);
        partial void OnvColumnStr2Changed();
        partial void OnvColumnStr3Changing(string value);
        partial void OnvColumnStr3Changed();
        partial void OnvColumnStr4Changing(string value);
        partial void OnvColumnStr4Changed();
        partial void OnvColumnNum1Changing(System.Nullable<double> value);
        partial void OnvColumnNum1Changed();
        partial void OnvColumnNum2Changing(System.Nullable<int> value);
        partial void OnvColumnNum2Changed();
        partial void OnEqar_FilStrChanging(string value);
        partial void OnEqar_FilStrChanged();
        partial void OnEqar_TenantStrChanging(string value);
        partial void OnEqar_TenantStrChanged();
        partial void OnEqar_RepStrChanging(string value);
        partial void OnEqar_RepStrChanged();
        partial void OnEqar_GenStrChanging(string value);
        partial void OnEqar_GenStrChanged();
        #endregion

        public T_User()
        {
            this._T_Branch = default(EntityRef<T_Branch>);
            OnCreated();
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Usr_ID", AutoSync = AutoSync.Always, DbType = "Int NOT NULL IDENTITY", IsDbGenerated = true)]
        public int Usr_ID
        {
            get
            {
                return this._Usr_ID;
            }
            set
            {
                if ((this._Usr_ID != value))
                {
                    this.OnUsr_IDChanging(value);
                    this.SendPropertyChanging();
                    this._Usr_ID = value;
                    this.SendPropertyChanged("Usr_ID");
                    this.OnUsr_IDChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_UsrNo", DbType = "VarChar(3) NOT NULL", CanBeNull = false, IsPrimaryKey = true)]
        public string UsrNo
        {
            get
            {
                return this._UsrNo;
            }
            set
            {
                if ((this._UsrNo != value))
                {
                    this.OnUsrNoChanging(value);
                    this.SendPropertyChanging();
                    this._UsrNo = value;
                    this.SendPropertyChanged("UsrNo");
                    this.OnUsrNoChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_UsrNamA", DbType = "VarChar(50)")]
        public string UsrNamA
        {
            get
            {
                return this._UsrNamA;
            }
            set
            {
                if ((this._UsrNamA != value))
                {
                    this.OnUsrNamAChanging(value);
                    this.SendPropertyChanging();
                    this._UsrNamA = value;
                    this.SendPropertyChanged("UsrNamA");
                    this.OnUsrNamAChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_UsrNamE", DbType = "VarChar(50)")]
        public string UsrNamE
        {
            get
            {
                return this._UsrNamE;
            }
            set
            {
                if ((this._UsrNamE != value))
                {
                    this.OnUsrNamEChanging(value);
                    this.SendPropertyChanging();
                    this._UsrNamE = value;
                    this.SendPropertyChanged("UsrNamE");
                    this.OnUsrNamEChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Pass", DbType = "VarChar(250)")]
        public string Pass
        {
            get
            {
                return this._Pass;
            }
            set
            {
                if ((this._Pass != value))
                {
                    this.OnPassChanging(value);
                    this.SendPropertyChanging();
                    this._Pass = value;
                    this.SendPropertyChanged("Pass");
                    this.OnPassChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Brn", DbType = "VarChar(50)")]
        public string Brn
        {
            get
            {
                return this._Brn;
            }
            set
            {
                if ((this._Brn != value))
                {
                    if (this._T_Branch.HasLoadedOrAssignedValue)
                    {
                        throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
                    }
                    this.OnBrnChanging(value);
                    this.SendPropertyChanging();
                    this._Brn = value;
                    this.SendPropertyChanged("Brn");
                    this.OnBrnChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Sts", DbType = "Int")]
        public System.Nullable<int> Sts
        {
            get
            {
                return this._Sts;
            }
            set
            {
                if ((this._Sts != value))
                {
                    this.OnStsChanging(value);
                    this.SendPropertyChanging();
                    this._Sts = value;
                    this.SendPropertyChanged("Sts");
                    this.OnStsChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Typ", DbType = "Int")]
        public System.Nullable<int> Typ
        {
            get
            {
                return this._Typ;
            }
            set
            {
                if ((this._Typ != value))
                {
                    this.OnTypChanging(value);
                    this.SendPropertyChanging();
                    this._Typ = value;
                    this.SendPropertyChanged("Typ");
                    this.OnTypChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_ProLng", DbType = "Int")]
        public System.Nullable<int> ProLng
        {
            get
            {
                return this._ProLng;
            }
            set
            {
                if ((this._ProLng != value))
                {
                    this.OnProLngChanging(value);
                    this.SendPropertyChanging();
                    this._ProLng = value;
                    this.SendPropertyChanged("ProLng");
                    this.OnProLngChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_FilStr", DbType = "VarChar(150)")]
        public string FilStr
        {
            get
            {
                return this._FilStr;
            }
            set
            {
                if ((this._FilStr != value))
                {
                    this.OnFilStrChanging(value);
                    this.SendPropertyChanging();
                    this._FilStr = value;
                    this.SendPropertyChanged("FilStr");
                    this.OnFilStrChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_InvStr", DbType = "VarChar(150)")]
        public string InvStr
        {
            get
            {
                return this._InvStr;
            }
            set
            {
                if ((this._InvStr != value))
                {
                    this.OnInvStrChanging(value);
                    this.SendPropertyChanging();
                    this._InvStr = value;
                    this.SendPropertyChanged("InvStr");
                    this.OnInvStrChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_SndStr", DbType = "VarChar(150)")]
        public string SndStr
        {
            get
            {
                return this._SndStr;
            }
            set
            {
                if ((this._SndStr != value))
                {
                    this.OnSndStrChanging(value);
                    this.SendPropertyChanging();
                    this._SndStr = value;
                    this.SendPropertyChanged("SndStr");
                    this.OnSndStrChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_StkRep", DbType = "VarChar(150)")]
        public string StkRep
        {
            get
            {
                return this._StkRep;
            }
            set
            {
                if ((this._StkRep != value))
                {
                    this.OnStkRepChanging(value);
                    this.SendPropertyChanging();
                    this._StkRep = value;
                    this.SendPropertyChanged("StkRep");
                    this.OnStkRepChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_AccRep", DbType = "VarChar(150)")]
        public string AccRep
        {
            get
            {
                return this._AccRep;
            }
            set
            {
                if ((this._AccRep != value))
                {
                    this.OnAccRepChanging(value);
                    this.SendPropertyChanging();
                    this._AccRep = value;
                    this.SendPropertyChanged("AccRep");
                    this.OnAccRepChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_SetStr", DbType = "VarChar(150)")]
        public string SetStr
        {
            get
            {
                return this._SetStr;
            }
            set
            {
                if ((this._SetStr != value))
                {
                    this.OnSetStrChanging(value);
                    this.SendPropertyChanging();
                    this._SetStr = value;
                    this.SendPropertyChanged("SetStr");
                    this.OnSetStrChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_EditCost", DbType = "VarChar(1)")]
        public string EditCost
        {
            get
            {
                return this._EditCost;
            }
            set
            {
                if ((this._EditCost != value))
                {
                    this.OnEditCostChanging(value);
                    this.SendPropertyChanging();
                    this._EditCost = value;
                    this.SendPropertyChanged("EditCost");
                    this.OnEditCostChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_PassQty", DbType = "VarChar(150)")]
        public string PassQty
        {
            get
            {
                return this._PassQty;
            }
            set
            {
                if ((this._PassQty != value))
                {
                    this.OnPassQtyChanging(value);
                    this.SendPropertyChanging();
                    this._PassQty = value;
                    this.SendPropertyChanged("PassQty");
                    this.OnPassQtyChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_RepInv1", DbType = "VarChar(100)")]
        public string RepInv1
        {
            get
            {
                return this._RepInv1;
            }
            set
            {
                if ((this._RepInv1 != value))
                {
                    this.OnRepInv1Changing(value);
                    this.SendPropertyChanging();
                    this._RepInv1 = value;
                    this.SendPropertyChanged("RepInv1");
                    this.OnRepInv1Changed();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_RepInv2", DbType = "VarChar(100)")]
        public string RepInv2
        {
            get
            {
                return this._RepInv2;
            }
            set
            {
                if ((this._RepInv2 != value))
                {
                    this.OnRepInv2Changing(value);
                    this.SendPropertyChanging();
                    this._RepInv2 = value;
                    this.SendPropertyChanged("RepInv2");
                    this.OnRepInv2Changed();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_RepInv3", DbType = "VarChar(100)")]
        public string RepInv3
        {
            get
            {
                return this._RepInv3;
            }
            set
            {
                if ((this._RepInv3 != value))
                {
                    this.OnRepInv3Changing(value);
                    this.SendPropertyChanging();
                    this._RepInv3 = value;
                    this.SendPropertyChanged("RepInv3");
                    this.OnRepInv3Changed();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_RepInv4", DbType = "VarChar(100)")]
        public string RepInv4
        {
            get
            {
                return this._RepInv4;
            }
            set
            {
                if ((this._RepInv4 != value))
                {
                    this.OnRepInv4Changing(value);
                    this.SendPropertyChanging();
                    this._RepInv4 = value;
                    this.SendPropertyChanged("RepInv4");
                    this.OnRepInv4Changed();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_RepInv5", DbType = "VarChar(100)")]
        public string RepInv5
        {
            get
            {
                return this._RepInv5;
            }
            set
            {
                if ((this._RepInv5 != value))
                {
                    this.OnRepInv5Changing(value);
                    this.SendPropertyChanging();
                    this._RepInv5 = value;
                    this.SendPropertyChanged("RepInv5");
                    this.OnRepInv5Changed();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_RepInv6", DbType = "VarChar(100)")]
        public string RepInv6
        {
            get
            {
                return this._RepInv6;
            }
            set
            {
                if ((this._RepInv6 != value))
                {
                    this.OnRepInv6Changing(value);
                    this.SendPropertyChanging();
                    this._RepInv6 = value;
                    this.SendPropertyChanged("RepInv6");
                    this.OnRepInv6Changed();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_RepAcc1", DbType = "VarChar(100)")]
        public string RepAcc1
        {
            get
            {
                return this._RepAcc1;
            }
            set
            {
                if ((this._RepAcc1 != value))
                {
                    this.OnRepAcc1Changing(value);
                    this.SendPropertyChanging();
                    this._RepAcc1 = value;
                    this.SendPropertyChanged("RepAcc1");
                    this.OnRepAcc1Changed();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_RepAcc2", DbType = "VarChar(100)")]
        public string RepAcc2
        {
            get
            {
                return this._RepAcc2;
            }
            set
            {
                if ((this._RepAcc2 != value))
                {
                    this.OnRepAcc2Changing(value);
                    this.SendPropertyChanging();
                    this._RepAcc2 = value;
                    this.SendPropertyChanged("RepAcc2");
                    this.OnRepAcc2Changed();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_RepAcc3", DbType = "VarChar(100)")]
        public string RepAcc3
        {
            get
            {
                return this._RepAcc3;
            }
            set
            {
                if ((this._RepAcc3 != value))
                {
                    this.OnRepAcc3Changing(value);
                    this.SendPropertyChanging();
                    this._RepAcc3 = value;
                    this.SendPropertyChanged("RepAcc3");
                    this.OnRepAcc3Changed();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_RepAcc4", DbType = "VarChar(100)")]
        public string RepAcc4
        {
            get
            {
                return this._RepAcc4;
            }
            set
            {
                if ((this._RepAcc4 != value))
                {
                    this.OnRepAcc4Changing(value);
                    this.SendPropertyChanging();
                    this._RepAcc4 = value;
                    this.SendPropertyChanged("RepAcc4");
                    this.OnRepAcc4Changed();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_RepAcc5", DbType = "VarChar(100)")]
        public string RepAcc5
        {
            get
            {
                return this._RepAcc5;
            }
            set
            {
                if ((this._RepAcc5 != value))
                {
                    this.OnRepAcc5Changing(value);
                    this.SendPropertyChanging();
                    this._RepAcc5 = value;
                    this.SendPropertyChanged("RepAcc5");
                    this.OnRepAcc5Changed();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_RepAcc6", DbType = "VarChar(100)")]
        public string RepAcc6
        {
            get
            {
                return this._RepAcc6;
            }
            set
            {
                if ((this._RepAcc6 != value))
                {
                    this.OnRepAcc6Changing(value);
                    this.SendPropertyChanging();
                    this._RepAcc6 = value;
                    this.SendPropertyChanged("RepAcc6");
                    this.OnRepAcc6Changed();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Emp_FilStr", DbType = "VarChar(100)")]
        public string Emp_FilStr
        {
            get
            {
                return this._Emp_FilStr;
            }
            set
            {
                if ((this._Emp_FilStr != value))
                {
                    this.OnEmp_FilStrChanging(value);
                    this.SendPropertyChanging();
                    this._Emp_FilStr = value;
                    this.SendPropertyChanged("Emp_FilStr");
                    this.OnEmp_FilStrChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Emp_MovStr", DbType = "VarChar(100)")]
        public string Emp_MovStr
        {
            get
            {
                return this._Emp_MovStr;
            }
            set
            {
                if ((this._Emp_MovStr != value))
                {
                    this.OnEmp_MovStrChanging(value);
                    this.SendPropertyChanging();
                    this._Emp_MovStr = value;
                    this.SendPropertyChanged("Emp_MovStr");
                    this.OnEmp_MovStrChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Emp_SalStr", DbType = "VarChar(100)")]
        public string Emp_SalStr
        {
            get
            {
                return this._Emp_SalStr;
            }
            set
            {
                if ((this._Emp_SalStr != value))
                {
                    this.OnEmp_SalStrChanging(value);
                    this.SendPropertyChanging();
                    this._Emp_SalStr = value;
                    this.SendPropertyChanged("Emp_SalStr");
                    this.OnEmp_SalStrChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Emp_RepStr", DbType = "VarChar(100)")]
        public string Emp_RepStr
        {
            get
            {
                return this._Emp_RepStr;
            }
            set
            {
                if ((this._Emp_RepStr != value))
                {
                    this.OnEmp_RepStrChanging(value);
                    this.SendPropertyChanging();
                    this._Emp_RepStr = value;
                    this.SendPropertyChanged("Emp_RepStr");
                    this.OnEmp_RepStrChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Emp_GenStr", DbType = "VarChar(100)")]
        public string Emp_GenStr
        {
            get
            {
                return this._Emp_GenStr;
            }
            set
            {
                if ((this._Emp_GenStr != value))
                {
                    this.OnEmp_GenStrChanging(value);
                    this.SendPropertyChanging();
                    this._Emp_GenStr = value;
                    this.SendPropertyChanged("Emp_GenStr");
                    this.OnEmp_GenStrChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_CreateGaid", DbType = "Int")]
        public System.Nullable<int> CreateGaid
        {
            get
            {
                return this._CreateGaid;
            }
            set
            {
                if ((this._CreateGaid != value))
                {
                    this.OnCreateGaidChanging(value);
                    this.SendPropertyChanging();
                    this._CreateGaid = value;
                    this.SendPropertyChanged("CreateGaid");
                    this.OnCreateGaidChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_UserPointTyp", DbType = "Int")]
        public System.Nullable<int> UserPointTyp
        {
            get
            {
                return this._UserPointTyp;
            }
            set
            {
                if ((this._UserPointTyp != value))
                {
                    this.OnUserPointTypChanging(value);
                    this.SendPropertyChanging();
                    this._UserPointTyp = value;
                    this.SendPropertyChanged("UserPointTyp");
                    this.OnUserPointTypChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_CashAccNo_D", DbType = "VarChar(30)")]
        public string CashAccNo_D
        {
            get
            {
                return this._CashAccNo_D;
            }
            set
            {
                if ((this._CashAccNo_D != value))
                {
                    this.OnCashAccNo_DChanging(value);
                    this.SendPropertyChanging();
                    this._CashAccNo_D = value;
                    this.SendPropertyChanged("CashAccNo_D");
                    this.OnCashAccNo_DChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_CashAccNo_C", DbType = "VarChar(30)")]
        public string CashAccNo_C
        {
            get
            {
                return this._CashAccNo_C;
            }
            set
            {
                if ((this._CashAccNo_C != value))
                {
                    this.OnCashAccNo_CChanging(value);
                    this.SendPropertyChanging();
                    this._CashAccNo_C = value;
                    this.SendPropertyChanged("CashAccNo_C");
                    this.OnCashAccNo_CChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_NetworkAccNo_D", DbType = "VarChar(30)")]
        public string NetworkAccNo_D
        {
            get
            {
                return this._NetworkAccNo_D;
            }
            set
            {
                if ((this._NetworkAccNo_D != value))
                {
                    this.OnNetworkAccNo_DChanging(value);
                    this.SendPropertyChanging();
                    this._NetworkAccNo_D = value;
                    this.SendPropertyChanged("NetworkAccNo_D");
                    this.OnNetworkAccNo_DChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_NetworkAccNo_C", DbType = "VarChar(30)")]
        public string NetworkAccNo_C
        {
            get
            {
                return this._NetworkAccNo_C;
            }
            set
            {
                if ((this._NetworkAccNo_C != value))
                {
                    this.OnNetworkAccNo_CChanging(value);
                    this.SendPropertyChanging();
                    this._NetworkAccNo_C = value;
                    this.SendPropertyChanged("NetworkAccNo_C");
                    this.OnNetworkAccNo_CChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_CreaditAccNo_D", DbType = "VarChar(30)")]
        public string CreaditAccNo_D
        {
            get
            {
                return this._CreaditAccNo_D;
            }
            set
            {
                if ((this._CreaditAccNo_D != value))
                {
                    this.OnCreaditAccNo_DChanging(value);
                    this.SendPropertyChanging();
                    this._CreaditAccNo_D = value;
                    this.SendPropertyChanged("CreaditAccNo_D");
                    this.OnCreaditAccNo_DChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_CreaditAccNo_C", DbType = "VarChar(30)")]
        public string CreaditAccNo_C
        {
            get
            {
                return this._CreaditAccNo_C;
            }
            set
            {
                if ((this._CreaditAccNo_C != value))
                {
                    this.OnCreaditAccNo_CChanging(value);
                    this.SendPropertyChanging();
                    this._CreaditAccNo_C = value;
                    this.SendPropertyChanged("CreaditAccNo_C");
                    this.OnCreaditAccNo_CChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Comm_Inv", DbType = "Float")]
        public System.Nullable<double> Comm_Inv
        {
            get
            {
                return this._Comm_Inv;
            }
            set
            {
                if ((this._Comm_Inv != value))
                {
                    this.OnComm_InvChanging(value);
                    this.SendPropertyChanging();
                    this._Comm_Inv = value;
                    this.SendPropertyChanged("Comm_Inv");
                    this.OnComm_InvChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Comm_Gaid", DbType = "Float")]
        public System.Nullable<double> Comm_Gaid
        {
            get
            {
                return this._Comm_Gaid;
            }
            set
            {
                if ((this._Comm_Gaid != value))
                {
                    this.OnComm_GaidChanging(value);
                    this.SendPropertyChanging();
                    this._Comm_Gaid = value;
                    this.SendPropertyChanged("Comm_Gaid");
                    this.OnComm_GaidChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_CashAccNo_D_R", DbType = "VarChar(30)")]
        public string CashAccNo_D_R
        {
            get
            {
                return this._CashAccNo_D_R;
            }
            set
            {
                if ((this._CashAccNo_D_R != value))
                {
                    this.OnCashAccNo_D_RChanging(value);
                    this.SendPropertyChanging();
                    this._CashAccNo_D_R = value;
                    this.SendPropertyChanged("CashAccNo_D_R");
                    this.OnCashAccNo_D_RChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_CashAccNo_C_R", DbType = "VarChar(30)")]
        public string CashAccNo_C_R
        {
            get
            {
                return this._CashAccNo_C_R;
            }
            set
            {
                if ((this._CashAccNo_C_R != value))
                {
                    this.OnCashAccNo_C_RChanging(value);
                    this.SendPropertyChanging();
                    this._CashAccNo_C_R = value;
                    this.SendPropertyChanged("CashAccNo_C_R");
                    this.OnCashAccNo_C_RChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_NetworkAccNo_D_R", DbType = "VarChar(30)")]
        public string NetworkAccNo_D_R
        {
            get
            {
                return this._NetworkAccNo_D_R;
            }
            set
            {
                if ((this._NetworkAccNo_D_R != value))
                {
                    this.OnNetworkAccNo_D_RChanging(value);
                    this.SendPropertyChanging();
                    this._NetworkAccNo_D_R = value;
                    this.SendPropertyChanged("NetworkAccNo_D_R");
                    this.OnNetworkAccNo_D_RChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_NetworkAccNo_C_R", DbType = "VarChar(30)")]
        public string NetworkAccNo_C_R
        {
            get
            {
                return this._NetworkAccNo_C_R;
            }
            set
            {
                if ((this._NetworkAccNo_C_R != value))
                {
                    this.OnNetworkAccNo_C_RChanging(value);
                    this.SendPropertyChanging();
                    this._NetworkAccNo_C_R = value;
                    this.SendPropertyChanged("NetworkAccNo_C_R");
                    this.OnNetworkAccNo_C_RChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_CreaditAccNo_D_R", DbType = "VarChar(30)")]
        public string CreaditAccNo_D_R
        {
            get
            {
                return this._CreaditAccNo_D_R;
            }
            set
            {
                if ((this._CreaditAccNo_D_R != value))
                {
                    this.OnCreaditAccNo_D_RChanging(value);
                    this.SendPropertyChanging();
                    this._CreaditAccNo_D_R = value;
                    this.SendPropertyChanged("CreaditAccNo_D_R");
                    this.OnCreaditAccNo_D_RChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_CreaditAccNo_C_R", DbType = "VarChar(30)")]
        public string CreaditAccNo_C_R
        {
            get
            {
                return this._CreaditAccNo_C_R;
            }
            set
            {
                if ((this._CreaditAccNo_C_R != value))
                {
                    this.OnCreaditAccNo_C_RChanging(value);
                    this.SendPropertyChanging();
                    this._CreaditAccNo_C_R = value;
                    this.SendPropertyChanged("CreaditAccNo_C_R");
                    this.OnCreaditAccNo_C_RChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_PeaperTyp", DbType = "VarChar(150)")]
        public string PeaperTyp
        {
            get
            {
                return this._PeaperTyp;
            }
            set
            {
                if ((this._PeaperTyp != value))
                {
                    this.OnPeaperTypChanging(value);
                    this.SendPropertyChanging();
                    this._PeaperTyp = value;
                    this.SendPropertyChanged("PeaperTyp");
                    this.OnPeaperTypChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_StorePrmission", DbType = "VarChar(250)")]
        public string StorePrmission
        {
            get
            {
                return this._StorePrmission;
            }
            set
            {
                if ((this._StorePrmission != value))
                {
                    this.OnStorePrmissionChanging(value);
                    this.SendPropertyChanging();
                    this._StorePrmission = value;
                    this.SendPropertyChanged("StorePrmission");
                    this.OnStorePrmissionChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_DefStores", DbType = "Int")]
        public System.Nullable<int> DefStores
        {
            get
            {
                return this._DefStores;
            }
            set
            {
                if ((this._DefStores != value))
                {
                    this.OnDefStoresChanging(value);
                    this.SendPropertyChanging();
                    this._DefStores = value;
                    this.SendPropertyChanged("DefStores");
                    this.OnDefStoresChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_StopBanner", DbType = "VarChar(50)")]
        public string StopBanner
        {
            get
            {
                return this._StopBanner;
            }
            set
            {
                if ((this._StopBanner != value))
                {
                    this.OnStopBannerChanging(value);
                    this.SendPropertyChanging();
                    this._StopBanner = value;
                    this.SendPropertyChanged("StopBanner");
                    this.OnStopBannerChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_UsrImg", DbType = "VarBinary(MAX)", UpdateCheck = UpdateCheck.Never)]
        public System.Data.Linq.Binary UsrImg
        {
            get
            {
                return this._UsrImg;
            }
            set
            {
                if ((this._UsrImg != value))
                {
                    this.OnUsrImgChanging(value);
                    this.SendPropertyChanging();
                    this._UsrImg = value;
                    this.SendPropertyChanged("UsrImg");
                    this.OnUsrImgChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_MaxDiscountSals", DbType = "Float")]
        public System.Nullable<double> MaxDiscountSals
        {
            get
            {
                return this._MaxDiscountSals;
            }
            set
            {
                if ((this._MaxDiscountSals != value))
                {
                    this.OnMaxDiscountSalsChanging(value);
                    this.SendPropertyChanging();
                    this._MaxDiscountSals = value;
                    this.SendPropertyChanged("MaxDiscountSals");
                    this.OnMaxDiscountSalsChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_MaxDiscountPurchaes", DbType = "Float")]
        public System.Nullable<double> MaxDiscountPurchaes
        {
            get
            {
                return this._MaxDiscountPurchaes;
            }
            set
            {
                if ((this._MaxDiscountPurchaes != value))
                {
                    this.OnMaxDiscountPurchaesChanging(value);
                    this.SendPropertyChanging();
                    this._MaxDiscountPurchaes = value;
                    this.SendPropertyChanged("MaxDiscountPurchaes");
                    this.OnMaxDiscountPurchaesChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_vColumnStr1", DbType = "VarChar(250)")]
        public string vColumnStr1
        {
            get
            {
                return this._vColumnStr1;
            }
            set
            {
                if ((this._vColumnStr1 != value))
                {
                    this.OnvColumnStr1Changing(value);
                    this.SendPropertyChanging();
                    this._vColumnStr1 = value;
                    this.SendPropertyChanged("vColumnStr1");
                    this.OnvColumnStr1Changed();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_vColumnStr2", DbType = "VarChar(250)")]
        public string vColumnStr2
        {
            get
            {
                return this._vColumnStr2;
            }
            set
            {
                if ((this._vColumnStr2 != value))
                {
                    this.OnvColumnStr2Changing(value);
                    this.SendPropertyChanging();
                    this._vColumnStr2 = value;
                    this.SendPropertyChanged("vColumnStr2");
                    this.OnvColumnStr2Changed();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_vColumnStr3", DbType = "VarChar(250)")]
        public string vColumnStr3
        {
            get
            {
                return this._vColumnStr3;
            }
            set
            {
                if ((this._vColumnStr3 != value))
                {
                    this.OnvColumnStr3Changing(value);
                    this.SendPropertyChanging();
                    this._vColumnStr3 = value;
                    this.SendPropertyChanged("vColumnStr3");
                    this.OnvColumnStr3Changed();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_vColumnStr4", DbType = "VarChar(250)")]
        public string vColumnStr4
        {
            get
            {
                return this._vColumnStr4;
            }
            set
            {
                if ((this._vColumnStr4 != value))
                {
                    this.OnvColumnStr4Changing(value);
                    this.SendPropertyChanging();
                    this._vColumnStr4 = value;
                    this.SendPropertyChanged("vColumnStr4");
                    this.OnvColumnStr4Changed();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_vColumnNum1", DbType = "Float")]
        public System.Nullable<double> vColumnNum1
        {
            get
            {
                return this._vColumnNum1;
            }
            set
            {
                if ((this._vColumnNum1 != value))
                {
                    this.OnvColumnNum1Changing(value);
                    this.SendPropertyChanging();
                    this._vColumnNum1 = value;
                    this.SendPropertyChanged("vColumnNum1");
                    this.OnvColumnNum1Changed();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_vColumnNum2", DbType = "Int")]
        public System.Nullable<int> vColumnNum2
        {
            get
            {
                return this._vColumnNum2;
            }
            set
            {
                if ((this._vColumnNum2 != value))
                {
                    this.OnvColumnNum2Changing(value);
                    this.SendPropertyChanging();
                    this._vColumnNum2 = value;
                    this.SendPropertyChanged("vColumnNum2");
                    this.OnvColumnNum2Changed();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Eqar_FilStr", DbType = "VarChar(100)")]
        public string Eqar_FilStr
        {
            get
            {
                return this._Eqar_FilStr;
            }
            set
            {
                if ((this._Eqar_FilStr != value))
                {
                    this.OnEqar_FilStrChanging(value);
                    this.SendPropertyChanging();
                    this._Eqar_FilStr = value;
                    this.SendPropertyChanged("Eqar_FilStr");
                    this.OnEqar_FilStrChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Eqar_TenantStr", DbType = "VarChar(100)")]
        public string Eqar_TenantStr
        {
            get
            {
                return this._Eqar_TenantStr;
            }
            set
            {
                if ((this._Eqar_TenantStr != value))
                {
                    this.OnEqar_TenantStrChanging(value);
                    this.SendPropertyChanging();
                    this._Eqar_TenantStr = value;
                    this.SendPropertyChanged("Eqar_TenantStr");
                    this.OnEqar_TenantStrChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Eqar_RepStr", DbType = "VarChar(100)")]
        public string Eqar_RepStr
        {
            get
            {
                return this._Eqar_RepStr;
            }
            set
            {
                if ((this._Eqar_RepStr != value))
                {
                    this.OnEqar_RepStrChanging(value);
                    this.SendPropertyChanging();
                    this._Eqar_RepStr = value;
                    this.SendPropertyChanged("Eqar_RepStr");
                    this.OnEqar_RepStrChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Eqar_GenStr", DbType = "VarChar(100)")]
        public string Eqar_GenStr
        {
            get
            {
                return this._Eqar_GenStr;
            }
            set
            {
                if ((this._Eqar_GenStr != value))
                {
                    this.OnEqar_GenStrChanging(value);
                    this.SendPropertyChanging();
                    this._Eqar_GenStr = value;
                    this.SendPropertyChanged("Eqar_GenStr");
                    this.OnEqar_GenStrChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.AssociationAttribute(Name = "T_Branch_T_User", Storage = "_T_Branch", ThisKey = "Brn", OtherKey = "Branch_no", IsForeignKey = true)]
        public T_Branch T_Branch
        {
            get
            {
                return this._T_Branch.Entity;
            }
            set
            {
                T_Branch previousValue = this._T_Branch.Entity;
                if (((previousValue != value)
                            || (this._T_Branch.HasLoadedOrAssignedValue == false)))
                {
                    this.SendPropertyChanging();
                    if ((previousValue != null))
                    {
                        this._T_Branch.Entity = null;
                        previousValue.T_Users.Remove(this);
                    }
                    this._T_Branch.Entity = value;
                    if ((value != null))
                    {
                        value.T_Users.Add(this);
                        this._Brn = value.Branch_no;
                    }
                    else
                    {
                        this._Brn = default(string);
                    }
                    this.SendPropertyChanged("T_Branch");
                }
            }
        }

        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            if ((this.PropertyChanging != null))
            {
                this.PropertyChanging(this, emptyChangingEventArgs);
            }
        }

        protected virtual void SendPropertyChanged(String propertyName)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
}
#pragma warning restore 1591
