   

namespace InvAcc.Forms
{
partial class FrmInvExport
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
    
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(InvAcc.Forms.FrmInvExport));
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            panel2 = new System.Windows.Forms.Panel();
            Button_Cancel = new DevComponents.DotNetBar.ButtonX();
            button_OK = new DevComponents.DotNetBar.ButtonX();
            textBox1 = new System.Windows.Forms.TextBox();
            buttonX_ImportFile = new DevComponents.DotNetBar.ButtonX();
            textBox_SearchFilePath = new System.Windows.Forms.TextBox();
            groupBox1 = new System.Windows.Forms.GroupBox();
            textBox_Unt = new System.Windows.Forms.TextBox();
            label29 = new System.Windows.Forms.Label();
            textBox_RunNo = new System.Windows.Forms.TextBox();
            textBox_Tax = new System.Windows.Forms.TextBox();
            textBox_DateExpir = new System.Windows.Forms.TextBox();
            label9 = new System.Windows.Forms.Label();
            label10 = new System.Windows.Forms.Label();
            label11 = new System.Windows.Forms.Label();
            label7 = new System.Windows.Forms.Label();
            textBox_Discount = new System.Windows.Forms.TextBox();
            label6 = new System.Windows.Forms.Label();
            textBox_Price = new System.Windows.Forms.TextBox();
            label3 = new System.Windows.Forms.Label();
            textBox_Qty = new System.Windows.Forms.TextBox();
            label2 = new System.Windows.Forms.Label();
            textBox_Store = new System.Windows.Forms.TextBox();
            label1 = new System.Windows.Forms.Label();
            textBox_ItmNo = new System.Windows.Forms.TextBox();
            textBox_NameE = new System.Windows.Forms.TextBox();
            textBox_NameA = new System.Windows.Forms.TextBox();
            label5 = new System.Windows.Forms.Label();
            label4 = new System.Windows.Forms.Label();
            ExcelGridView = new System.Windows.Forms.DataGridView();
            panel5 = new System.Windows.Forms.Panel();
            panel2.SuspendLayout();
            groupBox1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)ExcelGridView).BeginInit();
            SuspendLayout();
            panel2.AccessibleDescription = null;
            panel2.AccessibleName = null;
            resources.ApplyResources(panel2, "panel2");
            panel2.BackColor = System.Drawing.SystemColors.GradientActiveCaption;
            panel2.BackgroundImage = null;
            panel2.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            panel2.Controls.Add(Button_Cancel);
            panel2.Controls.Add(button_OK);
            panel2.Controls.Add(textBox1);
            panel2.Controls.Add(buttonX_ImportFile);
            panel2.Controls.Add(textBox_SearchFilePath);
            panel2.Controls.Add(groupBox1);
            panel2.Controls.Add(ExcelGridView);
            panel2.Font = null;
            panel2.Name = "panel2";
            Button_Cancel.AccessibleDescription = null;
            Button_Cancel.AccessibleName = null;
            Button_Cancel.AccessibleRole = System.Windows.Forms.AccessibleRole.PushButton;
            resources.ApplyResources(Button_Cancel, "Button_Cancel");
            Button_Cancel.BackgroundImage = null;
            Button_Cancel.Checked = true;
            Button_Cancel.ColorTable = DevComponents.DotNetBar.eButtonColor.OrangeWithBackground;
            Button_Cancel.CommandParameter = null;
            Button_Cancel.Name = "Button_Cancel";
            Button_Cancel.Style = DevComponents.DotNetBar.eDotNetBarStyle.StyleManagerControlled;
            Button_Cancel.Symbol = "\uf011";
            Button_Cancel.SymbolSize = 16f;
            Button_Cancel.TextColor = System.Drawing.Color.Black;
            Button_Cancel.Click += new System.EventHandler(Button_Cancel_Click);
            button_OK.AccessibleDescription = null;
            button_OK.AccessibleName = null;
            button_OK.AccessibleRole = System.Windows.Forms.AccessibleRole.PushButton;
            resources.ApplyResources(button_OK, "button_OK");
            button_OK.BackgroundImage = null;
            button_OK.ColorTable = DevComponents.DotNetBar.eButtonColor.BlueOrb;
            button_OK.CommandParameter = null;
            button_OK.Name = "button_OK";
            button_OK.Style = DevComponents.DotNetBar.eDotNetBarStyle.StyleManagerControlled;
            button_OK.Symbol = "\uf0c5";
            button_OK.SymbolSize = 16f;
            button_OK.TextColor = System.Drawing.Color.White;
            button_OK.Click += new System.EventHandler(button_OK_Click);
            textBox1.AccessibleDescription = null;
            textBox1.AccessibleName = null;
            resources.ApplyResources(textBox1, "textBox1");
            textBox1.BackgroundImage = null;
            textBox1.Name = "textBox1";
            buttonX_ImportFile.AccessibleDescription = null;
            buttonX_ImportFile.AccessibleName = null;
            buttonX_ImportFile.AccessibleRole = System.Windows.Forms.AccessibleRole.PushButton;
            resources.ApplyResources(buttonX_ImportFile, "buttonX_ImportFile");
            buttonX_ImportFile.BackgroundImage = null;
            buttonX_ImportFile.ColorTable = DevComponents.DotNetBar.eButtonColor.Orange;
            buttonX_ImportFile.CommandParameter = null;
            buttonX_ImportFile.Name = "buttonX_ImportFile";
            buttonX_ImportFile.Style = DevComponents.DotNetBar.eDotNetBarStyle.StyleManagerControlled;
            buttonX_ImportFile.Click += new System.EventHandler(buttonX_ImportFile_Click);
            textBox_SearchFilePath.AccessibleDescription = null;
            textBox_SearchFilePath.AccessibleName = null;
            resources.ApplyResources(textBox_SearchFilePath, "textBox_SearchFilePath");
            textBox_SearchFilePath.BackColor = System.Drawing.Color.FromArgb(255, 255, 192);
            textBox_SearchFilePath.BackgroundImage = null;
            textBox_SearchFilePath.ForeColor = System.Drawing.Color.Red;
            textBox_SearchFilePath.Name = "textBox_SearchFilePath";
            textBox_SearchFilePath.ReadOnly = true;
            groupBox1.AccessibleDescription = null;
            groupBox1.AccessibleName = null;
            resources.ApplyResources(groupBox1, "groupBox1");
            groupBox1.BackColor = System.Drawing.Color.Transparent;
            groupBox1.BackgroundImage = null;
            groupBox1.Controls.Add(textBox_Unt);
            groupBox1.Controls.Add(label29);
            groupBox1.Controls.Add(textBox_RunNo);
            groupBox1.Controls.Add(textBox_Tax);
            groupBox1.Controls.Add(textBox_DateExpir);
            groupBox1.Controls.Add(label9);
            groupBox1.Controls.Add(label10);
            groupBox1.Controls.Add(label11);
            groupBox1.Controls.Add(label7);
            groupBox1.Controls.Add(textBox_Discount);
            groupBox1.Controls.Add(label6);
            groupBox1.Controls.Add(textBox_Price);
            groupBox1.Controls.Add(label3);
            groupBox1.Controls.Add(textBox_Qty);
            groupBox1.Controls.Add(label2);
            groupBox1.Controls.Add(textBox_Store);
            groupBox1.Controls.Add(label1);
            groupBox1.Controls.Add(textBox_ItmNo);
            groupBox1.Controls.Add(textBox_NameE);
            groupBox1.Controls.Add(textBox_NameA);
            groupBox1.Controls.Add(label5);
            groupBox1.Controls.Add(label4);
            groupBox1.Name = "groupBox1";
            groupBox1.TabStop = false;
            textBox_Unt.AccessibleDescription = null;
            textBox_Unt.AccessibleName = null;
            resources.ApplyResources(textBox_Unt, "textBox_Unt");
            textBox_Unt.BackColor = System.Drawing.Color.White;
            textBox_Unt.BackgroundImage = null;
            textBox_Unt.ForeColor = System.Drawing.Color.Red;
            textBox_Unt.Name = "textBox_Unt";
            label29.AccessibleDescription = null;
            label29.AccessibleName = null;
            resources.ApplyResources(label29, "label29");
            label29.BackColor = System.Drawing.Color.Transparent;
            label29.Name = "label29";
            textBox_RunNo.AccessibleDescription = null;
            textBox_RunNo.AccessibleName = null;
            resources.ApplyResources(textBox_RunNo, "textBox_RunNo");
            textBox_RunNo.BackgroundImage = null;
            textBox_RunNo.ForeColor = System.Drawing.Color.Red;
            textBox_RunNo.Name = "textBox_RunNo";
            textBox_Tax.AccessibleDescription = null;
            textBox_Tax.AccessibleName = null;
            resources.ApplyResources(textBox_Tax, "textBox_Tax");
            textBox_Tax.BackgroundImage = null;
            textBox_Tax.ForeColor = System.Drawing.Color.Red;
            textBox_Tax.Name = "textBox_Tax";
            textBox_DateExpir.AccessibleDescription = null;
            textBox_DateExpir.AccessibleName = null;
            resources.ApplyResources(textBox_DateExpir, "textBox_DateExpir");
            textBox_DateExpir.BackgroundImage = null;
            textBox_DateExpir.ForeColor = System.Drawing.Color.Red;
            textBox_DateExpir.Name = "textBox_DateExpir";
            label9.AccessibleDescription = null;
            label9.AccessibleName = null;
            resources.ApplyResources(label9, "label9");
            label9.BackColor = System.Drawing.Color.Transparent;
            label9.Name = "label9";
            label10.AccessibleDescription = null;
            label10.AccessibleName = null;
            resources.ApplyResources(label10, "label10");
            label10.BackColor = System.Drawing.Color.Transparent;
            label10.Name = "label10";
            label11.AccessibleDescription = null;
            label11.AccessibleName = null;
            resources.ApplyResources(label11, "label11");
            label11.BackColor = System.Drawing.Color.Transparent;
            label11.Name = "label11";
            label7.AccessibleDescription = null;
            label7.AccessibleName = null;
            resources.ApplyResources(label7, "label7");
            label7.BackColor = System.Drawing.Color.Transparent;
            label7.Name = "label7";
            textBox_Discount.AccessibleDescription = null;
            textBox_Discount.AccessibleName = null;
            resources.ApplyResources(textBox_Discount, "textBox_Discount");
            textBox_Discount.BackgroundImage = null;
            textBox_Discount.ForeColor = System.Drawing.Color.Red;
            textBox_Discount.Name = "textBox_Discount";
            label6.AccessibleDescription = null;
            label6.AccessibleName = null;
            resources.ApplyResources(label6, "label6");
            label6.BackColor = System.Drawing.Color.Transparent;
            label6.Name = "label6";
            textBox_Price.AccessibleDescription = null;
            textBox_Price.AccessibleName = null;
            resources.ApplyResources(textBox_Price, "textBox_Price");
            textBox_Price.BackgroundImage = null;
            textBox_Price.ForeColor = System.Drawing.Color.Red;
            textBox_Price.Name = "textBox_Price";
            label3.AccessibleDescription = null;
            label3.AccessibleName = null;
            resources.ApplyResources(label3, "label3");
            label3.BackColor = System.Drawing.Color.Transparent;
            label3.Name = "label3";
            textBox_Qty.AccessibleDescription = null;
            textBox_Qty.AccessibleName = null;
            resources.ApplyResources(textBox_Qty, "textBox_Qty");
            textBox_Qty.BackgroundImage = null;
            textBox_Qty.ForeColor = System.Drawing.Color.Red;
            textBox_Qty.Name = "textBox_Qty";
            label2.AccessibleDescription = null;
            label2.AccessibleName = null;
            resources.ApplyResources(label2, "label2");
            label2.BackColor = System.Drawing.Color.Transparent;
            label2.Name = "label2";
            textBox_Store.AccessibleDescription = null;
            textBox_Store.AccessibleName = null;
            resources.ApplyResources(textBox_Store, "textBox_Store");
            textBox_Store.BackgroundImage = null;
            textBox_Store.ForeColor = System.Drawing.Color.Red;
            textBox_Store.Name = "textBox_Store";
            label1.AccessibleDescription = null;
            label1.AccessibleName = null;
            resources.ApplyResources(label1, "label1");
            label1.BackColor = System.Drawing.Color.Transparent;
            label1.Name = "label1";
            textBox_ItmNo.AccessibleDescription = null;
            textBox_ItmNo.AccessibleName = null;
            resources.ApplyResources(textBox_ItmNo, "textBox_ItmNo");
            textBox_ItmNo.BackColor = System.Drawing.Color.Yellow;
            textBox_ItmNo.BackgroundImage = null;
            textBox_ItmNo.ForeColor = System.Drawing.Color.Red;
            textBox_ItmNo.Name = "textBox_ItmNo";
            textBox_ItmNo.Click += new System.EventHandler(textBox_EmpNo_Click);
            textBox_NameE.AccessibleDescription = null;
            textBox_NameE.AccessibleName = null;
            resources.ApplyResources(textBox_NameE, "textBox_NameE");
            textBox_NameE.BackColor = System.Drawing.Color.White;
            textBox_NameE.BackgroundImage = null;
            textBox_NameE.ForeColor = System.Drawing.Color.Red;
            textBox_NameE.Name = "textBox_NameE";
            textBox_NameE.Click += new System.EventHandler(textBox_TimeLeave1_Click);
            textBox_NameA.AccessibleDescription = null;
            textBox_NameA.AccessibleName = null;
            resources.ApplyResources(textBox_NameA, "textBox_NameA");
            textBox_NameA.BackColor = System.Drawing.Color.White;
            textBox_NameA.BackgroundImage = null;
            textBox_NameA.ForeColor = System.Drawing.Color.Red;
            textBox_NameA.Name = "textBox_NameA";
            textBox_NameA.Click += new System.EventHandler(textBox_Time1_Click);
            label5.AccessibleDescription = null;
            label5.AccessibleName = null;
            resources.ApplyResources(label5, "label5");
            label5.BackColor = System.Drawing.Color.Transparent;
            label5.Name = "label5";
            label4.AccessibleDescription = null;
            label4.AccessibleName = null;
            resources.ApplyResources(label4, "label4");
            label4.BackColor = System.Drawing.Color.Transparent;
            label4.Name = "label4";
            ExcelGridView.AccessibleDescription = null;
            ExcelGridView.AccessibleName = null;
            ExcelGridView.AllowUserToAddRows = false;
            ExcelGridView.AllowUserToDeleteRows = false;
            resources.ApplyResources(ExcelGridView, "ExcelGridView");
            ExcelGridView.BackgroundColor = System.Drawing.SystemColors.ActiveCaption;
            ExcelGridView.BackgroundImage = null;
            ExcelGridView.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.Raised;
            dataGridViewCellStyle1.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter;
            dataGridViewCellStyle1.BackColor = System.Drawing.SystemColors.Control;
            dataGridViewCellStyle1.Font = new System.Drawing.Font("Tahoma", 9f, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, 0);
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.Red;
            dataGridViewCellStyle1.SelectionBackColor = System.Drawing.SystemColors.Highlight;
            dataGridViewCellStyle1.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle1.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            ExcelGridView.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle1;
            ExcelGridView.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter;
            dataGridViewCellStyle2.BackColor = System.Drawing.SystemColors.Window;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Tahoma", 8.25f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, 0);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.SystemColors.Highlight;
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            ExcelGridView.DefaultCellStyle = dataGridViewCellStyle2;
            ExcelGridView.Font = null;
            ExcelGridView.MultiSelect = false;
            ExcelGridView.Name = "ExcelGridView";
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter;
            dataGridViewCellStyle3.BackColor = System.Drawing.SystemColors.Control;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Tahoma", 8.25f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, 0);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.Red;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.SystemColors.Highlight;
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            ExcelGridView.RowHeadersDefaultCellStyle = dataGridViewCellStyle3;
            ExcelGridView.RowHeadersVisible = false;
            ExcelGridView.CellEndEdit += new System.Windows.Forms.DataGridViewCellEventHandler(ExcelGridView_CellEndEdit);
            panel5.AccessibleDescription = null;
            panel5.AccessibleName = null;
            resources.ApplyResources(panel5, "panel5");
            panel5.BackColor = System.Drawing.Color.SteelBlue;
            panel5.BackgroundImage = null;
            panel5.Font = null;
            panel5.Name = "panel5";
            base.AccessibleDescription = null;
            base.AccessibleName = null;
            resources.ApplyResources(this, "$this");
            base.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            BackColor = System.Drawing.SystemColors.GradientInactiveCaption;
            BackgroundImage = null;
            base.Controls.Add(panel5);
            base.Controls.Add(panel2);
            Font = null;
            base.FormBorderStyle = System.Windows.Forms.FormBorderStyle.Fixed3D;
            base.KeyPreview = true;
            base.MaximizeBox = false;
            base.Name = "FrmInvExport";
            base.Load += new System.EventHandler(FrmInvExport_Load);
            base.KeyPress += new System.Windows.Forms.KeyPressEventHandler(FrmInvExport_KeyPress);
            base.KeyDown += new System.Windows.Forms.KeyEventHandler(FrmInvExport_KeyDown);
            panel2.ResumeLayout(false);
            panel2.PerformLayout();
            groupBox1.ResumeLayout(false);
            groupBox1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)ExcelGridView).EndInit();
            ResumeLayout(false);
        }//###########&&&&&&&&&&

}
}
