   

namespace InvAcc.Forms
{
partial class FrmCheck
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
    
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

private void InitializeComponent()
        {
            components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(InvAcc.Forms.FrmCheck));
            DevComponents.DotNetBar.SuperGrid.Style.Background background5 = new DevComponents.DotNetBar.SuperGrid.Style.Background();
            DevComponents.DotNetBar.SuperGrid.Style.Background background6 = new DevComponents.DotNetBar.SuperGrid.Style.Background();
            DevComponents.DotNetBar.SuperGrid.Style.Background background7 = new DevComponents.DotNetBar.SuperGrid.Style.Background();
            DevComponents.DotNetBar.SuperGrid.Style.BorderColor borderColor3 = new DevComponents.DotNetBar.SuperGrid.Style.BorderColor();
            DevComponents.DotNetBar.SuperGrid.Style.BorderColor borderColor4 = new DevComponents.DotNetBar.SuperGrid.Style.BorderColor();
            DevComponents.DotNetBar.SuperGrid.Style.BaseTreeButtonVisualStyle baseTreeButtonVisualStyle3 = new DevComponents.DotNetBar.SuperGrid.Style.BaseTreeButtonVisualStyle();
            DevComponents.DotNetBar.SuperGrid.Style.BaseTreeButtonVisualStyle baseTreeButtonVisualStyle4 = new DevComponents.DotNetBar.SuperGrid.Style.BaseTreeButtonVisualStyle();
            DevComponents.DotNetBar.SuperGrid.Style.Background background8 = new DevComponents.DotNetBar.SuperGrid.Style.Background();
            contextMenuStrip1 = new System.Windows.Forms.ContextMenuStrip(components);
            openFileDialog1 = new System.Windows.Forms.OpenFileDialog();
            saveFileDialog1 = new System.Windows.Forms.SaveFileDialog();
            panel1 = new System.Windows.Forms.Panel();
            DGV_Main = new DevComponents.DotNetBar.SuperGrid.SuperGridControl();
            groupPanel2 = new DevComponents.DotNetBar.Controls.GroupPanel();
            CmbCurr = new DevComponents.DotNetBar.Controls.ComboBoxEx();
            switchButton_AccType = new DevComponents.DotNetBar.Controls.SwitchButton();
            txtBrancheName = new System.Windows.Forms.TextBox();
            txtBXBankName = new System.Windows.Forms.TextBox();
            switchButton_PageTyp = new DevComponents.DotNetBar.Controls.SwitchButton();
            label1 = new System.Windows.Forms.Label();
            button_SrchBrancheNo = new DevComponents.DotNetBar.ButtonX();
            txtBrancheNo = new System.Windows.Forms.TextBox();
            button_SrchBXBankNo = new DevComponents.DotNetBar.ButtonX();
            groupBox5 = new System.Windows.Forms.GroupBox();
            checkBox_Yes = new DevComponents.DotNetBar.Controls.CheckBoxX();
            checkBox_No = new DevComponents.DotNetBar.Controls.CheckBoxX();
            checkBox_Cancel = new DevComponents.DotNetBar.Controls.CheckBoxX();
            txtBXBankNo = new System.Windows.Forms.TextBox();
            label2 = new System.Windows.Forms.Label();
            button_OK = new DevComponents.DotNetBar.ButtonX();
            button_Return = new DevComponents.DotNetBar.ButtonX();
            button_BackCancel = new DevComponents.DotNetBar.ButtonX();
            button_BackPay = new DevComponents.DotNetBar.ButtonX();
            vcr1 = new SuperGridDemo.VcrControl();
            imageList1 = new System.Windows.Forms.ImageList(components);
            timerInfoBallon = new System.Windows.Forms.Timer(components);
            timer1 = new System.Windows.Forms.Timer(components);
            superTabStrip1 = new DevComponents.DotNetBar.SuperTabStrip();
            superTabItem = new DevComponents.DotNetBar.SuperTabItem();
            buttonItem_Close = new DevComponents.DotNetBar.ButtonItem();
            button_AddPage = new DevComponents.DotNetBar.ButtonItem();
            this.netResize1 = new Softgroup.NetResize.NetResize(this.components);  this.netResize1.LabelsAutoEllipse = false;
            this.netResize1.AfterControlResize += new Softgroup.NetResize.NetResize.AfterControlResizeEventHandler(this.netResize1_AfterControlResize);
            this.Shown += new System.EventHandler(this.FrmInvSale_Shown);
            this.SizeChanged += new System.EventHandler(this.FrmInvSale_SizeChanged);
            ((System.ComponentModel.ISupportInitialize)(this.netResize1)).BeginInit();

            panel1.SuspendLayout();
            groupPanel2.SuspendLayout();
            groupBox5.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)superTabStrip1).BeginInit();
            SuspendLayout();
            contextMenuStrip1.AccessibleDescription = null;
            contextMenuStrip1.AccessibleName = null;
            resources.ApplyResources(contextMenuStrip1, "contextMenuStrip1");
            contextMenuStrip1.BackgroundImage = null;
            contextMenuStrip1.Font = null;
            contextMenuStrip1.Name = "contextMenuStrip1";
            openFileDialog1.DefaultExt = "*.rtf";
            resources.ApplyResources(openFileDialog1, "openFileDialog1");
            openFileDialog1.FilterIndex = 2;
            saveFileDialog1.DefaultExt = "*.rtf";
            saveFileDialog1.FileName = "doc1";
            resources.ApplyResources(saveFileDialog1, "saveFileDialog1");
            saveFileDialog1.FilterIndex = 2;
            panel1.AccessibleDescription = null;
            panel1.AccessibleName = null;
            resources.ApplyResources(panel1, "panel1");
            panel1.BackgroundImage = null;
            panel1.Controls.Add(DGV_Main);
            panel1.Controls.Add(groupPanel2);
            panel1.Controls.Add(vcr1);
            panel1.Font = null;
            panel1.Name = "panel1";
            DGV_Main.AccessibleDescription = null;
            DGV_Main.AccessibleName = null;
            resources.ApplyResources(DGV_Main, "DGV_Main");
            DGV_Main.BackColor = System.Drawing.Color.Transparent;
            DGV_Main.BackgroundImage = null;
            background5.BackFillType = DevComponents.DotNetBar.SuperGrid.Style.BackFillType.ForwardDiagonalCenter;
            background5.Color1 = System.Drawing.SystemColors.GradientActiveCaption;
            background5.Color2 = System.Drawing.Color.White;
            DGV_Main.DefaultVisualStyles.GroupByStyles.Default.Background = background5;
            background6.BackFillType = DevComponents.DotNetBar.SuperGrid.Style.BackFillType.Center;
            background6.Color1 = System.Drawing.Color.LightSteelBlue;
            DGV_Main.DefaultVisualStyles.RowStyles.Default.Background = background6;
            background7.Color1 = System.Drawing.Color.FromArgb(255, 255, 192);
            DGV_Main.DefaultVisualStyles.RowStyles.MouseOver.Background = background7;
            DGV_Main.FilterExprColors.SysFunction = System.Drawing.Color.DarkRed;
            DGV_Main.ForeColor = System.Drawing.Color.Black;
            DGV_Main.Tag= "F962CEC7-CD8F-4911-A9E9-CAB39962FC1F";
            DGV_Main.Name = "DGV_Main";
            DGV_Main.PrimaryGrid.ActiveRowIndicatorStyle = DevComponents.DotNetBar.SuperGrid.ActiveRowIndicatorStyle.Both;
            DGV_Main.PrimaryGrid.AllowEdit = false;
            DGV_Main.PrimaryGrid.Caption.BackgroundImageLayout = DevComponents.DotNetBar.SuperGrid.GridBackgroundImageLayout.Center;
            DGV_Main.PrimaryGrid.Caption.Text = "";
            DGV_Main.PrimaryGrid.Caption.Visible = false;
            DGV_Main.PrimaryGrid.DefaultVisualStyles.AlternateColumnCellStyles.Default.AllowWrap = DevComponents.DotNetBar.SuperGrid.Style.Tbool.False;
            DGV_Main.PrimaryGrid.DefaultVisualStyles.AlternateColumnCellStyles.Default.TextColor = System.Drawing.Color.Black;
            DGV_Main.PrimaryGrid.DefaultVisualStyles.AlternateRowCellStyles.Default.AllowWrap = DevComponents.DotNetBar.SuperGrid.Style.Tbool.False;
            DGV_Main.PrimaryGrid.DefaultVisualStyles.AlternateRowCellStyles.Default.TextColor = System.Drawing.Color.Black;
            DGV_Main.PrimaryGrid.DefaultVisualStyles.CaptionStyles.Default.Font = new System.Drawing.Font("Tahoma", 8.25f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, 0);
            DGV_Main.PrimaryGrid.DefaultVisualStyles.CaptionStyles.Default.TextColor = System.Drawing.Color.White;
            DGV_Main.PrimaryGrid.DefaultVisualStyles.CaptionStyles.ReadOnly.Alignment = DevComponents.DotNetBar.SuperGrid.Style.Alignment.MiddleCenter;
            DGV_Main.PrimaryGrid.DefaultVisualStyles.CellStyles.Selected.Alignment = DevComponents.DotNetBar.SuperGrid.Style.Alignment.MiddleCenter;
            DGV_Main.PrimaryGrid.DefaultVisualStyles.ColumnHeaderRowStyles.Default.RowHeader.AllowWrap = DevComponents.DotNetBar.SuperGrid.Style.Tbool.True;
            borderColor3.Bottom = System.Drawing.Color.Black;
            borderColor3.Left = System.Drawing.Color.Black;
            borderColor3.Right = System.Drawing.Color.Black;
            borderColor3.Top = System.Drawing.Color.Black;
            DGV_Main.PrimaryGrid.DefaultVisualStyles.ColumnHeaderStyles.Default.BorderColor = borderColor3;
            DGV_Main.PrimaryGrid.DefaultVisualStyles.ColumnHeaderStyles.Default.Font = new System.Drawing.Font("Tahoma", 8.25f, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, 0);
            DGV_Main.PrimaryGrid.DefaultVisualStyles.ColumnHeaderStyles.Default.TextColor = System.Drawing.Color.SteelBlue;
            DGV_Main.PrimaryGrid.DefaultVisualStyles.FilterColumnHeaderStyles.Default.TextColor = System.Drawing.Color.White;
            DGV_Main.PrimaryGrid.DefaultVisualStyles.FooterStyles.Default.TextColor = System.Drawing.Color.White;
            DGV_Main.PrimaryGrid.DefaultVisualStyles.GridPanelStyle.AllowWrap = DevComponents.DotNetBar.SuperGrid.Style.Tbool.False;
            borderColor4.Bottom = System.Drawing.Color.Black;
            borderColor4.Left = System.Drawing.Color.Black;
            borderColor4.Right = System.Drawing.Color.Black;
            borderColor4.Top = System.Drawing.Color.Black;
            DGV_Main.PrimaryGrid.DefaultVisualStyles.GridPanelStyle.BorderColor = borderColor4;
            baseTreeButtonVisualStyle3.BorderColor = System.Drawing.Color.White;
            baseTreeButtonVisualStyle3.LineColor = System.Drawing.Color.White;
            DGV_Main.PrimaryGrid.DefaultVisualStyles.GridPanelStyle.CircleTreeButtonStyle.ExpandButton = baseTreeButtonVisualStyle3;
            DGV_Main.PrimaryGrid.DefaultVisualStyles.GridPanelStyle.HeaderHLinePattern = DevComponents.DotNetBar.SuperGrid.Style.LinePattern.None;
            background8.Color1 = System.Drawing.Color.FromArgb(255, 255, 192);
            baseTreeButtonVisualStyle4.Background = background8;
            DGV_Main.PrimaryGrid.DefaultVisualStyles.GridPanelStyle.SquareTreeButtonStyle.ExpandButton = baseTreeButtonVisualStyle4;
            DGV_Main.PrimaryGrid.DefaultVisualStyles.GridPanelStyle.TextColor = System.Drawing.Color.White;
            DGV_Main.PrimaryGrid.DefaultVisualStyles.TitleStyles.Default.RowHeaderStyle.TextAlignment = DevComponents.DotNetBar.SuperGrid.Style.Alignment.MiddleCenter;
            DGV_Main.PrimaryGrid.GroupByRow.RowHeaderVisibility = DevComponents.DotNetBar.SuperGrid.RowHeaderVisibility.Never;
            DGV_Main.PrimaryGrid.GroupByRow.Text = "أوراق القبــــــض";
            DGV_Main.PrimaryGrid.GroupByRow.WatermarkText = "";
            DGV_Main.PrimaryGrid.InitialActiveRow = DevComponents.DotNetBar.SuperGrid.RelativeRow.None;
            DGV_Main.PrimaryGrid.InitialSelection = DevComponents.DotNetBar.SuperGrid.RelativeSelection.None;
            DGV_Main.PrimaryGrid.MultiSelect = false;
            DGV_Main.PrimaryGrid.SelectionGranularity = DevComponents.DotNetBar.SuperGrid.SelectionGranularity.Row;
            DGV_Main.PrimaryGrid.ShowRowHeaders = false;
            DGV_Main.PrimaryGrid.Title.AllowSelection = false;
            DGV_Main.PrimaryGrid.Title.Text = "";
            DGV_Main.PrimaryGrid.Title.Visible = false;
            DGV_Main.PrimaryGrid.Visible = false;
            DGV_Main.RowClick += new System.EventHandler<DevComponents.DotNetBar.SuperGrid.GridRowClickEventArgs>(DGV_Main_RowClick);
            groupPanel2.AccessibleDescription = null;
            groupPanel2.AccessibleName = null;
            resources.ApplyResources(groupPanel2, "groupPanel2");
            groupPanel2.BackColor = System.Drawing.Color.Transparent;
            groupPanel2.CanvasColor = System.Drawing.SystemColors.Control;
            groupPanel2.ColorSchemeStyle = DevComponents.DotNetBar.eDotNetBarStyle.Office2007;
            groupPanel2.Controls.Add(CmbCurr);
            groupPanel2.Controls.Add(switchButton_AccType);
            groupPanel2.Controls.Add(txtBrancheName);
            groupPanel2.Controls.Add(txtBXBankName);
            groupPanel2.Controls.Add(switchButton_PageTyp);
            groupPanel2.Controls.Add(label1);
            groupPanel2.Controls.Add(button_SrchBrancheNo);
            groupPanel2.Controls.Add(txtBrancheNo);
            groupPanel2.Controls.Add(button_SrchBXBankNo);
            groupPanel2.Controls.Add(groupBox5);
            groupPanel2.Controls.Add(txtBXBankNo);
            groupPanel2.Controls.Add(label2);
            groupPanel2.Controls.Add(button_OK);
            groupPanel2.Controls.Add(button_Return);
            groupPanel2.Controls.Add(button_BackCancel);
            groupPanel2.Controls.Add(button_BackPay);
            groupPanel2.Font = null;
            groupPanel2.Name = "groupPanel2";
            groupPanel2.Style.BackColor2 = System.Drawing.SystemColors.GradientInactiveCaption;
            groupPanel2.Style.BackColorGradientAngle = 90;
            groupPanel2.Style.BackColorSchemePart = DevComponents.DotNetBar.eColorSchemePart.PanelBackground;
            groupPanel2.Style.BorderBottom = DevComponents.DotNetBar.eStyleBorderType.Solid;
            groupPanel2.Style.BorderBottomWidth = 1;
            groupPanel2.Style.BorderColorSchemePart = DevComponents.DotNetBar.eColorSchemePart.PanelBorder;
            groupPanel2.Style.BorderLeft = DevComponents.DotNetBar.eStyleBorderType.Solid;
            groupPanel2.Style.BorderLeftWidth = 1;
            groupPanel2.Style.BorderRight = DevComponents.DotNetBar.eStyleBorderType.Solid;
            groupPanel2.Style.BorderRightWidth = 1;
            groupPanel2.Style.BorderTop = DevComponents.DotNetBar.eStyleBorderType.Solid;
            groupPanel2.Style.BorderTopWidth = 1;
            groupPanel2.Style.CornerDiameter = 4;
            groupPanel2.Style.CornerType = DevComponents.DotNetBar.eCornerType.Rounded;
            groupPanel2.Style.TextAlignment = DevComponents.DotNetBar.eStyleTextAlignment.Center;
            groupPanel2.Style.TextColorSchemePart = DevComponents.DotNetBar.eColorSchemePart.PanelText;
            groupPanel2.StyleMouseDown.CornerType = DevComponents.DotNetBar.eCornerType.Square;
            groupPanel2.StyleMouseOver.CornerType = DevComponents.DotNetBar.eCornerType.Square;
            groupPanel2.TitleImagePosition = DevComponents.DotNetBar.eTitleImagePosition.Center;
            CmbCurr.AccessibleDescription = null;
            CmbCurr.AccessibleName = null;
            resources.ApplyResources(CmbCurr, "CmbCurr");
            CmbCurr.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.ListItems;
            CmbCurr.BackgroundImage = null;
            CmbCurr.CommandParameter = null;
            CmbCurr.DisplayMember = "Text";
            CmbCurr.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            CmbCurr.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            CmbCurr.FormattingEnabled = true;
            CmbCurr.Name = "CmbCurr";
            CmbCurr.Style = DevComponents.DotNetBar.eDotNetBarStyle.StyleManagerControlled;
            switchButton_AccType.AccessibleDescription = null;
            switchButton_AccType.AccessibleName = null;
            resources.ApplyResources(switchButton_AccType, "switchButton_AccType");
            switchButton_AccType.BackgroundImage = null;
            switchButton_AccType.BackgroundStyle.CornerType = DevComponents.DotNetBar.eCornerType.Square;
            switchButton_AccType.CommandParameter = null;
            switchButton_AccType.Font = null;
            switchButton_AccType.Name = "switchButton_AccType";
            switchButton_AccType.Style = DevComponents.DotNetBar.eDotNetBarStyle.StyleManagerControlled;
            switchButton_AccType.ValueChanged += new System.EventHandler(switchButton_AccType_ValueChanged);
            txtBrancheName.AccessibleDescription = null;
            txtBrancheName.AccessibleName = null;
            resources.ApplyResources(txtBrancheName, "txtBrancheName");
            txtBrancheName.BackColor = System.Drawing.Color.White;
            txtBrancheName.BackgroundImage = null;
            txtBrancheName.Font = null;
            txtBrancheName.ForeColor = System.Drawing.Color.FromArgb(192, 0, 0);
            txtBrancheName.Name = "txtBrancheName";
            txtBrancheName.ReadOnly = true;
            txtBXBankName.AccessibleDescription = null;
            txtBXBankName.AccessibleName = null;
            resources.ApplyResources(txtBXBankName, "txtBXBankName");
            txtBXBankName.BackColor = System.Drawing.Color.White;
            txtBXBankName.BackgroundImage = null;
            txtBXBankName.Font = null;
            txtBXBankName.ForeColor = System.Drawing.Color.FromArgb(192, 0, 0);
            txtBXBankName.Name = "txtBXBankName";
            txtBXBankName.ReadOnly = true;
            switchButton_PageTyp.AccessibleDescription = null;
            switchButton_PageTyp.AccessibleName = null;
            resources.ApplyResources(switchButton_PageTyp, "switchButton_PageTyp");
            switchButton_PageTyp.BackgroundImage = null;
            switchButton_PageTyp.BackgroundStyle.CornerType = DevComponents.DotNetBar.eCornerType.Square;
            switchButton_PageTyp.CommandParameter = null;
            switchButton_PageTyp.Font = null;
            switchButton_PageTyp.Name = "switchButton_PageTyp";
            switchButton_PageTyp.Style = DevComponents.DotNetBar.eDotNetBarStyle.StyleManagerControlled;
            switchButton_PageTyp.ValueChanged += new System.EventHandler(switchButton_PageTyp_ValueChanged);
            label1.AccessibleDescription = null;
            label1.AccessibleName = null;
            resources.ApplyResources(label1, "label1");
            label1.BackColor = System.Drawing.Color.Transparent;
            label1.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            label1.Name = "label1";
            button_SrchBrancheNo.AccessibleDescription = null;
            button_SrchBrancheNo.AccessibleName = null;
            button_SrchBrancheNo.AccessibleRole = System.Windows.Forms.AccessibleRole.PushButton;
            resources.ApplyResources(button_SrchBrancheNo, "button_SrchBrancheNo");
            button_SrchBrancheNo.BackgroundImage = null;
            button_SrchBrancheNo.ColorTable = DevComponents.DotNetBar.eButtonColor.OrangeWithBackground;
            button_SrchBrancheNo.CommandParameter = null;
            button_SrchBrancheNo.Font = null;
            button_SrchBrancheNo.Name = "button_SrchBrancheNo";
            button_SrchBrancheNo.Style = DevComponents.DotNetBar.eDotNetBarStyle.StyleManagerControlled;
            button_SrchBrancheNo.Symbol = "\uf002";
            button_SrchBrancheNo.SymbolSize = 12f;
            button_SrchBrancheNo.TextColor = System.Drawing.Color.SteelBlue;
            button_SrchBrancheNo.Click += new System.EventHandler(button_SrchBrancheNo_Click);
            txtBrancheNo.AccessibleDescription = null;
            txtBrancheNo.AccessibleName = null;
            resources.ApplyResources(txtBrancheNo, "txtBrancheNo");
            txtBrancheNo.BackColor = System.Drawing.Color.White;
            txtBrancheNo.BackgroundImage = null;
            txtBrancheNo.Font = null;
            txtBrancheNo.ForeColor = System.Drawing.Color.FromArgb(192, 0, 0);
            txtBrancheNo.Name = "txtBrancheNo";
            txtBrancheNo.ReadOnly = true;
            button_SrchBXBankNo.AccessibleDescription = null;
            button_SrchBXBankNo.AccessibleName = null;
            button_SrchBXBankNo.AccessibleRole = System.Windows.Forms.AccessibleRole.PushButton;
            resources.ApplyResources(button_SrchBXBankNo, "button_SrchBXBankNo");
            button_SrchBXBankNo.BackgroundImage = null;
            button_SrchBXBankNo.ColorTable = DevComponents.DotNetBar.eButtonColor.OrangeWithBackground;
            button_SrchBXBankNo.CommandParameter = null;
            button_SrchBXBankNo.Font = null;
            button_SrchBXBankNo.Name = "button_SrchBXBankNo";
            button_SrchBXBankNo.Style = DevComponents.DotNetBar.eDotNetBarStyle.StyleManagerControlled;
            button_SrchBXBankNo.Symbol = "\uf002";
            button_SrchBXBankNo.SymbolSize = 12f;
            button_SrchBXBankNo.TextColor = System.Drawing.Color.SteelBlue;
            button_SrchBXBankNo.Click += new System.EventHandler(button_SrchBXBankNo_Click);
            groupBox5.AccessibleDescription = null;
            groupBox5.AccessibleName = null;
            resources.ApplyResources(groupBox5, "groupBox5");
            groupBox5.BackColor = System.Drawing.Color.Transparent;
            groupBox5.BackgroundImage = null;
            groupBox5.Controls.Add(checkBox_Yes);
            groupBox5.Controls.Add(checkBox_No);
            groupBox5.Controls.Add(checkBox_Cancel);
            groupBox5.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            groupBox5.ForeColor = System.Drawing.Color.FromArgb(128, 64, 64);
            groupBox5.Name = "groupBox5";
            groupBox5.TabStop = false;
            checkBox_Yes.AccessibleDescription = null;
            checkBox_Yes.AccessibleName = null;
            resources.ApplyResources(checkBox_Yes, "checkBox_Yes");
            checkBox_Yes.BackColor = System.Drawing.Color.Transparent;
            checkBox_Yes.BackgroundImage = null;
            checkBox_Yes.BackgroundStyle.CornerType = DevComponents.DotNetBar.eCornerType.Square;
            checkBox_Yes.CheckBoxStyle = DevComponents.DotNetBar.eCheckBoxStyle.RadioButton;
            checkBox_Yes.CheckSignSize = new System.Drawing.Size(14, 14);
            checkBox_Yes.CommandParameter = null;
            checkBox_Yes.Name = "checkBox_Yes";
            checkBox_Yes.Style = DevComponents.DotNetBar.eDotNetBarStyle.StyleManagerControlled;
            checkBox_Yes.Tag = "1";
            checkBox_Yes.CheckedChanged += new System.EventHandler(checkBox_Yes_CheckedChanged);
            checkBox_No.AccessibleDescription = null;
            checkBox_No.AccessibleName = null;
            resources.ApplyResources(checkBox_No, "checkBox_No");
            checkBox_No.BackColor = System.Drawing.Color.Transparent;
            checkBox_No.BackgroundImage = null;
            checkBox_No.BackgroundStyle.CornerType = DevComponents.DotNetBar.eCornerType.Square;
            checkBox_No.BackgroundStyle.TextShadowColor = System.Drawing.SystemColors.ControlLight;
            checkBox_No.BackgroundStyle.TextShadowOffset = new System.Drawing.Point(3, 3);
            checkBox_No.CheckBoxStyle = DevComponents.DotNetBar.eCheckBoxStyle.RadioButton;
            checkBox_No.Checked = true;
            checkBox_No.CheckSignSize = new System.Drawing.Size(14, 14);
            checkBox_No.CheckState = System.Windows.Forms.CheckState.Checked;
            checkBox_No.CheckValue = "Y";
            checkBox_No.CommandParameter = null;
            checkBox_No.Name = "checkBox_No";
            checkBox_No.Style = DevComponents.DotNetBar.eDotNetBarStyle.StyleManagerControlled;
            checkBox_No.Tag = "0";
            checkBox_No.CheckedChanged += new System.EventHandler(checkBox_No_CheckedChanged);
            checkBox_Cancel.AccessibleDescription = null;
            checkBox_Cancel.AccessibleName = null;
            resources.ApplyResources(checkBox_Cancel, "checkBox_Cancel");
            checkBox_Cancel.BackColor = System.Drawing.Color.Transparent;
            checkBox_Cancel.BackgroundImage = null;
            checkBox_Cancel.BackgroundStyle.CornerType = DevComponents.DotNetBar.eCornerType.Square;
            checkBox_Cancel.CheckBoxStyle = DevComponents.DotNetBar.eCheckBoxStyle.RadioButton;
            checkBox_Cancel.CheckSignSize = new System.Drawing.Size(14, 14);
            checkBox_Cancel.CommandParameter = null;
            checkBox_Cancel.Name = "checkBox_Cancel";
            checkBox_Cancel.Style = DevComponents.DotNetBar.eDotNetBarStyle.StyleManagerControlled;
            checkBox_Cancel.Tag = "2";
            checkBox_Cancel.CheckedChanged += new System.EventHandler(checkBox_Cancel_CheckedChanged);
            txtBXBankNo.AccessibleDescription = null;
            txtBXBankNo.AccessibleName = null;
            resources.ApplyResources(txtBXBankNo, "txtBXBankNo");
            txtBXBankNo.BackColor = System.Drawing.Color.White;
            txtBXBankNo.BackgroundImage = null;
            txtBXBankNo.Font = null;
            txtBXBankNo.ForeColor = System.Drawing.Color.FromArgb(192, 0, 0);
            txtBXBankNo.Name = "txtBXBankNo";
            txtBXBankNo.ReadOnly = true;
            label2.AccessibleDescription = null;
            label2.AccessibleName = null;
            resources.ApplyResources(label2, "label2");
            label2.BackColor = System.Drawing.Color.Transparent;
            label2.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            label2.Name = "label2";
            button_OK.AccessibleDescription = null;
            button_OK.AccessibleName = null;
            button_OK.AccessibleRole = System.Windows.Forms.AccessibleRole.PushButton;
            resources.ApplyResources(button_OK, "button_OK");
            button_OK.BackgroundImage = null;
            button_OK.ColorTable = DevComponents.DotNetBar.eButtonColor.BlueOrb;
            button_OK.CommandParameter = null;
            button_OK.Name = "button_OK";
            button_OK.Style = DevComponents.DotNetBar.eDotNetBarStyle.StyleManagerControlled;
            button_OK.Symbol = "\uf00c";
            button_OK.SymbolSize = 12f;
            button_OK.TextColor = System.Drawing.Color.White;
            button_OK.Click += new System.EventHandler(button_OK_Click);
            button_Return.AccessibleDescription = null;
            button_Return.AccessibleName = null;
            button_Return.AccessibleRole = System.Windows.Forms.AccessibleRole.PushButton;
            resources.ApplyResources(button_Return, "button_Return");
            button_Return.BackgroundImage = null;
            button_Return.Checked = true;
            button_Return.ColorTable = DevComponents.DotNetBar.eButtonColor.OrangeWithBackground;
            button_Return.CommandParameter = null;
            button_Return.Name = "button_Return";
            button_Return.Style = DevComponents.DotNetBar.eDotNetBarStyle.StyleManagerControlled;
            button_Return.Symbol = "\uf00d";
            button_Return.SymbolSize = 12f;
            button_Return.TextColor = System.Drawing.Color.Black;
            button_Return.Click += new System.EventHandler(button_Return_Click);
            button_BackCancel.AccessibleDescription = null;
            button_BackCancel.AccessibleName = null;
            button_BackCancel.AccessibleRole = System.Windows.Forms.AccessibleRole.PushButton;
            resources.ApplyResources(button_BackCancel, "button_BackCancel");
            button_BackCancel.BackgroundImage = null;
            button_BackCancel.ColorTable = DevComponents.DotNetBar.eButtonColor.BlueOrb;
            button_BackCancel.CommandParameter = null;
            button_BackCancel.Name = "button_BackCancel";
            button_BackCancel.Style = DevComponents.DotNetBar.eDotNetBarStyle.StyleManagerControlled;
            button_BackCancel.Symbol = "\uf00c";
            button_BackCancel.SymbolSize = 12f;
            button_BackCancel.TextColor = System.Drawing.Color.White;
            button_BackCancel.Click += new System.EventHandler(button_BackCancel_Click);
            button_BackPay.AccessibleDescription = null;
            button_BackPay.AccessibleName = null;
            button_BackPay.AccessibleRole = System.Windows.Forms.AccessibleRole.PushButton;
            resources.ApplyResources(button_BackPay, "button_BackPay");
            button_BackPay.BackgroundImage = null;
            button_BackPay.ColorTable = DevComponents.DotNetBar.eButtonColor.BlueOrb;
            button_BackPay.CommandParameter = null;
            button_BackPay.Name = "button_BackPay";
            button_BackPay.Style = DevComponents.DotNetBar.eDotNetBarStyle.StyleManagerControlled;
            button_BackPay.Symbol = "\uf00c";
            button_BackPay.SymbolSize = 12f;
            button_BackPay.TextColor = System.Drawing.Color.White;
            button_BackPay.Click += new System.EventHandler(button_BackPay_Click);
            vcr1.AccessibleDescription = null;
            vcr1.AccessibleName = null;
            resources.ApplyResources(vcr1, "vcr1");
            vcr1.BackColor = System.Drawing.Color.Transparent;
            vcr1.BackgroundImage = null;
            vcr1.Font = null;
            vcr1.Name = "vcr1";
            vcr1.NextClick += new System.EventHandler<System.EventArgs>(VcrNextClick);
            vcr1.LastClick += new System.EventHandler<System.EventArgs>(VcrLastClick);
            vcr1.PreviousClick += new System.EventHandler<System.EventArgs>(VcrPreviousClick);
            vcr1.FirstClick += new System.EventHandler<System.EventArgs>(VcrFirstClick);
            imageList1.ImageStream = (System.Windows.Forms.ImageListStreamer)resources.GetObject("imageList1.ImageStream");
            imageList1.TransparentColor = System.Drawing.Color.Magenta;
            imageList1.Images.SetKeyName(0, "");
            imageList1.Images.SetKeyName(1, "");
            imageList1.Images.SetKeyName(2, "");
            imageList1.Images.SetKeyName(3, "");
            imageList1.Images.SetKeyName(4, "");
            imageList1.Images.SetKeyName(5, "");
            imageList1.Images.SetKeyName(6, "");
            imageList1.Images.SetKeyName(7, "");
            imageList1.Images.SetKeyName(8, "");
            imageList1.Images.SetKeyName(9, "");
            imageList1.Images.SetKeyName(10, "");
            imageList1.Images.SetKeyName(11, "");
            imageList1.Images.SetKeyName(12, "");
            imageList1.Images.SetKeyName(13, "");
            imageList1.Images.SetKeyName(14, "");
            imageList1.Images.SetKeyName(15, "");
            imageList1.Images.SetKeyName(16, "");
            imageList1.Images.SetKeyName(17, "");
            imageList1.Images.SetKeyName(18, "");
            imageList1.Images.SetKeyName(19, "");
            imageList1.Images.SetKeyName(20, "");
            imageList1.Images.SetKeyName(21, "");
            imageList1.Images.SetKeyName(22, "");
            imageList1.Images.SetKeyName(23, "");
            timerInfoBallon.Interval = 3000;
            timer1.Interval = 1000;
            superTabStrip1.AccessibleDescription = null;
            superTabStrip1.AccessibleName = null;
            resources.ApplyResources(superTabStrip1, "superTabStrip1");
            superTabStrip1.AutoSelectAttachedControl = false;
            superTabStrip1.BackgroundImage = null;
            superTabStrip1.BackgroundStyle.CornerType = DevComponents.DotNetBar.eCornerType.Square;
            superTabStrip1.ContainerControlProcessDialogKey = true;
            superTabStrip1.ControlBox.Category = resources.GetString("superTabStrip1.ControlBox.Category");
            superTabStrip1.ControlBox.CloseBox.Category = resources.GetString("superTabStrip1.ControlBox.CloseBox.Category");
            superTabStrip1.ControlBox.CloseBox.CommandParameter = null;
            superTabStrip1.ControlBox.CloseBox.Description = resources.GetString("superTabStrip1.ControlBox.CloseBox.Description");
            superTabStrip1.ControlBox.CloseBox.Name = "";
            superTabStrip1.ControlBox.CloseBox.Tag = resources.GetString("superTabStrip1.ControlBox.CloseBox.Tag");
            superTabStrip1.ControlBox.CloseBox.Text = resources.GetString("superTabStrip1.ControlBox.CloseBox.Text");
            superTabStrip1.ControlBox.CloseBox.Tooltip = resources.GetString("superTabStrip1.ControlBox.CloseBox.Tooltip");
            superTabStrip1.ControlBox.CommandParameter = null;
            superTabStrip1.ControlBox.Description = resources.GetString("superTabStrip1.ControlBox.Description");
            superTabStrip1.ControlBox.MenuBox.Category = resources.GetString("superTabStrip1.ControlBox.MenuBox.Category");
            superTabStrip1.ControlBox.MenuBox.CommandParameter = null;
            superTabStrip1.ControlBox.MenuBox.Description = resources.GetString("superTabStrip1.ControlBox.MenuBox.Description");
            superTabStrip1.ControlBox.MenuBox.Name = "";
            superTabStrip1.ControlBox.MenuBox.Tag = resources.GetString("superTabStrip1.ControlBox.MenuBox.Tag");
            superTabStrip1.ControlBox.MenuBox.Text = resources.GetString("superTabStrip1.ControlBox.MenuBox.Text");
            superTabStrip1.ControlBox.MenuBox.Tooltip = resources.GetString("superTabStrip1.ControlBox.MenuBox.Tooltip");
            superTabStrip1.ControlBox.Name = "";
            superTabStrip1.ControlBox.SubItems.AddRange(new DevComponents.DotNetBar.BaseItem[2]
            {
                superTabStrip1.ControlBox.MenuBox,
                superTabStrip1.ControlBox.CloseBox
            });
            superTabStrip1.ControlBox.Tag = resources.GetString("superTabStrip1.ControlBox.Tag");
            superTabStrip1.ControlBox.Text = resources.GetString("superTabStrip1.ControlBox.Text");
            superTabStrip1.ControlBox.Tooltip = resources.GetString("superTabStrip1.ControlBox.Tooltip");
            superTabStrip1.ControlBox.Visible = false;
            superTabStrip1.Font = null;
            superTabStrip1.Name = "superTabStrip1";
            superTabStrip1.ReorderTabsEnabled = true;
            superTabStrip1.SelectedTabIndex = 0;
            superTabStrip1.TabCloseButtonHot = null;
            superTabStrip1.Tabs.AddRange(new DevComponents.DotNetBar.BaseItem[3]
            {
                superTabItem,
                buttonItem_Close,
                button_AddPage
            });
            resources.ApplyResources(superTabItem, "superTabItem");
            superTabItem.CommandParameter = null;
            superTabItem.GlobalItem = false;
            superTabItem.ImageAlignment = DevComponents.DotNetBar.ImageAlignment.MiddleCenter;
            superTabItem.ItemAlignment = DevComponents.DotNetBar.eItemAlignment.Center;
            superTabItem.Name = "superTabItem";
            superTabItem.Stretch = true;
            superTabItem.TabFont = new System.Drawing.Font("Tahoma", 9.75f, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, 0);
            superTabItem.TextAlignment = DevComponents.DotNetBar.eItemAlignment.Center;
            resources.ApplyResources(buttonItem_Close, "buttonItem_Close");
            buttonItem_Close.Checked = true;
            buttonItem_Close.ColorTable = DevComponents.DotNetBar.eButtonColor.Office2007WithBackground;
            buttonItem_Close.CommandParameter = null;
            buttonItem_Close.Name = "buttonItem_Close";
            buttonItem_Close.Stretch = true;
            buttonItem_Close.Symbol = "\uf00d";
            buttonItem_Close.SymbolSize = 12f;
            buttonItem_Close.Click += new System.EventHandler(Button_Close_Click);
            resources.ApplyResources(button_AddPage, "button_AddPage");
            button_AddPage.ButtonStyle = DevComponents.DotNetBar.eButtonStyle.ImageAndText;
            button_AddPage.ColorTable = DevComponents.DotNetBar.eButtonColor.Blue;
            button_AddPage.CommandParameter = null;
            button_AddPage.Name = "button_AddPage";
            button_AddPage.Stretch = true;
            button_AddPage.Symbol = "\uf067";
            button_AddPage.SymbolSize = 12f;
            button_AddPage.Click += new System.EventHandler(button_AddPage_Click);
            base.AccessibleDescription = null;
            base.AccessibleName = null;
            resources.ApplyResources(this, "$this");
            base.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            BackColor = System.Drawing.SystemColors.GradientInactiveCaption;
            BackgroundImage = null;
            base.Controls.Add(panel1);
            base.Controls.Add(superTabStrip1);
            Font = null;
            base.FormBorderStyle = System.Windows.Forms.FormBorderStyle.Fixed3D;
            base.KeyPreview = true;
            base.MaximizeBox = false;
            base.Name = "FrmCheck";
            base.Load += new System.EventHandler(FrmCheck_Load);
            base.KeyPress += new System.Windows.Forms.KeyPressEventHandler(Frm_KeyPress);
            base.KeyDown += new System.Windows.Forms.KeyEventHandler(Frm_KeyDown);
            panel1.ResumeLayout(false);
            groupPanel2.ResumeLayout(false);
            groupPanel2.PerformLayout();
            groupBox5.ResumeLayout(false);
            groupBox5.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)superTabStrip1).EndInit();
            ResumeLayout(false);
        }//###########&&&&&&&&&&

}
}
