using InvAcc.Controls;
using ProShared.GeneralM;
using ProShared.Stock_Data;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.SqlClient;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace InvAcc.Forms.Cards
{
    public partial class frmItemNoWizard : Form
    {
        public frmItemNoWizard()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            t_ItemsBindingSource.DataSource = db.T_Items.OrderBy(i => i.Itm_ID);
        }
        Stock_DataDataContext db = new Stock_DataDataContext();
        private void button1_Click(object sender, EventArgs e)
        {
            int index = 0;

            int con = int.Parse(start_No.Text);
            int xa = db.T_Items.Count();
            for (int i = index; i <xa ; i++)
            {
                t_ItemsBindingSource.MoveNext();
                T_Item k = t_ItemsBindingSource.Current as T_Item;

                //do
              //  {
                    k.Itm_No = (con ).ToString();
                 con++;
                //} while (db.StockItem(k.Itm_No).Itm_ID != 0);


            }
            gridControl1.Refresh();
        }

        private void textBox3_TextChanged(object sender, EventArgs e)
        {

        }

        private void textBox1_TextChanged(object sender, EventArgs e)
        {

        }

        private void t_ItemsBindingSource_PositionChanged(object sender, EventArgs e)
        {

        }

        private void frmItemNoWizard_Load(object sender, EventArgs e)
        {

        }
		string ss = @"ALTER TABLE dbo.T_Items
	DROP CONSTRAINT FK_T_Items_T_CATERY

ALTER TABLE dbo.T_CATEGORY SET (LOCK_ESCALATION = TABLE)




ALTER TABLE dbo.T_OfferDet
	DROP CONSTRAINT FK_T_OfferDet_T_Items

ALTER TABLE dbo.T_OfferQFree
	DROP CONSTRAINT FK_T_OfferQFree_T_Items

ALTER TABLE dbo.T_PatientCout
	DROP CONSTRAINT FK_T_PatientCout_T_Items

ALTER TABLE dbo.T_ItemSerial
	DROP CONSTRAINT FK_T_ItemSerial_T_Items

ALTER TABLE dbo.T_ItemDet
	DROP CONSTRAINT FK_T_ItemDet_T_Items

ALTER TABLE dbo.T_StoreMnd
	DROP CONSTRAINT FK_T_StoreMnd_T_Items

ALTER TABLE dbo.T_STKSQTY
	DROP CONSTRAINT FK_T_STKSQTY_T_Items

ALTER TABLE dbo.T_QTYEXP
	DROP CONSTRAINT FK_T_QTYEXP_T_Items

ALTER TABLE dbo.T_INVDET
	DROP CONSTRAINT FK_T_INVDET_T_Items

ALTER TABLE dbo.T_EditItemPrice
	DROP CONSTRAINT FK_T_EditItemPrice_T_Items

ALTER TABLE dbo.T_SINVDET
	DROP CONSTRAINT FK_T_SINVDET_T_Items

ALTER TABLE dbo.T_Items ADD CONSTRAINT
	FK_T_Items_T_CATERY FOREIGN KEY
	(
	ItmCat
	) REFERENCES dbo.T_CATEGORY
	(
	CAT_ID
	) ON UPDATE  CASCADE 
	 ON DELETE  NO ACTION 
	

ALTER TABLE dbo.T_Items SET (LOCK_ESCALATION = TABLE)




ALTER TABLE dbo.T_SINVDET ADD CONSTRAINT
	FK_T_SINVDET_T_Items FOREIGN KEY
	(
	SItmNo
	) REFERENCES dbo.T_Items
	(
	Itm_No
	) ON UPDATE  CASCADE 
	 ON DELETE  NO ACTION 
	

ALTER TABLE dbo.T_SINVDET SET (LOCK_ESCALATION = TABLE)




ALTER TABLE dbo.T_EditItemPrice ADD CONSTRAINT
	FK_T_EditItemPrice_T_Items FOREIGN KEY
	(
	ItmNo
	) REFERENCES dbo.T_Items
	(
	Itm_No
	) ON UPDATE  CASCADE 
	 ON DELETE  NO ACTION 
	

ALTER TABLE dbo.T_EditItemPrice SET (LOCK_ESCALATION = TABLE)




ALTER TABLE dbo.T_INVDET ADD CONSTRAINT
	FK_T_INVDET_T_Items FOREIGN KEY
	(
	ItmNo
	) REFERENCES dbo.T_Items
	(
	Itm_No
	) ON UPDATE  CASCADE 
	 ON DELETE  NO ACTION 
	

ALTER TABLE dbo.T_INVDET SET (LOCK_ESCALATION = TABLE)




ALTER TABLE dbo.T_QTYEXP ADD CONSTRAINT
	FK_T_QTYEXP_T_Items FOREIGN KEY
	(
	itmNo
	) REFERENCES dbo.T_Items
	(
	Itm_No
	) ON UPDATE  CASCADE 
	 ON DELETE  NO ACTION 
	

ALTER TABLE dbo.T_QTYEXP SET (LOCK_ESCALATION = TABLE)




ALTER TABLE dbo.T_STKSQTY ADD CONSTRAINT
	FK_T_STKSQTY_T_Items FOREIGN KEY
	(
	itmNo
	) REFERENCES dbo.T_Items
	(
	Itm_No
	) ON UPDATE  CASCADE 
	 ON DELETE  NO ACTION 
	

ALTER TABLE dbo.T_STKSQTY SET (LOCK_ESCALATION = TABLE)




ALTER TABLE dbo.T_StoreMnd ADD CONSTRAINT
	FK_T_StoreMnd_T_Items FOREIGN KEY
	(
	itmNo
	) REFERENCES dbo.T_Items
	(
	Itm_No
	) ON UPDATE  CASCADE 
	 ON DELETE  NO ACTION 
	

ALTER TABLE dbo.T_StoreMnd SET (LOCK_ESCALATION = TABLE)




ALTER TABLE dbo.T_ItemDet ADD CONSTRAINT
	FK_T_ItemDet_T_Items FOREIGN KEY
	(
	ItmNo
	) REFERENCES dbo.T_Items
	(
	Itm_No
	) ON UPDATE  CASCADE 
	 ON DELETE  NO ACTION 
	

ALTER TABLE dbo.T_ItemDet SET (LOCK_ESCALATION = TABLE)




ALTER TABLE dbo.T_ItemSerial ADD CONSTRAINT
	FK_T_ItemSerial_T_Items FOREIGN KEY
	(
	ItmNo
	) REFERENCES dbo.T_Items
	(
	Itm_No
	) ON UPDATE  CASCADE 
	 ON DELETE  NO ACTION 
	

ALTER TABLE dbo.T_ItemSerial SET (LOCK_ESCALATION = TABLE)




ALTER TABLE dbo.T_PatientCout ADD CONSTRAINT
	FK_T_PatientCout_T_Items FOREIGN KEY
	(
	ItmNo
	) REFERENCES dbo.T_Items
	(
	Itm_No
	) ON UPDATE  CASCADE 
	 ON DELETE  NO ACTION 
	

ALTER TABLE dbo.T_PatientCout SET (LOCK_ESCALATION = TABLE)




ALTER TABLE dbo.T_OfferQFree ADD CONSTRAINT
	FK_T_OfferQFree_T_Items FOREIGN KEY
	(
	OfferQFreeItmNo
	) REFERENCES dbo.T_Items
	(
	Itm_No
	) ON UPDATE  CASCADE 
	 ON DELETE  NO ACTION 
	

ALTER TABLE dbo.T_OfferQFree SET (LOCK_ESCALATION = TABLE)




ALTER TABLE dbo.T_OfferDet ADD CONSTRAINT
	FK_T_OfferDet_T_Items FOREIGN KEY
	(
	ItmNo
	) REFERENCES dbo.T_Items
	(
	Itm_No
	) ON UPDATE  CASCADE 
	 ON DELETE  NO ACTION 
	

ALTER TABLE dbo.T_OfferDet SET (LOCK_ESCALATION = TABLE)
"
;
		string fdo = @"
ALTER TABLE dbo.T_Items
	DROP CONSTRAINT FK_T_Items_T_CATERY

ALTER TABLE dbo.T_CATEGORY SET (LOCK_ESCALATION = TABLE)




ALTER TABLE dbo.T_SINVDET
	DROP CONSTRAINT FK_T_SINVDET_T_Items

ALTER TABLE dbo.T_EditItemPrice
	DROP CONSTRAINT FK_T_EditItemPrice_T_Items

ALTER TABLE dbo.T_INVDET
	DROP CONSTRAINT FK_T_INVDET_T_Items

ALTER TABLE dbo.T_QTYEXP
	DROP CONSTRAINT FK_T_QTYEXP_T_Items

ALTER TABLE dbo.T_STKSQTY
	DROP CONSTRAINT FK_T_STKSQTY_T_Items

ALTER TABLE dbo.T_StoreMnd
	DROP CONSTRAINT FK_T_StoreMnd_T_Items

ALTER TABLE dbo.T_ItemDet
	DROP CONSTRAINT FK_T_ItemDet_T_Items

ALTER TABLE dbo.T_ItemSerial
	DROP CONSTRAINT FK_T_ItemSerial_T_Items

ALTER TABLE dbo.T_PatientCout
	DROP CONSTRAINT FK_T_PatientCout_T_Items

ALTER TABLE dbo.T_OfferQFree
	DROP CONSTRAINT FK_T_OfferQFree_T_Items

ALTER TABLE dbo.T_OfferDet
	DROP CONSTRAINT FK_T_OfferDet_T_Items

ALTER TABLE dbo.T_Items ADD CONSTRAINT
	FK_T_Items_T_CATERY FOREIGN KEY
	(
	ItmCat
	) REFERENCES dbo.T_CATGOERY
	(
	CAT_ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	

ALTER TABLE dbo.T_Items SET (LOCK_ESCALATION = TABLE)




ALTER TABLE dbo.T_OfferDet ADD CONSTRAINT
	FK_T_OfferDet_T_Items FOREIGN KEY
	(
	ItmNo
	) REFERENCES dbo.T_Items
	(
	Itm_No
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	

ALTER TABLE dbo.T_OfferDet SET (LOCK_ESCALATION = TABLE)




ALTER TABLE dbo.T_OfferQFree ADD CONSTRAINT
	FK_T_OfferQFree_T_Items FOREIGN KEY
	(
	OfferQFreeItmNo
	) REFERENCES dbo.T_Items
	(
	Itm_No
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	

ALTER TABLE dbo.T_OfferQFree SET (LOCK_ESCALATION = TABLE)




ALTER TABLE dbo.T_PatientCout ADD CONSTRAINT
	FK_T_PatientCout_T_Items FOREIGN KEY
	(
	ItmNo
	) REFERENCES dbo.T_Items
	(
	Itm_No
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	

ALTER TABLE dbo.T_PatientCout SET (LOCK_ESCALATION = TABLE)




ALTER TABLE dbo.T_ItemSerial ADD CONSTRAINT
	FK_T_ItemSerial_T_Items FOREIGN KEY
	(
	ItmNo
	) REFERENCES dbo.T_Items
	(
	Itm_No
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	

ALTER TABLE dbo.T_ItemSerial SET (LOCK_ESCALATION = TABLE)




ALTER TABLE dbo.T_ItemDet ADD CONSTRAINT
	FK_T_ItemDet_T_Items FOREIGN KEY
	(
	ItmNo
	) REFERENCES dbo.T_Items
	(
	Itm_No
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	

ALTER TABLE dbo.T_ItemDet SET (LOCK_ESCALATION = TABLE)




ALTER TABLE dbo.T_StoreMnd ADD CONSTRAINT
	FK_T_StoreMnd_T_Items FOREIGN KEY
	(
	itmNo
	) REFERENCES dbo.T_Items
	(
	Itm_No
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	

ALTER TABLE dbo.T_StoreMnd SET (LOCK_ESCALATION = TABLE)




ALTER TABLE dbo.T_STKSQTY ADD CONSTRAINT
	FK_T_STKSQTY_T_Items FOREIGN KEY
	(
	itmNo
	) REFERENCES dbo.T_Items
	(
	Itm_No
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	

ALTER TABLE dbo.T_STKSQTY SET (LOCK_ESCALATION = TABLE)




ALTER TABLE dbo.T_QTYEXP ADD CONSTRAINT
	FK_T_QTYEXP_T_Items FOREIGN KEY
	(
	itmNo
	) REFERENCES dbo.T_Items
	(
	Itm_No
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	

ALTER TABLE dbo.T_QTYEXP SET (LOCK_ESCALATION = TABLE)




ALTER TABLE dbo.T_INVDET ADD CONSTRAINT
	FK_T_INVDET_T_Items FOREIGN KEY
	(
	ItmNo
	) REFERENCES dbo.T_Items
	(
	Itm_No
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	

ALTER TABLE dbo.T_INVDET SET (LOCK_ESCALATION = TABLE)




ALTER TABLE dbo.T_EditItemPrice ADD CONSTRAINT
	FK_T_EditItemPrice_T_Items FOREIGN KEY
	(
	ItmNo
	) REFERENCES dbo.T_Items
	(
	Itm_No
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	

ALTER TABLE dbo.T_EditItemPrice SET (LOCK_ESCALATION = TABLE)




ALTER TABLE dbo.T_SINVDET ADD CONSTRAINT
	FK_T_SINVDET_T_Items FOREIGN KEY
	(
	SItmNo
	) REFERENCES dbo.T_Items
	(
	Itm_No
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	

ALTER TABLE dbo.T_SINVDET SET (LOCK_ESCALATION = TABLE)

";
		string ff = @"
ALTER TABLE dbo.T_Items
	DROP CONSTRAINT FK_T_Items_T_CATEGORY

ALTER TABLE dbo.T_CATEGORY SET (LOCK_ESCALATION = TABLE)


ALTER TABLE dbo.T_OfferDet
	DROP CONSTRAINT FK_T_OfferDet_T_Items

ALTER TABLE dbo.T_OfferQFree
	DROP CONSTRAINT FK_T_OfferQFree_T_Items

ALTER TABLE dbo.T_PatientCout
	DROP CONSTRAINT FK_T_PatientCout_T_Items

ALTER TABLE dbo.T_ItemSerial
	DROP CONSTRAINT FK_T_ItemSerial_T_Items

ALTER TABLE dbo.T_ItemDet
	DROP CONSTRAINT FK_T_ItemDet_T_Items

ALTER TABLE dbo.T_StoreMnd
	DROP CONSTRAINT FK_T_StoreMnd_T_Items

ALTER TABLE dbo.T_STKSQTY
	DROP CONSTRAINT FK_T_STKSQTY_T_Items

ALTER TABLE dbo.T_QTYEXP
	DROP CONSTRAINT FK_T_QTYEXP_T_Items

ALTER TABLE dbo.T_INVDET
	DROP CONSTRAINT FK_T_INVDET_T_Items

ALTER TABLE dbo.T_EditItemPrice
	DROP CONSTRAINT FK_T_EditItemPrice_T_Items

ALTER TABLE dbo.T_SINVDET
	DROP CONSTRAINT FK_T_SINVDET_T_Items

ALTER TABLE dbo.T_Items ADD CONSTRAINT
	FK_T_Items_T_CATEGORY FOREIGN KEY
	(
	ItmCat
	) REFERENCES dbo.T_CATEGORY
	(
	CAT_ID
	) ON UPDATE  CASCADE 
	 ON DELETE  NO ACTION 
	

ALTER TABLE dbo.T_Items SET (LOCK_ESCALATION = TABLE)


ALTER TABLE dbo.T_SINVDET ADD CONSTRAINT
	FK_T_SINVDET_T_Items FOREIGN KEY
	(
	SItmNo
	) REFERENCES dbo.T_Items
	(
	Itm_No
	) ON UPDATE  CASCADE 
	 ON DELETE  NO ACTION 
	

ALTER TABLE dbo.T_SINVDET SET (LOCK_ESCALATION = TABLE)


ALTER TABLE dbo.T_EditItemPrice ADD CONSTRAINT
	FK_T_EditItemPrice_T_Items FOREIGN KEY
	(
	ItmNo
	) REFERENCES dbo.T_Items
	(
	Itm_No
	) ON UPDATE  CASCADE 
	 ON DELETE  NO ACTION 
	

ALTER TABLE dbo.T_EditItemPrice SET (LOCK_ESCALATION = TABLE)


ALTER TABLE dbo.T_INVDET ADD CONSTRAINT
	FK_T_INVDET_T_Items FOREIGN KEY
	(
	ItmNo
	) REFERENCES dbo.T_Items
	(
	Itm_No
	) ON UPDATE  CASCADE 
	 ON DELETE  NO ACTION 
	

ALTER TABLE dbo.T_INVDET SET (LOCK_ESCALATION = TABLE)



ALTER TABLE dbo.T_QTYEXP ADD CONSTRAINT
	FK_T_QTYEXP_T_Items FOREIGN KEY
	(
	itmNo
	) REFERENCES dbo.T_Items
	(
	Itm_No
	) ON UPDATE  CASCADE 
	 ON DELETE  NO ACTION 
	

ALTER TABLE dbo.T_QTYEXP SET (LOCK_ESCALATION = TABLE)




ALTER TABLE dbo.T_STKSQTY ADD CONSTRAINT
	FK_T_STKSQTY_T_Items FOREIGN KEY
	(
	itmNo
	) REFERENCES dbo.T_Items
	(
	Itm_No
	) ON UPDATE  CASCADE 
	 ON DELETE  NO ACTION 
	

ALTER TABLE dbo.T_STKSQTY SET (LOCK_ESCALATION = TABLE)




ALTER TABLE dbo.T_StoreMnd ADD CONSTRAINT
	FK_T_StoreMnd_T_Items FOREIGN KEY
	(
	itmNo
	) REFERENCES dbo.T_Items
	(
	Itm_No
	) ON UPDATE  CASCADE 
	 ON DELETE  NO ACTION 
	

ALTER TABLE dbo.T_StoreMnd SET (LOCK_ESCALATION = TABLE)




ALTER TABLE dbo.T_ItemDet ADD CONSTRAINT
	FK_T_ItemDet_T_Items FOREIGN KEY
	(
	ItmNo
	) REFERENCES dbo.T_Items
	(
	Itm_No
	) ON UPDATE  CASCADE 
	 ON DELETE  NO ACTION 
	

ALTER TABLE dbo.T_ItemDet SET (LOCK_ESCALATION = TABLE)




ALTER TABLE dbo.T_ItemSerial ADD CONSTRAINT
	FK_T_ItemSerial_T_Items FOREIGN KEY
	(
	ItmNo
	) REFERENCES dbo.T_Items
	(
	Itm_No
	) ON UPDATE  CASCADE 
	 ON DELETE  NO ACTION 
	

ALTER TABLE dbo.T_ItemSerial SET (LOCK_ESCALATION = TABLE)




ALTER TABLE dbo.T_PatientCout ADD CONSTRAINT
	FK_T_PatientCout_T_Items FOREIGN KEY
	(
	ItmNo
	) REFERENCES dbo.T_Items
	(
	Itm_No
	) ON UPDATE  CASCADE 
	 ON DELETE  NO ACTION 
	

ALTER TABLE dbo.T_PatientCout SET (LOCK_ESCALATION = TABLE)




ALTER TABLE dbo.T_OfferQFree ADD CONSTRAINT
	FK_T_OfferQFree_T_Items FOREIGN KEY
	(
	OfferQFreeItmNo
	) REFERENCES dbo.T_Items
	(
	Itm_No
	) ON UPDATE  CASCADE 
	 ON DELETE  NO ACTION 
	

ALTER TABLE dbo.T_OfferQFree SET (LOCK_ESCALATION = TABLE)




ALTER TABLE dbo.T_OfferDet ADD CONSTRAINT
	FK_T_OfferDet_T_Items FOREIGN KEY
	(
	ItmNo
	) REFERENCES dbo.T_Items
	(
	Itm_No
	) ON UPDATE  CASCADE 
	 ON DELETE  NO ACTION 
	

ALTER TABLE dbo.T_OfferDet SET (LOCK_ESCALATION = TABLE)
";string ssav = @"ALTER TABLE dbo.T_Items
	DROP CONSTRAINT FK_T_Items_T_CATERY

ALTER TABLE dbo.T_CATEGORY SET (LOCK_ESCALATION = TABLE)




ALTER TABLE dbo.T_OfferDet
	DROP CONSTRAINT FK_T_OfferDet_T_Items

ALTER TABLE dbo.T_OfferQFree
	DROP CONSTRAINT FK_T_OfferQFree_T_Items

ALTER TABLE dbo.T_PatientCout
	DROP CONSTRAINT FK_T_PatientCout_T_Items

ALTER TABLE dbo.T_ItemSerial
	DROP CONSTRAINT FK_T_ItemSerial_T_Items

ALTER TABLE dbo.T_ItemDet
	DROP CONSTRAINT FK_T_ItemDet_T_Items

ALTER TABLE dbo.T_StoreMnd
	DROP CONSTRAINT FK_T_StoreMnd_T_Items

ALTER TABLE dbo.T_STKSQTY
	DROP CONSTRAINT FK_T_STKSQTY_T_Items

ALTER TABLE dbo.T_QTYEXP
	DROP CONSTRAINT FK_T_QTYEXP_T_Items

ALTER TABLE dbo.T_INVDET
	DROP CONSTRAINT FK_T_INVDET_T_Items

ALTER TABLE dbo.T_EditItemPrice
	DROP CONSTRAINT FK_T_EditItemPrice_T_Items

ALTER TABLE dbo.T_SINVDET
	DROP CONSTRAINT FK_T_SINVDET_T_Items

ALTER TABLE dbo.T_Items ADD CONSTRAINT
	FK_T_Items_T_CATERY FOREIGN KEY
	(
	ItmCat
	) REFERENCES dbo.T_CATEGORY
	(
	CAT_ID
	) ON UPDATE NO ACTION 
	 ON DELETE  NO ACTION 
	

ALTER TABLE dbo.T_Items SET (LOCK_ESCALATION = TABLE)




ALTER TABLE dbo.T_SINVDET ADD CONSTRAINT
	FK_T_SINVDET_T_Items FOREIGN KEY
	(
	SItmNo
	) REFERENCES dbo.T_Items
	(
	Itm_No
	) ON UPDATE NO ACTION 
	 ON DELETE  NO ACTION 
	

ALTER TABLE dbo.T_SINVDET SET (LOCK_ESCALATION = TABLE)




ALTER TABLE dbo.T_EditItemPrice ADD CONSTRAINT
	FK_T_EditItemPrice_T_Items FOREIGN KEY
	(
	ItmNo
	) REFERENCES dbo.T_Items
	(
	Itm_No
	) ON UPDATE NO ACTION 
	 ON DELETE  NO ACTION 
	

ALTER TABLE dbo.T_EditItemPrice SET (LOCK_ESCALATION = TABLE)




ALTER TABLE dbo.T_INVDET ADD CONSTRAINT
	FK_T_INVDET_T_Items FOREIGN KEY
	(
	ItmNo
	) REFERENCES dbo.T_Items
	(
	Itm_No
	) ON UPDATE NO ACTION 
	 ON DELETE  NO ACTION 
	

ALTER TABLE dbo.T_INVDET SET (LOCK_ESCALATION = TABLE)




ALTER TABLE dbo.T_QTYEXP ADD CONSTRAINT
	FK_T_QTYEXP_T_Items FOREIGN KEY
	(
	itmNo
	) REFERENCES dbo.T_Items
	(
	Itm_No
	) ON UPDATE NO ACTION 
	 ON DELETE  NO ACTION 
	

ALTER TABLE dbo.T_QTYEXP SET (LOCK_ESCALATION = TABLE)




ALTER TABLE dbo.T_STKSQTY ADD CONSTRAINT
	FK_T_STKSQTY_T_Items FOREIGN KEY
	(
	itmNo
	) REFERENCES dbo.T_Items
	(
	Itm_No
	) ON UPDATE NO ACTION 
	 ON DELETE  NO ACTION 
	

ALTER TABLE dbo.T_STKSQTY SET (LOCK_ESCALATION = TABLE)




ALTER TABLE dbo.T_StoreMnd ADD CONSTRAINT
	FK_T_StoreMnd_T_Items FOREIGN KEY
	(
	itmNo
	) REFERENCES dbo.T_Items
	(
	Itm_No
	) ON UPDATE NO ACTION 
	 ON DELETE  NO ACTION 
	

ALTER TABLE dbo.T_StoreMnd SET (LOCK_ESCALATION = TABLE)




ALTER TABLE dbo.T_ItemDet ADD CONSTRAINT
	FK_T_ItemDet_T_Items FOREIGN KEY
	(
	ItmNo
	) REFERENCES dbo.T_Items
	(
	Itm_No
	) ON UPDATE NO ACTION 
	 ON DELETE  NO ACTION 
	

ALTER TABLE dbo.T_ItemDet SET (LOCK_ESCALATION = TABLE)




ALTER TABLE dbo.T_ItemSerial ADD CONSTRAINT
	FK_T_ItemSerial_T_Items FOREIGN KEY
	(
	ItmNo
	) REFERENCES dbo.T_Items
	(
	Itm_No
	) ON UPDATE NO ACTION 
	 ON DELETE  NO ACTION 
	

ALTER TABLE dbo.T_ItemSerial SET (LOCK_ESCALATION = TABLE)




ALTER TABLE dbo.T_PatientCout ADD CONSTRAINT
	FK_T_PatientCout_T_Items FOREIGN KEY
	(
	ItmNo
	) REFERENCES dbo.T_Items
	(
	Itm_No
	) ON UPDATE NO ACTION 
	 ON DELETE  NO ACTION 
	

ALTER TABLE dbo.T_PatientCout SET (LOCK_ESCALATION = TABLE)




ALTER TABLE dbo.T_OfferQFree ADD CONSTRAINT
	FK_T_OfferQFree_T_Items FOREIGN KEY
	(
	OfferQFreeItmNo
	) REFERENCES dbo.T_Items
	(
	Itm_No
	) ON UPDATE NO ACTION 
	 ON DELETE  NO ACTION 
	

ALTER TABLE dbo.T_OfferQFree SET (LOCK_ESCALATION = TABLE)




ALTER TABLE dbo.T_OfferDet ADD CONSTRAINT
	FK_T_OfferDet_T_Items FOREIGN KEY
	(
	ItmNo
	) REFERENCES dbo.T_Items
	(
	Itm_No
	) ON UPDATE NO ACTION 
	 ON DELETE  NO ACTION 
	

ALTER TABLE dbo.T_OfferDet SET (LOCK_ESCALATION = TABLE)
";
		private void button2_Click(object sender, EventArgs e)
        {
            t_ItemsBindingSource.EndEdit();
			int count = 1;
			{
				
				{
					try
					{
					 
						SqlConnection con = new SqlConnection(VarGeneral.BranchCS);
						con.Open();
						SqlCommand c = new SqlCommand(ss, con);
						c.ExecuteNonQuery();
						foreach (T_Item k in db.T_Items)
						{
							c = new SqlCommand("update T_Items set Itm_No=Itm_No+'3548787' where Itm_ID='" + k.Itm_ID.ToString() + "'", con);

							//c = new SqlCommand("update T_Items set Itm_No='" + k.Itm_No.ToString() + "' where Itm_ID='"+k.Itm_ID.ToString()+"'", con);
							c.ExecuteNonQuery();


						}
					for(int i=0;i<t_ItemsBindingSource.Count;i++)
						{
							t_ItemsBindingSource.Position = i;
							T_Item k = t_ItemsBindingSource.Current as T_Item;
						//	c = new SqlCommand("update T_Items set Itm_No=Item_No+'3' where Itm_ID='" + k.Itm_ID.ToString() + "'", con);

							c = new SqlCommand("update T_Items set Itm_No='" + count + "' where Itm_ID='" + k.Itm_ID.ToString() + "'", con);
							count++;
							c.ExecuteNonQuery();
							t_ItemsBindingSource.MoveNext();


						}
						c = new SqlCommand(ssav, con);
						c.ExecuteNonQuery();
					}
					catch (Exception ex)
					{
						 
					}
				}
			}
			
		
          
		}

		private void frmItemNoWizard_FormClosing(object sender, FormClosingEventArgs e)
        {
            try
            {
                db.SubmitChanges();
            }
            catch(Exception ex) { }
        }
    }
}
