using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;

namespace InvAcc.Forms.Eqr_Version.New.Rep
{
    public partial class XFrmEqarRepQuery : DevExpress.XtraEditors.XtraForm
    {
        public XFrmEqarRepQuery()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            t_EqarsDatasBindingSource.DataSource = new ProShared.Stock_Data.Stock_DataDataContext().T_EqarsDatas;
            // This line of code is generated by Data Source Configuration Wizard
            t_EqarTypsBindingSource.DataSource = new ProShared.Stock_Data.Stock_DataDataContext().T_EqarTyps;
            // This line of code is generated by Data Source Configuration Wizard
            t_EqarNaturalsBindingSource.DataSource = new ProShared.Stock_Data.Stock_DataDataContext().T_EqarNaturals;
            // This line of code is generated by Data Source Configuration Wizard
            t_AinTypsBindingSource.DataSource = new ProShared.Stock_Data.Stock_DataDataContext().T_AinTyps;
            // This line of code is generated by Data Source Configuration Wizard
            t_AinNaturalsBindingSource.DataSource = new ProShared.Stock_Data.Stock_DataDataContext().T_AinNaturals;
            // This line of code is generated by Data Source Configuration Wizard
            t_CitiesBindingSource.DataSource = new ProShared.Stock_Data.Stock_DataDataContext().T_Cities;
            // This line of code is generated by Data Source Configuration Wizard
            t_OwnersBindingSource.DataSource = new ProShared.Stock_Data.Stock_DataDataContext().T_Owners;
        }

        private void XFrmEqarRepQuery_Load(object sender, EventArgs e)
        {

        }

        private void txtEqarNo_ProcessNewValue(object sender, DevExpress.XtraEditors.Controls.ProcessNewValueEventArgs e)
        {

        }

        private void CmbEyeTyp_ProcessNewValue(object sender, DevExpress.XtraEditors.Controls.ProcessNewValueEventArgs e)
        {
            if (MessageBox.Show("القيمه المدخلة لا توجد هل تريد اضافتها ", "اضافة جديدة", MessageBoxButtons.YesNo) == DialogResult.Yes)
            {

                XFrmAinTyp frm = new XFrmAinTyp();
                frm.ShowDialog();
            }

        }
    }
}