//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvAcc.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\PROSOFT")]
        public string ServerName {
            get {
                return ((string)(this["ServerName"]));
            }
            set {
                this["ServerName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sa")]
        public string SUser {
            get {
                return ((string)(this["SUser"]));
            }
            set {
                this["SUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PROSOFT_default")]
        public string DefaultDDatabaseName {
            get {
                return ((string)(this["DefaultDDatabaseName"]));
            }
            set {
                this["DefaultDDatabaseName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DBPROSOFT_default")]
        public string DefaultUDatabaseName {
            get {
                return ((string)(this["DefaultUDatabaseName"]));
            }
            set {
                this["DefaultUDatabaseName"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\prosoft;Initial Catalog=DBPROSOFT_default;Persist Security Info=Tru" +
            "e;User ID=sa;Password=\"Prosoft@prosoft&ma89\"")]
        public string DBPROSOFT_defaultConnectionString {
            get {
                return ((string)(this["DBPROSOFT_defaultConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int SSSTyp {
            get {
                return ((int)(this["SSSTyp"]));
            }
            set {
                this["SSSTyp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string SSSLevel {
            get {
                return ((string)(this["SSSLevel"]));
            }
            set {
                this["SSSLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("G.")]
        public string runTyp {
            get {
                return ((string)(this["runTyp"]));
            }
            set {
                this["runTyp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SQL")]
        public string Mode {
            get {
                return ((string)(this["Mode"]));
            }
            set {
                this["Mode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MSSQL10_50.PROSOFT")]
        public string SqlFolder {
            get {
                return ((string)(this["SqlFolder"]));
            }
            set {
                this["SqlFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Password=Prosoft@prosoft&ma89;Persist Security Info=True;")]
        public string pscomp {
            get {
                return ((string)(this["pscomp"]));
            }
            set {
                this["pscomp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Software\\PRS AND PR Settings\\MrdSoft\\\\Register")]
        public string Registerks {
            get {
                return ((string)(this["Registerks"]));
            }
            set {
                this["Registerks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Software\\PRS AND PR Settings\\WinSystemOperation")]
        public string WinOperation {
            get {
                return ((string)(this["WinOperation"]));
            }
            set {
                this["WinOperation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Software\\MrdHrdw\\ItIntel")]
        public string Intelk {
            get {
                return ((string)(this["Intelk"]));
            }
            set {
                this["Intelk"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Prog_MessageToShow {
            get {
                return ((string)(this["Prog_MessageToShow"]));
            }
            set {
                this["Prog_MessageToShow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Prog_StartCommandToExecute {
            get {
                return ((string)(this["Prog_StartCommandToExecute"]));
            }
            set {
                this["Prog_StartCommandToExecute"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Prog_AutoCommandToExecute {
            get {
                return ((string)(this["Prog_AutoCommandToExecute"]));
            }
            set {
                this["Prog_AutoCommandToExecute"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\prosoft;Initial Catalog=MRDClientsDB;Persist Security Info=True;Use" +
            "r ID=sa;Password=Prosoft@prosoft&ma89")]
        public string MRDClientsDBConnectionString {
            get {
                return ((string)(this["MRDClientsDBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=EC2AMAZ-SI4ASSC\\PROSOFT;Initial Catalog=PROSOFT_default_1;Persist Sec" +
            "urity Info=True;User ID=sa;Password=\"Prosoft@prosoft&amp;ma89\"")]
        public string PROSOFT_default_1ConnectionStringh {
            get {
                return ((string)(this["PROSOFT_default_1ConnectionStringh"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"Prosoft@prosoft&ma89\"")]
        public string SPassword {
            get {
                return ((string)(this["SPassword"]));
            }
            set {
                this["SPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string B3 {
            get {
                return ((string)(this["B3"]));
            }
            set {
                this["B3"] = value;
            }
        }
    }
}
