using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using ProShared.Stock_Data;

namespace InvAcc.Forms.Eqr_Version.New
{
    public partial class XFrmTenantContract :BaseForm
    {
        public XFrmTenantContract()
        {
            InitializeComponent();
            dbInstance = new Stock_DataDataContext();
            // This line of code is generated by Data Source Configuration Wizard
            t_TenantContractsBindingSource.DataSource = db.T_TenantContracts;
            ubar1.BindingSource = t_TenantContractsBindingSource;
            // This line of code is generated by Data Source Configuration Wizard
            t_TenantsBindingSource.DataSource = db.T_Tenants;
            // This line of code is generated by Data Source Configuration Wizard
            t_AinTypsBindingSource.DataSource = db.T_AinTyps;
            // This line of code is generated by Data Source Configuration Wizard
            t_EqarsDatasBindingSource.DataSource = db.T_EqarsDatas;
            // This line of code is generated by Data Source Configuration Wizard
            t_AinsDatasBindingSource.DataSource = new ProShared.Stock_Data.Stock_DataDataContext().T_AinsDatas;
        }

        private void XFrmTenantContract_Load(object sender, EventArgs e)
        {

        }

        private void t_TenantContractsBindingSource_AddingNew(object sender, AddingNewEventArgs e)
        {

            T_TenantContract et = new T_TenantContract();
            et.ContractID = db.MaxAlarmTenantNo;

            et.ContractNo = db.MaxAlarmTenantNo;
            e.NewObject = et;
            tenant_IDTextEdit.Focus();
        }

        private void ContractStartTextEdit_EditValueChanged(object sender, EventArgs e)
        {
            dateEdit1_EditValueChanged(sender, e);

        }

        private void ContractEndTextEdit_EditValueChanged(object sender, EventArgs e)
        {
            dateEdit1_EditValueChanged(sender, e);
        }

        private void ContractStartTextEdit_ButtonPressed(object sender, DevExpress.XtraEditors.Controls.ButtonPressedEventArgs e)
        {

        }

        private void ContractEndTextEdit_Layout(object sender, LayoutEventArgs e)
        {

        }

        private void ContractEndTextEdit_Modified(object sender, EventArgs e)
        {

        }

        private void ubar1_Button_Save_Click(object sender, Controls.BarEvArg e)
        {
            if (ActiveControl.GetType() == typeof(DateEdit))
                this.Focus();
        }
    }
}