using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using ProShared.Stock_Data;
using ProShared.GeneralM;

namespace InvAcc.Forms.Eqr_Version.New
{
    public partial class XFrmTenantPayment :BaseForm
    {
        public T_User Permmission
        {
            get
            {
                return permission;
            }
            set
            {
                if (value != null && value.UsrNo != string.Empty)
                {
                    permission = value;
                }
            }
        }

        public XFrmTenantPayment()
        {
            InitializeComponent();
            dbInstance = new Stock_DataDataContext();
            // This line of code is generated by Data Source Configuration Wizard
            t_TenantContractsBindingSource.DataSource =db.T_TenantContracts;
            // This line of code is generated by Data Source Configuration Wizard
            t_TenantsBindingSource.DataSource =db.T_Tenants;
            // This line of code is generated by Data Source Configuration Wizard
            t_TenantPaymentsBindingSource.DataSource =db.T_TenantPayments;
            // This line of code is generated by Data Source Configuration Wizard
            t_EqarsDatasBindingSource.DataSource =db.T_EqarsDatas;
            // This line of code is generated by Data Source Configuration Wizard
            t_AinTypsBindingSource.DataSource =db.T_AinTyps;
        }

        private void XXFrmTenantPayment_Load(object sender, EventArgs e)
        {
            Permmission = dbc.Get_PermissionID(VarGeneral.UserID);
            if (columns_Names_visible.Count == 0)
            {
                columns_Names_visible.Add("PaymentNo", new ColumnDictinary("الرقم ", " No", ifDefault: true, string.Empty));
            }

        }

        private void t_TenantContractsBindingSource_AddingNew(object sender, AddingNewEventArgs e)
        {
            T_TenantContract et = new T_TenantContract();
            et.ContractID = db.MaxTenantContractDataNo;
            et.ContractNo = db.MaxTenantContractDataNo;
            e.NewObject = et;
            tenant_IDTextEdit.Focus();

        }

        private void ubar1_Button_Search_Click(object sender, Controls.BarEvArg e)
        {

        }

        private void ContractStartTextEdit_EditValueChanged(object sender, EventArgs e)
        {
            dateEdit1_EditValueChanged(sender, e);
        }
    }
}