using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using ProShared.Stock_Data;
using InvAcc.Controls;
using ProShared.GeneralM;

namespace InvAcc.Forms.Eqr_Version.New
{
    public partial class XFrmEqarTyp : BaseForm
    {
        public XFrmEqarTyp()
        {
            InitializeComponent();
            dbInstance = new Stock_DataDataContext();
            // This line of code is generated by Data Source Configuration Wizard
            t_EqarTypsBindingSource.DataSource = db.T_EqarTyps;
        }
        private void ubar1_Button_Search_Click(object sender, BarEvArg e)
        {
            FrmSearch frm = new FrmSearch();
            frm.Tag = LangArEn;
            ICollection<KeyValuePair<string, ColumnDictinary>> animalsAsCollection = columns_Names_visible;
            foreach (KeyValuePair<string, ColumnDictinary> kvp in animalsAsCollection)
            {
                frm.columns_Names_visible.Add(kvp.Key, new FrmSearch.SColumnDictinary(kvp.Value.AText, kvp.Value.EText, kvp.Value.IfDefault, string.Empty));
            }
            VarGeneral.SFrmTyp = "T_EqarTyp";
            frm.TopMost = true;
            frm.ShowDialog();
            if (frm.SerachNo != string.Empty)
            {
                var q = (from i in db.T_EqarTyps where i.EqarTyp_No == int.Parse(frm.Serach_No) select i).FirstOrDefault();
                int index = db.T_EqarTyps.ToBindingList<T_EqarTyp>().IndexOf(q);
                if (index != -1)
                {

                    ubar1.Binding.Position = index;
                }
            }

        }
        public T_User Permmission
        {
            get
            {
                return permission;
            }
            set
            {
                if (value != null && value.UsrNo != string.Empty)
                {
                    permission = value;
                    if (!VarGeneral.TString.ChkStatShow(value.Eqar_FilStr, 9))
                    {
                        IfAdd = false;
                    }
                    else
                    {
                        IfAdd = true;
                    }
                    if (!VarGeneral.TString.ChkStatShow(value.Eqar_FilStr, 10))
                    {
                        CanEdit = false;
                    }
                    else
                    {
                        CanEdit = true;
                    }
                    if (!VarGeneral.TString.ChkStatShow(value.Eqar_FilStr, 11))
                    {
                        IfDelete = false;
                    }
                    else
                    {
                        IfDelete = true;
                    }
                }
            }
        }


        private void XFrmEqarTyp_Load(object sender, EventArgs e)
        {
            Permmission = dbc.Get_PermissionID(VarGeneral.UserID);
            if (columns_Names_visible.Count == 0)
            {
                columns_Names_visible.Add("EqarTyp_No", new ColumnDictinary("الرقـــــم", "No", ifDefault: true, string.Empty));
                columns_Names_visible.Add("NameA", new ColumnDictinary("الاسم عربي", "Arabic Name", ifDefault: true, string.Empty));
                columns_Names_visible.Add("NameE", new ColumnDictinary("الاسم الانجليزي", "English Name", ifDefault: true, string.Empty));
            }

        }

        private void t_EqarTypsBindingSource_AddingNew(object sender, AddingNewEventArgs e)
        {
            T_EqarTyp et = new T_EqarTyp();
            et.EqarTyp_ID = Guid.NewGuid().ToString();
            et.EqarTyp_No = db.MaxEqarTypNo;
            e.NewObject = et;
        }
    }
}