using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using ProShared.Stock_Data;
using ProShared.GeneralM;
using InvAcc.Controls;

namespace InvAcc.Forms.Eqr_Version.New
{
    public partial class XFrmNation :BaseForm
    {
        public XFrmNation()
        {
            InitializeComponent();
            dbInstance = new Stock_DataDataContext();
            // This line of code is generated by Data Source Configuration Wizard
            t_NationalitiesBindingSource.DataSource = db.T_Nationalities;
        }

        private void XFrmNation_Load(object sender, EventArgs e)
        {
            Permmission = dbc.Get_PermissionID(VarGeneral.UserID);
            if (columns_Names_visible.Count == 0)
            {
                columns_Names_visible.Add("Nation_No", new ColumnDictinary("رقم الجنسية", "Nation No", ifDefault: true, ""));
                columns_Names_visible.Add("NameA", new ColumnDictinary("الاسم عربي", "Arabic Name", ifDefault: true, ""));
                columns_Names_visible.Add("NameE", new ColumnDictinary("الاسم الانجليزي", "English Name", ifDefault: true, ""));
                columns_Names_visible.Add("SalSubtract", new ColumnDictinary("يخصم من الراتب", "from Salary", ifDefault: false, ""));
                columns_Names_visible.Add("CompPaying", new ColumnDictinary("مستحق من الشركة", "from Company", ifDefault: false, ""));
                columns_Names_visible.Add("Note", new ColumnDictinary("الملاحظات", "Note", ifDefault: false, ""));
            }
        }

        private void t_NationalitiesBindingSource_AddingNew(object sender, AddingNewEventArgs e)
        {

            T_Nationality et = new T_Nationality();
            et.Nation_ID = db.MaxAlarmTenantNo.ToString();

            et.Nation_No = db.MaxAlarmTenantNo;
            e.NewObject = et;
        }
        public T_User Permmission
        {
            get
            {
                return permission;
            }
            set
            {
                if (value == null || !(value.UsrNo != ""))
                {
                    return;
                }
                permission = value;
                if (VarGeneral.SSSLev == "D" || VarGeneral.SSSLev == "E")
                {
                    if (!VarGeneral.TString.ChkStatShow(value.Emp_FilStr, 25))
                    {
                        IfAdd = false;
                    }
                    else
                    {
                        IfAdd = true;
                    }
                    if (!VarGeneral.TString.ChkStatShow(value.Emp_FilStr, 26))
                    {
                        CanEdit = false;
                    }
                    else
                    {
                        CanEdit = true;
                    }
                    if (!VarGeneral.TString.ChkStatShow(value.Emp_FilStr, 27))
                    {
                        IfDelete = false;
                    }
                    else
                    {
                        IfDelete = true;
                    }
                }
                else
                {
                    if (!VarGeneral.TString.ChkStatShow(value.RepAcc1, 13))
                    {
                        IfAdd = false;
                    }
                    else
                    {
                        IfAdd = true;
                    }
                    if (!VarGeneral.TString.ChkStatShow(value.RepAcc1, 14))
                    {
                        CanEdit = false;
                    }
                    else
                    {
                        CanEdit = true;
                    }
                    if (!VarGeneral.TString.ChkStatShow(value.RepAcc1, 15))
                    {
                        IfDelete = false;
                    }
                    else
                    {
                        IfDelete = true;
                    }
                }
            }
        }


        private void ubar1_Button_Search_Click(object sender, Controls.BarEvArg e)
        {
            FrmSearch frm = new FrmSearch();
            frm.Tag = LangArEn;
            ICollection<KeyValuePair<string, ColumnDictinary>> animalsAsCollection = columns_Names_visible;
            foreach (KeyValuePair<string, ColumnDictinary> kvp in animalsAsCollection)
            {
                frm.columns_Names_visible.Add(kvp.Key, new FrmSearch.SColumnDictinary(kvp.Value.AText, kvp.Value.EText, kvp.Value.IfDefault, ""));
            }
            VarGeneral.SFrmTyp = "T_Nationality";
            frm.TopMost = true;
            frm.ShowDialog();
            if (frm.SerachNo != "")
            {
                var q = (from i in db.T_Nationalities where i.Nation_No == int.Parse(frm.Serach_No) select i).FirstOrDefault();
                int index = db.T_Nationalities.ToBindingList<T_Nationality>().IndexOf(q);
                if (index != -1)
                {

                    ubar1.Binding.Position = index;
                }
            }


        }

        private void Nation_NoTextEdit_EditValueChanged(object sender, EventArgs e)
        {

        }
    }
}