using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using ProShared.Stock_Data;
using ProShared.GeneralM;

namespace InvAcc.Forms.Eqr_Version.New
{
    public partial class XFrmAlarmTenant :BaseForm
    {
        public T_User Permmission
        {
            get
            {
                return permission;
            }
            set
            {
                if (value != null && value.UsrNo != "")
                {
                    permission = value;
                    if (!VarGeneral.TString.ChkStatShow(value.Eqar_TenantStr, 13))
                    {
                        IfAdd = false;
                    }
                    else
                    {
                        IfAdd = true;
                    }
                    if (!VarGeneral.TString.ChkStatShow(value.Eqar_TenantStr, 14))
                    {
                        CanEdit = false;
                    }
                    else
                    {
                        CanEdit = true;
                    }
                    if (!VarGeneral.TString.ChkStatShow(value.Eqar_TenantStr, 15))
                    {
                        IfDelete = false;
                    }
                    else
                    {
                        IfDelete = true;
                    }
                }
            }
        }

        public XFrmAlarmTenant()
        {
            InitializeComponent();
            dbInstance = new Stock_DataDataContext();
            // This line of code is generated by Data Source Configuration Wizard
            t_AlarmTenantsBindingSource.DataSource =db.T_AlarmTenants;
            // This line of code is generated by Data Source Configuration Wizard
            t_TenantsBindingSource.DataSource = db.T_Tenants;
        }

        private void XFrmAlarmTenant_Load(object sender, EventArgs e)
        {
            Permmission = dbc.Get_PermissionID(VarGeneral.UserID);
            if (columns_Names_visible.Count == 0)
            {
                columns_Names_visible.Add("AlarmTenantNo", new ColumnDictinary("الرقم ", " No", ifDefault: true, ""));
                columns_Names_visible.Add("AlarmSubject", new ColumnDictinary("موضوع الإشعار", "Subject", ifDefault: true, ""));
                columns_Names_visible.Add("AlarmAdmin", new ColumnDictinary("المســؤول", "Administrator", ifDefault: true, ""));
                columns_Names_visible.Add("AlarmDateG", new ColumnDictinary("التاريخ الميلادي", "Date Ger", ifDefault: true, ""));
                columns_Names_visible.Add("AlarmDateH", new ColumnDictinary("التاريخ الهجري", "Date Hijri", ifDefault: true, ""));
            }
            else
            { 
            }
        }

        private void t_AlarmTenantsBindingSource_AddingNew(object sender, AddingNewEventArgs e)
        {
            T_AlarmTenant et = new T_AlarmTenant();
            et.AlarmTenantID = db.MaxAlarmTenantNo;

            et.AlarmTenantNo = db.MaxAlarmTenantNo;
            e.NewObject = et;
            tenant_IDTextEdit.Focus();
        }

        private void AlarmDateGTextEdit_EditValueChanged(object sender, EventArgs e)
        {

        }

        private void ubar1_Button_Close_Click(object sender, Controls.BarEvArg e)
        {
            e.db = db;

        }

        private void ubar1_Button_Save_Click(object sender, Controls.BarEvArg e)
        {
            e.db = db;
        }

        private void ubar1_Button_Delete_Click(object sender, Controls.BarEvArg e)
        {
            e.db = db;
        }

        private void ubar1_HelpRequested(object sender, HelpEventArgs hlpevent)
        {

        }

        private void ubar1_Button_Search_Click(object sender, Controls.BarEvArg e)
        {
            FrmSearch frm = new FrmSearch();
            frm.Tag = LangArEn;
            columns_Names_visible.Clear();
            columns_Names_visible.Add("AlarmTenantNo", new ColumnDictinary("الرقم ", " No", ifDefault: true, ""));
            columns_Names_visible.Add("NameA", new ColumnDictinary("إسم المستأجر عربي", "Arabic Name", ifDefault: true, ""));
            columns_Names_visible.Add("NameE", new ColumnDictinary("إسم المستأجر إنجليزي", "English Name", ifDefault: true, ""));
            columns_Names_visible.Add("AlarmSubject", new ColumnDictinary("موضوع الإشعار", "Subject", ifDefault: true, ""));
            columns_Names_visible.Add("AlarmAdmin", new ColumnDictinary("المســؤول", "Administrator", ifDefault: false, ""));
            ICollection<KeyValuePair<string, ColumnDictinary>> animalsAsCollection = columns_Names_visible;
            foreach (KeyValuePair<string, ColumnDictinary> kvp in animalsAsCollection)
            {
                frm.columns_Names_visible.Add(kvp.Key, new FrmSearch.SColumnDictinary(kvp.Value.AText, kvp.Value.EText, kvp.Value.IfDefault, ""));
            }
            VarGeneral.SFrmTyp = "T_AlarmTenant";
            frm.TopMost = true;
            frm.ShowDialog();
            if (frm.SerachNo != "")
            {
                AlarmTenantNoTextEdit.EditValue = frm.SerachNo.ToString();
            }

        }

        private void AlarmDateHTextEdit_EditValueChanged_1(object sender, EventArgs e)
        {
            dateEdit1_EditValueChanged(sender, e);
        }
    }
}