using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using ProShared.Stock_Data;
using InvAcc.Controls;
using ProShared.GeneralM;

namespace InvAcc.Forms.Eqr_Version.New
{
    public partial class XFrmEqarSale : BaseForm
    {
        public XFrmEqarSale()
        {
            InitializeComponent();
            dbInstance = new Stock_DataDataContext();
            // This line of code is generated by Data Source Configuration Wizard
            t_EqarSalesBindingSource.DataSource =db.T_EqarSales;
            // This line of code is generated by Data Source Configuration Wizard
            t_EqarsDatasBindingSource.DataSource = db.T_EqarsDatas;
            // This line of code is generated by Data Source Configuration Wizard
            t_AinTypsBindingSource.DataSource = db.T_AinTyps;
        }
        public T_User Permmission
        {
            get
            {
                return permission;
            }
            set
            {
                if (value != null && value.UsrNo != "")
                {
                    permission = value;
                    if (!VarGeneral.TString.ChkStatShow(value.Eqar_FilStr, 21))
                    {
                        IfAdd = false;
                    }
                    else
                    {
                        IfAdd = true;
                    }
                    if (!VarGeneral.TString.ChkStatShow(value.Eqar_FilStr, 22))
                    {
                        CanEdit = false;
                    }
                    else
                    {
                        CanEdit = true;
                    }
                    if (!VarGeneral.TString.ChkStatShow(value.Eqar_FilStr, 23))
                    {
                        IfDelete = false;
                    }
                    else
                    {
                        IfDelete = true;
                    }
                }
            }
        }


        private void XFrmEqarSale_Load(object sender, EventArgs e)
        {
            Permmission = dbc.Get_PermissionID(VarGeneral.UserID);
            if (columns_Names_visible.Count == 0)
            {
                columns_Names_visible.Add("EqarSaleNo", new ColumnDictinary("الرقـــــم", "No", ifDefault: true, ""));
                columns_Names_visible.Add("EqarNo", new ColumnDictinary("الرقـــــم", "No", ifDefault: true, ""));
                columns_Names_visible.Add("NameA", new ColumnDictinary("الاسم عربي", "Arabic Name", ifDefault: true, ""));
                columns_Names_visible.Add("NameE", new ColumnDictinary("الاسم الانجليزي", "English Name", ifDefault: false, ""));
                columns_Names_visible.Add("AinNo", new ColumnDictinary("رقم العين", "Eye No", ifDefault: false, ""));
            }

        }

        private void t_EqarSalesBindingSource_AddingNew(object sender, AddingNewEventArgs e)
        {

            T_EqarSale et = new T_EqarSale();
            et.EqarSaleID = db.MaxEqarSaleNo;

            et.EqarSaleNo = db.MaxEqarSaleNo.ToString();
            e.NewObject = et;
            EqarIDTextEdit.Focus();
        }

        private void ubar1_Button_Search_Click(object sender, Controls.BarEvArg e)
        {
            FrmSearch frm = new FrmSearch();
            frm.Tag = LangArEn;
            ICollection<KeyValuePair<string, ColumnDictinary>> animalsAsCollection = columns_Names_visible;
            foreach (KeyValuePair<string, ColumnDictinary> kvp in animalsAsCollection)
            {
                frm.columns_Names_visible.Add(kvp.Key, new FrmSearch.SColumnDictinary(kvp.Value.AText, kvp.Value.EText, kvp.Value.IfDefault, ""));
            }
            VarGeneral.SFrmTyp = "T_EqarSale";
            frm.TopMost = true;
            frm.ShowDialog();
            if (frm.SerachNo != "")
            {
                var q = (from i in db.T_EqarSales where i.EqarSaleNo == (frm.Serach_No) select i).FirstOrDefault();
                int index = db.T_EqarSales.ToBindingList<T_EqarSale>().IndexOf(q);
                if (index != -1)
                {

                    ubar1.Binding.Position = index;
                }
            }

        }

        private void GDateTextEdit_EditValueChanged(object sender, EventArgs e)
        {
            dateEdit1_EditValueChanged(sender, e);
        }

        private void HDateTextEdit_EditValueChanged(object sender, EventArgs e)
        {
            dateEdit1_EditValueChanged(sender, e);
        }
    }
}